Repository rathena/rathena, pull requests merged in 2018-11, with the labels that each got.

#3643 Corrected atcommand reloadscript and NPC dialogs
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/pc.cpp
Labels: status:code-review

#3646 Added multi level up level caps
  conf/battle/exp.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3592 Fixed instance id being lost for guilds
  src/map/guild.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3638 Corrected warping and OnTouch events
  src/map/status.cpp
Labels: status:code-review

#3523 Corrected renewal Steal formula
  src/map/pc.cpp
  src/map/pc.hpp
Labels: status:code-review

#3594 Corrected Instance timers when entering a map
  src/map/instance.cpp
  src/map/pc.cpp
Labels: status:code-review

#3647 Corrected Concentration's status icon
  src/map/status.cpp
Labels: status:code-review

#3651 Added login user count colorization
  conf/login_athena.conf
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginclif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3658 Removed dbmap/ers from login-server
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginchrif.cpp
  src/login/loginclif.cpp
  src/login/logincnslif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#3673 Implemented official buy/sell amount restrictions
  conf/battle/items.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pc.cpp
Labels: status:code-review

#3680 Added some additional guild loading checks
  src/map/clif.cpp
  src/map/guild.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3670 Corrected Ignition Break animation
  src/map/skill.cpp
Labels: status:code-review

#3669 Corrected script command setunitdata HP/Max HP
  src/map/script.cpp
Labels: status:code-review

#3595 Updated Hammer of God behavior
  db/pre-re/skill_db.txt
  db/re/skill_db.txt
  src/map/skill.cpp
Labels: status:code-review

#3621 Corrected Reins of Mount interaction with hiding
  src/map/script.cpp
Labels: status:code-review

#3648 Corrected Raid damage for renewal
  src/map/battle.cpp
Labels: status:code-review

#3683 Corrected trap splash count
  src/map/skill.cpp
Labels: status:code-review

#3684 Corrected Platinum Shotel and Curved Sword
  db/re/item_db.txt
Labels: status:code-review

#3656 Equipments/weapons from ep17.1
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review

#3696 Illusion of Labyrinth item DB
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: status:code-review

#3699 Fixed a potential crash on change map events
  src/map/pc.cpp
Labels: status:code-review

#3689 Corrected Absorb Spirit Sphere on self
  src/map/skill.cpp
Labels: status:code-review

#3235 Refactored item bonuses to utilize C++ features
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#3710 Add drop highlighting effect feature
  db/import-tmpl/item_flag.txt
  db/pre-re/item_flag.txt
  db/re/item_flag.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3631 Fixed possible string out of bounds in configurations
  conf/char_athena.conf
  conf/log_athena.conf
  src/char/char.cpp
  src/char/inter.cpp
  src/common/msg_conf.cpp
  src/map/chrif.cpp
  src/map/map.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3603 Updated CN Meteor and Lunatic CB behavior
  db/pre-re/skill_db.txt
  db/re/skill_cast_db.txt
  db/re/skill_db.txt
  db/re/skill_require_db.txt
  db/re/skill_unit_db.txt
  src/common/mmo.hpp
  src/map/itemdb.hpp
  src/map/skill.cpp
Labels: status:code-review

#3660 Corrected Electric Shocker versus MVP
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#3685 Corrected White Imprison and reflected damage
  src/map/battle.cpp
Labels: status:code-review

#3709 Corrected a potential overflow in item bonuses
  src/map/pc.hpp
Labels: status:code-review

#3713 Corrected Stone Hard Skin Rune effects
  src/map/battle.cpp
  src/map/status.cpp
Labels: status:code-review

#3714 Corrected possible item loss during char login
  src/map/pc.cpp
Labels: status:code-review
