Repository rathena/rathena, pull requests merged in 2018-04, with the labels that each got.

#3011 Corrected Biscuit Stick bonus
  db/re/item_db.txt
Labels: status:code-review

#2781 Fixed a few typos and language mistakes
  npc/airports/airships.txt
  npc/airports/izlude.txt
  npc/cities/aldebaran.txt
  npc/cities/amatsu.txt
  npc/cities/ayothaya.txt
  npc/cities/comodo.txt
  npc/cities/einbech.txt
  npc/cities/einbroch.txt
  npc/cities/geffen.txt
  npc/cities/gonryun.txt
  npc/cities/hugel.txt
  npc/cities/izlude.txt
  npc/cities/jawaii.txt
  npc/cities/lighthalzen.txt
  npc/cities/lutie.txt
  npc/cities/manuk.txt
  npc/cities/morocc.txt
  npc/cities/payon.txt
  npc/cities/prontera.txt
  npc/cities/rachel.txt
  npc/cities/splendide.txt
  npc/cities/umbala.txt
  npc/cities/veins.txt
  npc/cities/yuno.txt
  npc/custom/card_remover.txt
  npc/custom/etc/bank.txt
  npc/custom/etc/blackjack.txt
  npc/custom/etc/marriage.txt
  npc/custom/etc/monster_arena.txt
  npc/custom/etc/penal_servitude.txt
  npc/custom/etc/quest_warper.txt
  npc/custom/events/disguise.txt
  npc/custom/events/holiday/hallow06.txt
  npc/custom/events/holiday/uneasy_cemetery.txt
  npc/custom/events/holiday/valentinesdayexp.txt
  npc/custom/jobmaster.txt
  npc/custom/official/GeffenMagicTournament.txt
  npc/custom/quests/bandit_beard.txt
  npc/custom/quests/elvenear.txt
  npc/custom/quests/event_6_new_hats.txt
  npc/custom/quests/jewel_case.txt
  npc/custom/quests/may_hats.txt
  npc/custom/quests/tha_statues.txt
  npc/custom/quests/thq/THQS_ChattingNPC.txt
  npc/custom/quests/thq/THQS_GuildNPC.txt
  npc/custom/quests/thq/THQS_QuestNPC.txt
  npc/custom/quests/thq/THQS_Quests.txt
  npc/custom/quests/thq/THQS_TTShop.txt
  npc/custom/quests/umbalian_language.txt
  npc/custom/woe_controller.txt
  npc/re/instances/HorrorToyFactory.txt
  npc/re/merchants/bio4_reward.txt
  npc/re/quests/quests_15_1.txt
Labels: component:script, mode:renewal, priority:low, status:code-review, type:maintenance

#3008 Added a config for disabling novice/summoner character creation
  conf/battle/player.conf
  conf/char_athena.conf
  src/char/char.cpp
  src/char/char.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/status.cpp
Labels: status:code-review

#3027 Adjusted Madogear interaction with skills
  src/map/pc.cpp
Labels: status:code-review

#3012 Corrected a potential integer overflow
  src/map/battle.cpp
Labels: status:code-review

#3014 Updated Shadow Chaser skills
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#3040 No matter what MAX_ITEM_RDM_OPT is, send 5 random options
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:enhancement

#3028 Resolved storage saving on server crash
  src/map/storage.cpp
Labels: status:code-review

#2954 New items, some fixes and missing duplicates
  db/re/item_db.txt
  db/re/item_trade.txt
  npc/re/custom/lasagna/lasagna_npcs.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#2912 Removed a stack push from getvar
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2902 Made the second parameter for bonus script command optional
  db/pre-re/item_combo_db.txt
  db/pre-re/item_db.txt
  db/re/item_combo_db.txt
  db/re/item_db.txt
  doc/item_bonus.txt
  src/map/script.cpp
Labels: component:script, type:enhancement

#2791 Phantasmagorika Mobskill Placeholder
  db/re/mob_skill_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#3043 Added script command mail
  doc/script_commands.txt
  src/char/int_mail.cpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3047 Corrected Homunculus healing
  src/map/homunculus.cpp
Labels: status:code-review

#3069 Removed ranged attack bonus from Hunting Arrow
  db/re/item_db.txt
Labels: status:code-review

#3080 Corrected some shadow equipment
  db/re/item_db.txt
Labels: status:code-review
