Repository rathena/rathena, pull requests merged in 2018-07, with the labels that each got.

#3261 Added a 'force' option to attachrid
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3260 Added possibility to log without attached player
  src/map/log.cpp
  src/map/log.hpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3244 Added Guild Storage Expansion Skill
  conf/msg_conf/map_msg.conf
  db/guild_skill_tree.txt
  db/pre-re/skill_db.txt
  db/re/skill_db.txt
  doc/script_commands.txt
  sql-files/main.sql
  sql-files/upgrades/upgrade_20180623.sql
  src/char/char.cpp
  src/char/int_guild.cpp
  src/char/int_guild.hpp
  src/char/int_storage.cpp
  src/common/mmo.hpp
  src/config/packets.hpp
  src/map/atcommand.cpp
  src/map/guild.cpp
  src/map/script_constants.hpp
  src/map/storage.cpp
  src/map/storage.hpp
Labels: status:code-review

#3274 Extra npc checks
  npc/merchants/advanced_refiner.txt
  npc/merchants/refine.txt
  npc/other/card_trader.txt
  npc/quests/seals/mjolnir_seal.txt
  npc/re/instances/SarahAndFenrir.txt
  npc/re/jobs/2e/kagerou_oboro.txt
  npc/re/jobs/novice/academy.txt
  npc/re/merchants/HorrorToyFactory_merchants.txt
  npc/re/merchants/OldGlastHeim_merchants.txt
  npc/re/merchants/advanced_refiner.txt
  npc/re/merchants/bio4_reward.txt
  npc/re/merchants/blessed_refiner.txt
  npc/re/merchants/enchan_ko.txt
  npc/re/merchants/enchan_mal.txt
  npc/re/merchants/enchan_mora.txt
  npc/re/merchants/enchan_upg.txt
  npc/re/merchants/hd_refiner.txt
  npc/re/merchants/refine.txt
  npc/re/merchants/shadow_refiner.txt
  npc/re/merchants/ticket_refiner.txt
  npc/re/quests/quests_malaya.txt
Labels: component:script, status:code-review

#3263 Fixed a few compiler warnings on clang
  src/common/utils.cpp
  src/map/atcommand.cpp
  src/map/channel.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/guild.cpp
  src/map/homunculus.cpp
  src/map/log.cpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/storage.cpp
  src/map/unit.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#3288 Fixed a bug with warlock's spheres
  src/map/clif.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#3289 Corrected SC_MTF_CRIDAMAGE bonus not triggering
  src/map/status.cpp
Labels: status:code-review

#3290 Updated Shield Spell behavior
  src/map/pc.cpp
Labels: status:code-review

#3271 Refactored roulette system
  conf/battle/feature.conf
  db/pre-re/item_db.txt
  doc/script_commands.txt
  sql-files/logs.sql
  sql-files/upgrades/upgrade_20180705_logs.sql
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3292 Updated Axe Mastery behavior
  src/map/battle.cpp
Labels: status:code-review

#3291 Updated Masquerade effects
  src/map/status.cpp
Labels: status:code-review

#3294 Cleaned up Summer 2 code
  conf/help.txt
  src/char/inter.cpp
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3298 Corrected some item bonuses not triggering
  src/map/battle.cpp
Labels: status:code-review

#3299 Adjusted Shield Chain range
  db/pre-re/skill_db.txt
  db/re/skill_db.txt
Labels: status:code-review

#3303 Pets should mimic master's walk speed
  src/map/homunculus.cpp
  src/map/status.cpp
Labels: status:code-review

#3306 Fixed Guild Storage Expansion skill saving
  src/char/int_guild.cpp
Labels: status:code-review

#3234 Banquet for Heroes ep 16.1
  db/re/instance_db.txt
  db/re/item_db.txt
  db/re/mob_db.txt
  db/re/quest_db.txt
  npc/jobs/2-2/crusader.txt
  npc/pre-re/jobs/2-2/crusader.txt
  npc/pre-re/quests/cooking_quest.txt
  npc/pre-re/quests/first_class/tu_archer.txt
  npc/pre-re/quests/quests_13_1.txt
  npc/pre-re/quests/quests_morocc.txt
  npc/pre-re/quests/seals/brisingamen_seal.txt
  npc/pre-re/quests/seals/megingard_seal.txt
  npc/pre-re/quests/the_sign_quest.txt
  npc/pre-re/scripts_athena.conf
  npc/pre-re/scripts_jobs.conf
  npc/pre-re/scripts_warps.conf
  npc/pre-re/warps/cities/prontera.txt
  npc/pre-re/warps/guildcastles.txt
  npc/quests/cooking_quest.txt
  npc/quests/first_class/tu_archer.txt
  npc/quests/quests_13_1.txt
  npc/quests/quests_morocc.txt
  npc/quests/seals/brisingamen_seal.txt
  npc/quests/seals/megingard_seal.txt
  npc/quests/the_sign_quest.txt
  npc/re/instances/RitualOfBlessing.txt
  npc/re/instances/RoomOfConsciousness.txt
  npc/re/jobs/2-2/crusader.txt
  npc/re/jobs/3-2/royal_guard.txt
  npc/re/jobs/repair.txt
  npc/re/mobs/dungeons/prt_prison.txt
  npc/re/mobs/dungeons/prt_q.txt
  npc/re/mobs/prt_cas.txt
  npc/re/quests/cooking_quest.txt
  npc/re/quests/first_class/tu_archer.txt
  npc/re/quests/quests_13_1.txt
  npc/re/quests/quests_16_1.txt
  npc/re/quests/seals/brisingamen_seal.txt
  npc/re/quests/seals/megingard_seal.txt
  npc/re/quests/the_sign_quest.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_jobs.conf
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/cities/prontera.txt
  npc/re/warps/guildcastles.txt
  npc/warps/cities/prontera.txt
  npc/warps/guildcastles.txt
Labels: component:script, status:code-review

#3311 Hid timer function parameters in a macro
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_cnslif.cpp
  src/char/char_logif.cpp
  src/char/char_logif.hpp
  src/char/int_auction.cpp
  src/char/int_guild.cpp
  src/char/int_mail.cpp
  src/char/int_mail.hpp
  src/common/cli.cpp
  src/common/cli.hpp
  src/common/socket.cpp
  src/common/sql.cpp
  src/common/timer.hpp
  src/login/ipban.cpp
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginchrif.cpp
  src/map/battle.cpp
  src/map/battleground.cpp
  src/map/cashshop.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/elemental.cpp
  src/map/guild.cpp
  src/map/homunculus.cpp
  src/map/instance.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mapreg.cpp
  src/map/mercenary.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#3297 Initial Release of Attendance Feature
  conf/battle/feature.conf
  conf/groups.conf
  conf/map_athena.conf
  conf/msg_conf/map_msg.conf
  db/import-tmpl/attendance.yml
  db/pre-re/attendance.yml
  db/re/attendance.yml
  db/re/item_db.txt
  db/re/item_package.txt
  db/re/item_trade.txt
  doc/script_commands.txt
  src/common/utilities.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/date.cpp
  src/map/date.hpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pc_groups.hpp
  src/map/script_constants.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3309 Updated max recovery weight to 70% for renewal
  conf/battle/player.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
Labels: status:code-review

#3321 Resolved Guild Storage Expansion not updating
  src/char/int_storage.cpp
  src/map/storage.cpp
Labels: status:code-review

#2943 Cleaned up the mapflag system
  db/skill_damage_db.txt
  doc/mapflags.txt
  doc/script_commands.txt
  src/common/utilities.hpp
  src/config/core.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/buyingstore.cpp
  src/map/chat.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/itemdb.cpp
  src/map/mail.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/trade.cpp
  src/map/unit.cpp
Labels: status:code-review

#3329 Fixed npc location for Lutie quest
  npc/cities/lutie.txt
  npc/pre-re/cities/lutie.txt
  npc/pre-re/scripts_athena.conf
  npc/re/cities/lutie.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, type:bug

#3332 Further cleanup to mapflags
  doc/mapflags.txt
  doc/script_commands.txt
  npc/mapflag/skill_damage.txt
  src/config/core.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/npc.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: status:code-review

#3279 Hotfix for issue 3277
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#3347 Cleaned up map data storage
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_mapif.cpp
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/buyingstore.cpp
  src/map/channel.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/guild.cpp
  src/map/instance.cpp
  src/map/intif.cpp
  src/map/itemdb.cpp
  src/map/log.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/party.cpp
  src/map/path.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/vending.cpp
Labels: status:code-review

#3354 Initial release of private airship system
  conf/battle/feature.conf
  conf/msg_conf/map_msg.conf
  db/re/item_db.txt
  npc/re/mapflag/privateairship.txt
  npc/re/scripts_mapflags.conf
  sql-files/logs.sql
  sql-files/upgrades/upgrade_20180729_logs.sql
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.hpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/map.hpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#3358 Corrected Spiritual Sphere Absorption and Cursed Circle interaction
  src/map/status.cpp
Labels: status:code-review
