Repository rathena/rathena, pull requests merged in 2018-05, with the labels that each got.

#3075 Updated Bullet Cartridges
  db/re/item_db.txt
Labels: status:code-review

#3088 Corrected Demonic Fire and FE Acid behavior
  db/pre-re/skill_db.txt
  db/re/skill_db.txt
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#3096 Updated Readme.md
  README.md
Labels: component:documentation, priority:low

#3098 Fixed UF_RANGEDSINGLEUNIT skill interactions
  src/map/skill.cpp
Labels: status:code-review

#3103 Added atcommand for limited sale
  conf/groups.conf
  conf/help.txt
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/pc.hpp
  src/map/pc_groups.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3110 Added Excellion Armor and Wing
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: status:code-review

#3107 Added a template function for std::map search
  src/common/utilities.hpp
  src/map/mercenary.cpp
  src/map/mob.cpp
  src/map/pet.cpp
  src/map/storage.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3125 Removed old visual studio projects from gitignore
  .gitignore
Labels: component:core, mode:prerenewal, mode:renewal, type:maintenance

#3120 Corrected skills that lose mob targets
  db/pre-re/skill_cast_db.txt
  db/re/skill_cast_db.txt
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#3124 Fixed login mail notification
  src/map/intif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3117 Cleaned up item broadcast code
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/intif.cpp
  src/map/intif.hpp
Labels: status:code-review

#3115 Corrected reflected damage applying twice
  src/map/battle.cpp
Labels: status:code-review

#3119 Added an option to disable homun autofeed notify
  conf/battle/homunc.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3116 Fixed an invalid declaration of cached events
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3130 Fixed a few hardcoded limits in status.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#3109 Added support for changedress command
  conf/atcommand_athena.conf
  conf/groups.conf
  conf/help.txt
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3126 Corrected Baby Dragon hat bonus
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: status:code-review

#3128 Added Gambler Seal and Gambler Card item combo
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: status:code-review

#3131 Corrected QD Shot and Crimson Marker interaction
  src/map/skill.cpp
Labels: status:code-review

#3140 Fixed a few items having getrefine in script
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3138 Corrected Invisibility CRI bonus
  src/map/status.cpp
Labels: status:code-review

#3151 Added missing Imperial Set Combos
  db/re/item_combo_db.txt
  db/re/item_db.txt
  doc/item_bonus.txt
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#3161 Removed duplicates and added some missing mapflags
  npc/mapflag/night.txt
  npc/re/mapflag/nobranch.txt
  npc/re/mapflag/noicewall.txt
  npc/re/mapflag/nomemo.txt
  npc/re/mapflag/noteleport.txt
  npc/re/mapflag/nowarpto.txt
  npc/re/mapflag/partylock.txt
  npc/re/mapflag/restricted.txt
Labels: component:script

#3162 Added extra check in some renewal instances to prevent unexpected behaviour
  npc/re/instances/FacewormsNest.txt
  npc/re/instances/LastRoom.txt
  npc/re/instances/SaraMemory.txt
Labels: component:script, mode:renewal, type:enhancement

#3145 Moved remaining refine NPC to the database
  db/re/refine_db.yml
  doc/script_commands.txt
  npc/merchants/advanced_refiner.txt
  npc/re/jobs/novice/academy.txt
  npc/re/merchants/advanced_refiner.txt
  npc/re/merchants/hd_refiner.txt
  npc/re/merchants/refine.txt
  npc/re/merchants/ticket_refiner.txt
  src/map/script_constants.hpp
  src/map/status.hpp
Labels: status:code-review

#3170 Corrected Mora NPC name
  npc/re/quests/quests_mora.txt
Labels: status:code-review

#3149 Corrected B.S. Sacramenti behavior
  src/map/map.cpp
  src/map/skill.cpp
Labels: status:code-review

#3141 Script/airship instance
  db/re/instance_db.txt
  db/re/item_combo_db.txt
  db/re/item_db.txt
  db/re/mob_db.txt
  db/re/quest_db.txt
  npc/re/instances/AirshipAssault.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review
