Repository rathena/rathena, pull requests merged in 2018-02, with the labels that each got.

#2795 Workaround to solve issue with news cards in enchants NPCs
  npc/events/RWC_2012.txt
  npc/other/Global_Functions.txt
  npc/re/merchants/card_separation.txt
  npc/re/merchants/enchan_ko.txt
  npc/re/merchants/enchan_mal.txt
  npc/re/merchants/enchan_mora.txt
  npc/re/merchants/enchan_upg.txt
  npc/re/quests/quests_malangdo.txt
Labels: status:code-review, status:inprogress

#2882 Corrected Heat Barrel bonuses
  src/map/status.cpp
Labels: status:code-review

#2851 Updated card seller
  npc/custom/card_seller.txt
  src/map/script_constants.hpp
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2903 Fixed some autobonus scripts in item_db
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review

#2910 Updated Cultivation plant spawn formula
  src/map/mob.hpp
  src/map/skill.cpp
Labels: status:code-review

#2909 Updated Masquerade - Weakness behavior
  src/map/pc.cpp
Labels: status:code-review

#2907 Fixed Mystical Amplification and Chain Lightning
  src/map/skill.cpp
Labels: status:code-review

#2883 Made mercenary db dynamic
  src/common/mmo.h
  src/map/mercenary.cpp
  src/map/mercenary.hpp
  src/map/script.cpp
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#2840 (Clear) command script
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#2922 Fixed compatibility with newer MySQL client library derivatives
  src/common/sql.c
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#2908 Updated guild skill Guard Up
  src/map/status.cpp
Labels: status:code-review

#2917 Updated Tiger Fist stop duration
  db/pre-re/skill_cast_db.txt
  db/re/skill_cast_db.txt
  src/map/skill.cpp
Labels: status:code-review

#2921 Reactors from Charleston Instance
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#2914 Fixed item creation with full inventory
  conf/battle/skill.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/skill.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2846 Fixed STR/INT/VIT Biscuit Sticks item script. Fixed #2841
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review, type:maintenance

#2915 Changing DBMap into STL::Map in C++ for guild storage
  src/map/storage.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#2924 Cart Termination should be affected by % effects
  db/re/skill_db.txt
Labels: component:skill, mode:renewal, type:bug

#2890 Corrected Disarm and Steal Coin formulas
  src/map/pc.cpp
  src/map/skill.cpp
Labels: status:code-review

#2926 Cleaned up atcommand accinfo leftovers
  conf/msg_conf/char_msg.conf
  doc/packet_interserv.txt
  src/char/char_logif.cpp
  src/char/char_logif.hpp
  src/char/inter.cpp
  src/login/loginchrif.cpp
Labels: status:code-review

#2911 Fixed display of newly added pet eggs in storage
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2901 Converted pet_data::petDB into a getter function
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#2928 Fixed Skin Tempering (BS_SKINTEMPER) fire resistance percentage.
  src/map/status.cpp
Labels: component:skill

#2932 Added a new packet for the equipment swap system
  src/map/clif_packetdb.hpp
Labels: component:core, status:code-review, type:bug

#2913 Fixed unitwalkto calls in unit walk events
  src/map/mob.cpp
  src/map/unit.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2933 Resolved renewal ASPD and two-handed weapons
  src/map/status.cpp
Labels: status:code-review

#2935 Fixed default traps invisibility setting for renewal
  conf/battle/skill.conf
  src/map/battle.cpp
Labels: component:skill, mode:renewal, priority:low, status:code-review, status:confirmed, type:bug

#2941 Fixed party_skill_check not updating the party members
  src/map/party.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, priority:low, status:confirmed, type:bug
