Repository rathena/rathena, pull requests merged in 2018-08, with the labels that each got.

#3384 Cleaned up map storage type
  doc/script_commands.txt
  src/char/char.cpp
  src/common/mmo.hpp
  src/common/utilities.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/intif.cpp
  src/map/itemdb.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#3367 Official Spiritual Sphere Absorption behavior
  src/map/skill.cpp
Labels: status:code-review

#3394 Corrected SECURE_NPCTIMEOUT behavior
  src/config/secure.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/script.cpp
Labels: status:code-review

#2977 Update Renewal and Pre-renewal Morocc NPCs
  db/re/item_db.txt
  db/re/item_trade.txt
  npc/battleground/bg_common.txt
  npc/jobs/2-1/blacksmith.txt
  npc/merchants/shops.txt
  npc/merchants/socket_enchant2.txt
  npc/pre-re/merchants/shops.txt
  npc/pre-re/merchants/socket_enchant2.txt
  npc/pre-re/quests/quests_morocc.txt
  npc/pre-re/scripts_athena.conf
  npc/quests/quests_morocc.txt
  npc/re/battleground/bg_common.txt
  npc/re/merchants/3rd_trader.txt
  npc/re/merchants/shops.txt
  npc/re/merchants/socket_enchant2.txt
  npc/re/quests/mrsmile.txt
  npc/re/quests/quests_morocc.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:prerenewal, mode:renewal, priority:low, status:confirmed, status:need more info, type:bug

#3411 Item scripts from kRO 2017.05.10 update
  db/re/item_combo_db.txt
  db/re/item_db.txt
  db/re/mob_db.txt
Labels: status:code-review

#3414 Fix for issue #3412 'Global instance timer'
  src/map/instance.cpp
Labels: status:code-review

#3406 Updated mapcache tool
  src/tool/mapcache.cpp
Labels: status:code-review

#3405 Cleaned up map data checks
  src/common/utilities.hpp
  src/map/map.cpp
  src/map/pc.cpp
Labels: status:code-review

#3435 Corrected some map property issues
  src/map/atcommand.cpp
  src/map/map.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: status:code-review

#3429 Implemented news items from Illusion of Moon Light (kRO 2016.12.27)
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database

#3440 Implemented news items from Illusion of Vampire kRO 2017.01.25
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, status:code-review

#3434 Corrected server info display
  src/map/clif.cpp
Labels: status:code-review

#3444 Implemented news items from Illusion of Abyss kRO 2017.04.18
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, status:code-review

#3446 Implemented news items from Illusion of Luanda (kRO 2018.04.18)
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, status:code-review

#3449 Implemented cards from ep 17.1 (kRO 2018.08.13)
  db/re/item_db.txt
Labels: component:database, status:code-review

#3428 Updated default items's items script of attendance.yml
  db/re/item_db.txt
  doc/script_commands.txt
Labels: component:database, status:code-review

#3460 Cleaned up map property functions from PvP/GvG script commands
  src/map/script.cpp
Labels: status:code-review

#3452 Updated mob_drop parsing
  src/map/mob.cpp
Labels: status:code-review
