Repository rathena/rathena, pull requests merged in 2018-03, with the labels that each got.

#2929 Fixed no reiteration unit skills fail message back to USESKILL_FAIL_LEVEL
  src/map/skill.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, priority:low, status:confirmed, status:need more info, type:bug

#2948 Fixed Frenzy (LK_BERSERK) job level requirement.
  db/pre-re/skill_tree.txt
  db/re/skill_tree.txt
  src/map/pc.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, priority:low, status:code-review, status:confirmed, type:bug

#2951 Fixed Malangdo Culvert Warp
  npc/re/instances/MalangdoCulvert.txt
Labels: component:script, mode:renewal, priority:low, status:confirmed, type:bug

#2940 Fixed a few issues with TXT item db parsing
  db/re/item_db.txt
  src/map/itemdb.cpp
Labels: component:core, component:database, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2945 Fixed titles only being added on relog
  src/map/achievement.cpp
  src/map/pc.cpp
  src/map/pc.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#2942 Added support for the second summer costume
  db/re/item_db.txt
  src/map/atcommand.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2925 Added items 4951-4969
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#2961 Costumes update
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#2975 Added support for clients up to 2018-03-07bRagexeRE
  src/char/char.cpp
  src/map/clif.cpp
  src/map/clif_obfuscation.hpp
  src/map/clif_packetdb.hpp
  src/map/clif_shuffle.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#2985 Corrected Parasite Card script
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: status:code-review

#2986 Disabled achievement NPCs if feature is disabled
  npc/re/other/achievements.txt
Labels: component:script, mode:renewal, status:code-review, type:enhancement

#2988 Corrected Shadow Warrior double attack rate
  src/map/battle.cpp
Labels: status:code-review

#2980 Corrects Spirit/Charm absorption behaviour on Ninja Spirit Charm
  src/map/skill.cpp
Labels: status:code-review

#2957 Corrected guild storage saving
  src/map/storage.cpp
Labels: status:code-review

#2984 Corrected Lightning Walk requirements
  db/pre-re/skill_require_db.txt
  db/re/skill_require_db.txt
Labels: status:code-review

#2997 Fixes a map-server crash when using @showmobs
  src/map/atcommand.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#3000 Prevent unloadnpc script command to unload the invoking NPC.
  src/map/script.cpp
Labels: status:code-review

#2744 Corrected ShortWeaponDamageReturn behavior
  src/map/battle.cpp
Labels: status:code-review
