Repository rathena/rathena, pull requests merged in 2019-12, with the labels that each got.

#4362 Biolab Edda Weapon
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, status:code-review, status:inprogress

#4485 Corrected Rock Ridge monster spawn
  npc/re/mobs/fields/rockridge.txt
Labels: status:code-review

#4482 Converted Magic Mushroom Database to YAML
  db/import-tmpl/magicmushroom_db.yml
  db/magicmushroom_db.txt
  db/magicmushroom_db.yml
  db/pre-re/magicmushroom_db.yml
  db/re/magicmushroom_db.yml
  doc/yaml/db/magicmushroom_db.yml
  src/map/map-server.vcxproj
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4486 Fixed SC_KEEPING and SC_BARRIER exploit after classchange
  src/map/mob.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4480 Converted Abra Database to YAML
  db/abra_db.txt
  db/abra_db.yml
  db/import-tmpl/abra_db.txt
  db/import-tmpl/abra_db.yml
  doc/yaml/db/abra_db.yml
  src/map/map-server.vcxproj
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4484 Corrected Enchant Arms for older clients
  src/map/clif.cpp
  src/map/status.cpp
Labels: status:code-review

#4481 Converted Improvised Song Database to YAML
  db/import-tmpl/improvise_db.yml
  db/improvise_db.yml
  db/re/improvise_db.yml
  db/skill_improvise_db.txt
  doc/yaml/db/improvise_db.yml
  src/map/map-server.vcxproj
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4489 Moved Material Seller shop to Renewal
  npc/merchants/shops.txt
  npc/re/merchants/shops.txt
Labels: status:code-review

#4396 Adding Missing Portals
  npc/warps/cities/lighthalzen.txt
  npc/warps/cities/yuno.txt
Labels: component:script, mode:prerenewal, mode:renewal, type:bug

#4487 Migrated atcommand aliases and help to YAML
  conf/atcommand_athena.conf
  conf/atcommands.yml
  conf/battle/gm.conf
  conf/help.txt
  conf/import-tmpl/atcommands.yml
  conf/map_athena.conf
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_grm.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/common/cli.cpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/map.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#4490 Fixed 'Finding the Moving Island' quest spawning the wrong monsters on pre-re
  npc/quests/quests_moscovia.txt
Labels: component:script, mode:prerenewal, status:code-review, type:bug

#4306 Added primary key to tables that lack them & Dropped sstatus table
  sql-files/main.sql
  sql-files/tools/convert_engine_innodb.sql
  sql-files/tools/convert_engine_myisam.sql
  sql-files/upgrades/upgrade_20191222.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4385 Allow NPC view data modifications
  db/import-tmpl/mob_avail.txt
  db/import-tmpl/mob_avail.yml
  db/mob_avail.txt
  doc/mob_avail.txt
  doc/script_commands.txt
  doc/yaml/db/mob_avail.yml
  src/map/clif.cpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/unit.cpp
  src/map/unit.hpp
  src/tool/csv2yaml.cpp
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#2526 Corrected Vacuum Extreme behavior
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#4493 Corrected Gatling Fever damage
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4496 Added Merchant Seller to Pre-renewal
  npc/pre-re/merchants/shops.txt
Labels: component:script, mode:prerenewal, status:code-review
