Repository rathena/rathena, pull requests merged in 2019-01, with the labels that each got.

#3812 Corrected Honor Token weight
  db/re/item_db.txt
Labels: status:code-review

#3825 Corrected Faceworm Larva Card bonus
  db/re/item_db.txt
Labels: status:code-review

#3827 Corrected Cat Ear Beret bonus
  db/re/item_db.txt
Labels: status:code-review

#3828 Fixed Costume Pocketwatch Hair Ornament location
  db/re/item_db.txt
Labels: status:code-review

#3824 Corrected Palace Guard Cap bonus
  db/re/item_db.txt
Labels: status:code-review

#3829 Corrected Shell of Resistance equip restriction
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: status:code-review

#3793 Added Clothing Effect Removal Service
  npc/re/merchants/clothing_buff_removal.txt
  npc/re/scripts_athena.conf
  src/map/atcommand.cpp
Labels: component:script, mode:renewal, status:code-review, type:bug

#3830 Added missing Costume Flying Galapago
  db/re/item_db.txt
Labels: status:code-review

#3791 Fixed duration for items 12274 and 12275
  db/pre-re/item_db.txt
Labels: component:database, mode:prerenewal, type:bug

#3822 Corrected Shadow Staff script error
  db/re/item_db.txt
Labels: status:code-review

#3823 Corrected Owl Viscount Silk Hat script error
  db/re/item_db.txt
Labels: status:code-review

#3799 Allow increasing connection limit on linux
  configure
  configure.in
  src/common/socket.cpp
  src/common/socket.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3808 Corrected item bonus FixedCastRate
  src/map/pc.cpp
Labels: status:code-review

#3850 Fixed pre-re Barricade HP value
  db/pre-re/mob_db.txt
Labels: component:database, mode:prerenewal, priority:low, status:confirmed, type:bug

#3848 Fixed Reflect Damage not reflecting damage
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/skill.cpp
Labels: status:code-review

#3849 Adjusted reload item database
  src/map/itemdb.cpp
Labels: status:code-review

#3853 Added new Rebellion Shops
  db/re/item_db.txt
  npc/re/merchants/shops.txt
Labels: status:code-review

#3857 Added MS support for the function macro
  src/common/cbasetypes.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3877 OnTouch Royal messenger NPC
  npc/re/quests/quests_16_1.txt
Labels: component:script

#3885 Fixed a few more leftovers from 64bit tick
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/elemental.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pet.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/unit.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3876 Corrected skills that give bonuses while sitting
  src/map/clif.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#3887 Fixed CDP not failing when haven't met the requirements
  src/map/skill.cpp
Labels: status:code-review

#3888 Fixed a crash from MVP Ladder Warper
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3826 Corrected Sarah's Battle Robe bonus
  db/re/item_db.txt
Labels: status:code-review

#3802 Updated Quagmire status removal list
  src/map/status.cpp
Labels: status:code-review

#3895 Disconnect player on map-server switch failure
  src/map/chrif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3873 Corrected status attack's element
  src/map/battle.cpp
Labels: status:code-review

#3845 Corrected Sling Item bonuses
  db/pre-re/item_db.txt
  db/re/item_db.txt
  src/map/itemdb.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#3890 Updated script command getmapxy parameters
  doc/script_commands.txt
  npc/battleground/bg_common.txt
  npc/custom/events/devil_square.txt
  npc/custom/events/mvp_ladder.txt
  npc/custom/quests/hunting_missions.txt
  npc/events/halloween_2009.txt
  npc/other/gm_npcs.txt
  npc/other/monster_race.txt
  npc/other/poring_war.txt
  npc/quests/guildrelay.txt
  npc/quests/partyrelay.txt
  npc/re/instances/FacewormsNest.txt
  npc/re/instances/HorrorToyFactory.txt
  npc/re/instances/IsleOfBios.txt
  npc/re/instances/MalangdoCulvert.txt
  npc/re/instances/MorseCave.txt
  npc/re/instances/OldGlastHeim.txt
  npc/re/instances/SarahAndFenrir.txt
  npc/re/jobs/3-1/guillotine_cross.txt
  npc/re/jobs/3-1/ranger.txt
  npc/re/quests/quests_15_2.txt
  npc/re/quests/quests_16_1.txt
  npc/re/quests/quests_malangdo.txt
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: status:code-review
