Repository rathena/rathena, pull requests merged in 2019-11, with the labels that each got.

#4433 Added support for constants in csv2yaml
  src/tool/csv2yaml.cpp
Labels: component:tool, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4442 Added unsigned rate support for yaml
  src/common/database.cpp
  src/common/database.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4441 Added progress for loading yaml databases
  src/common/database.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:enhancement

#4423 quest_16_1 typo fix
  npc/re/quests/quests_16_1.txt
Labels: component:script, mode:renewal, type:bug

#4445 Corrected Succession of the Prince quest
  npc/pre-re/quests/quests_morocc.txt
Labels: status:code-review

#4438 Fixed #4437
  db/re/mob_db.txt
Labels: component:database, mode:renewal, type:bug

#4451 Fixed appveyor building
  src/common/database.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#4448 Updated the CSV2YAML tool to utilize YAML Emitter
  .gitattributes
  doc/yaml/db/guild_skill_tree.yml
  doc/yaml/db/license.yml
  doc/yaml/db/pet_db.yml
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4458 Corrected Bacsojin Pet
  db/re/pet_db.yml
Labels: status:code-review
