Repository rathena/rathena, pull requests merged in 2019-08, with the labels that each got.

#4281 Corrected Tornado Axe equip level
  db/re/item_db.txt
Labels: status:code-review

#4290 Corrected Clock Tower Gatekeeper dialog
  npc/cities/aldebaran.txt
Labels: status:code-review

#4294 Synced Geffen Magic Tournament mob_skill_db name with mob_db name
  db/re/mob_skill_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#4295 Fixed Old Money Pocket being unusable
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review

#4200 Empty message in announce script command
  src/map/clif.cpp
  src/map/intif.cpp
Labels: status:code-review

#4291 Added quest checks for Geffen Magic Tournament
  npc/custom/official/GeffenMagicTournament.txt
Labels: status:code-review

#4292 Corrected pet bonuses not applying
  conf/battle/pet.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pet.cpp
  src/map/status.cpp
Labels: status:code-review

#4298 Hotfix #4297 instance_warpall
  npc/custom/official/GeffenMagicTournament.txt
  npc/instances/NydhoggsNest.txt
  npc/instances/SealedShrine.txt
  npc/re/instances/OctopusCave.txt
Labels: component:script, status:code-review

#4300 Reduce list field length in ipbanlist table from 255 to 15
  sql-files/main.sql
  sql-files/upgrades/upgrade_20190814.sql
  src/login/ipban.cpp
Labels: status:code-review

#4243 Updated Euphy's WoE controller using the new mail script command
  npc/custom/woe_controller.txt
Labels: component:script, status:code-review

#4229 Small isequippedcnt script command update
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#4301 Drop ragsrvinfo functionality
  conf/inter_athena.conf
  sql-files/main.sql
  sql-files/upgrades/upgrade_20190815.sql
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_mapif.cpp
  src/char/char_mapif.hpp
  src/map/atcommand.cpp
  src/map/chrif.cpp
  src/map/chrif.hpp
Labels: status:code-review

#4270 Removed the option ID requirement for some **item3 functions
  src/map/script.cpp
Labels: status:code-review

#4307 Fixed typo in item 5330's script
  db/re/item_db.txt
Labels: status:code-review
