Repository rathena/rathena, pull requests merged in 2019-02, with the labels that each got.

#3914 Fixed a possible mail send server crash
  src/map/clif.cpp
  src/map/mail.cpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#3912 Fixed a possible pet server crash
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#3920 Fixed a possible script exploit
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#3910 Cleaned up script command argument parsing
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script.hpp
Labels: status:code-review

#3913 Fixed accessory equipping with cards
  src/map/pc.cpp
Labels: status:code-review

#3903 Corrected some card combos
  db/re/item_combo_db.txt
  src/map/script.cpp
Labels: status:code-review

#3844 Fixed Old Card Album and High Weapon Box scripts
  db/re/item_db.txt
Labels: status:code-review

#3922 Corrected script command getmapxy
  src/map/script.cpp
Labels: status:code-review

#3921 Fixed bg_get_data script command
  src/map/script.cpp
Labels: status:code-review

#3935 Fixed Ice Wall units to match their official behavior
  db/pre-re/skill_cast_db.txt
  db/pre-re/skill_unit_db.txt
  db/re/skill_cast_db.txt
  db/re/skill_unit_db.txt
  src/map/skill.cpp
Labels: status:code-review

#3927 Converted remaining C comments
  .gitignore
  conf/battle/gm.conf
  conf/battle/misc.conf
  conf/char_athena.conf
  conf/login_athena.conf
  conf/motd.txt
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  configure
  db/mob_item_ratio.txt
  db/pre-re/item_delay.txt
  db/pre-re/skill_require_db.txt
  db/re/item_delay.txt
  db/re/skill_require_db.txt
  db/spellbook_db.txt
  doc/atcommands.txt
  doc/ea_job_system.txt
  doc/item_group.txt
  doc/packet_interserv.txt
  doc/script_commands.txt
  doc/skill_require_db.txt
  doc/source_doc.txt
  npc/custom/jobmaster.txt
  npc/re/jobs/3-1/rune_knight.txt
  src/char/char.cpp
  src/char/char_mapif.cpp
  src/char/int_clan.cpp
  src/char/int_guild.cpp
  src/char/int_party.cpp
  src/char/inter.cpp
  src/common/mmo.hpp
  src/common/showmsg.cpp
  src/custom/battle_config_struct.inc
  src/login/login.cpp
  src/login/loginlog.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/mapreg.cpp
  src/map/mercenary.hpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/status.cpp
  src/map/unit.cpp
  tools/check-doc.pl
Labels: status:code-review

#3932 Corrected script commands containing arrays
  src/map/script.cpp
Labels: status:code-review

#3933 Fixed Camouflage
  src/map/clif.cpp
  src/map/status.cpp
Labels: status:code-review

#3941 Cleaned up cmake output
  .gitignore
  doc/script_commands.txt
  src/common/CMakeLists.txt
Labels: status:code-review

#3942 Corrected loyal pet bonuses
  db/pre-re/pet_db.txt
  db/re/pet_db.txt
Labels: status:code-review

#3945 Fixed an issue with progressbars
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3946 Added correct allocation info to strlib
  src/common/strlib.cpp
  src/common/strlib.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3952 Fixed Taekwon Running fixed cast time
  db/re/skill_cast_db.txt
Labels: status:code-review

#3954 Uncommented progressbar part in Devil tower
  npc/re/instances/DevilTower.txt
Labels: component:script, status:code-review

#3966 Corrected RODEX message size
  sql-files/main.sql
Labels: status:code-review

#3970 Fixed Eddga's HP
  db/re/mob_db.txt
Labels: status:code-review

#3967 Adjusted death event for Emperium Battleground
  doc/script_commands.txt
  npc/custom/battleground/bg_emp.txt
Labels: status:code-review

#3991 Added the skeleton for the yaml converter
  .travis.yml
  csv2yaml.bat
  rAthena.sln
  src/tool/Makefile.in
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.vcxproj
  src/tool/csv2yaml.vcxproj.filters
  tools/csv2yaml.bat
Labels: component:tool, mode:prerenewal, mode:renewal, status:code-review, type:maintenance
