Repository rathena/rathena, pull requests merged in 2019-07, with the labels that each got.

#3924 [Suggestion] convertpcinfo script command
  doc/script_commands.txt
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: component:script, status:code-review, status:inprogress, type:enhancement, type:question

#4226 Fix for issue #4225 (clone issue)
  src/map/unit.cpp
Labels: status:code-review

#4227 Corrected autospell stacking
  src/map/pc.cpp
Labels: status:code-review

#4232 Fixed pet evolution upgrade script
  sql-files/upgrades/upgrade_20190309.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4240 Fixed invalid item errors in achievements
  src/map/achievement.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4239 Made mob sprite column unique
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  sql-files/upgrades/upgrade_20190628.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4248 Corrected Magnum Break delay
  db/pre-re/skill_cast_db.txt
  db/re/skill_cast_db.txt
  src/map/skill.cpp
Labels: status:code-review

#4228 Fixed STR affecting mob damage in pre-renewal
  conf/battle/battle.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/status.cpp
Labels: status:code-review

#4123 Cleaned up Joint Beat behavior
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#4251 Corrected a potential crash with Joint Beat
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#4156 Fixed Achievement Level progression
  src/map/achievement.cpp
  src/map/clif.cpp
Labels: status:code-review

#4255 Corrected another potential crash with Joint Beat
  src/map/skill.cpp
Labels: status:code-review

#4257 Corrected Strip duration
  src/map/skill.cpp
Labels: status:code-review

#4259 Corrected RENEWAL_ASPD macro processing
  src/map/pc.cpp
Labels: status:code-review

#4261 Corrected pre-renewal Heal formula
  src/map/skill.cpp
Labels: status:code-review

#4263 Corrected a compile warning on GCC 8
  src/char/char_clif.cpp
Labels: status:code-review

#4269 Properly free function script counter
  src/map/script.cpp
Labels: status:code-review

#4275 Removed leftover variable
  src/map/skill.cpp
Labels: status:code-review
