Repository rathena/rathena, pull requests merged in 2019-05, with the labels that each got.

#4139 Fixed potential race-condition possibility in cart item transaction
  src/map/pc.cpp
Labels: priority:high, status:code-review, type:bug

#4137 Fixed some bonuses getting capped
  src/map/pc.cpp
Labels: status:code-review

#4100 Renewal item database update
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database

#4148 Additional fixes for cart exploit
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/storage.cpp
Labels: priority:high, status:code-review

#4167 autobonus correction
  db/re/item_combo_db.txt
  db/re/item_db.txt
Labels: component:database, status:code-review

#4166 Added shadow items - ID range 24320~24424
  db/re/item_combo_db.txt
  db/re/item_db.txt
  db/re/item_trade.txt
Labels: component:database, status:code-review

#4157 Corrected Twin Pompom By JB item bonus
  db/import-tmpl/item_db.txt
  db/re/item_db.txt
Labels: status:code-review

#4186 Fix for issue #4153
  db/re/item_db.txt
Labels: status:code-review

#4188 Corrected new hats
  db/re/item_db.txt
Labels: status:code-review

#4143 viewpoint accept char id
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#4172 changed renewal start coordinates.
  src/config/const.hpp
Labels: mode:renewal, priority:low, status:code-review
