Repository rathena/rathena, pull requests merged in 2019-04, with the labels that each got.

#4067 Added setpcblock to some official scripts
  doc/script_commands.txt
  npc/re/custom/lasagna/lasagna_npcs.txt
  npc/re/instances/DevilTower.txt
  npc/re/instances/HorrorToyFactory.txt
  npc/re/instances/MorseCave.txt
  npc/re/instances/SarahAndFenrir.txt
  npc/re/merchants/nightmare_biolab.txt
  npc/re/quests/quests_15_2.txt
  npc/re/quests/quests_16_1.txt
  npc/re/quests/quests_rockridge.txt
  src/map/clif.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: component:script, status:code-review

#2382 Adjusted OnTouch overlap behavior
  src/map/clif.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/npc.cpp
  src/map/pc.hpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#4074 Fixed pre-renewal pet fullness values
  db/pre-re/pet_db.yml
  db/re/pet_db.yml
Labels: status:code-review

#3556 Updated Firewall cast check
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/unit.cpp
Labels: status:code-review

#4082 Fixed the upgrade script for pet evolution
  sql-files/upgrades/upgrade_20190309.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4091 Corrected Sword Stick equip requirements
  db/re/item_db.txt
Labels: status:code-review

#4086 Corrected Gunslinger shops
  db/re/item_db.txt
  npc/merchants/shops.txt
  npc/pre-re/merchants/shops.txt
  npc/re/merchants/shops.txt
Labels: status:code-review

#4084 Added Hanbok Bag item script
  db/re/item_db.txt
Labels: status:code-review

#4081 Added caps to item bonus rates
  src/map/pc.cpp
Labels: status:code-review

#4094 Corrected guild level increases
  src/char/int_guild.cpp
Labels: status:code-review

#4062 Added several warning messages
  src/common/mapindex.cpp
  src/map/atcommand.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/status.cpp
Labels: component:core, status:code-review

#4083 Adjusted pet walk speed
  conf/battle/pet.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/status.cpp
Labels: status:code-review

#3657 Cleaned up countitem-type script commands
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#4061 Implemented (the old) Nightmarish Jitterbug instance
  db/pre-re/skill_cast_db.txt
  db/pre-re/skill_db.txt
  db/pre-re/skill_unit_db.txt
  db/re/instance_db.txt
  db/re/mob_db.txt
  db/re/mob_skill_db.txt
  db/re/skill_cast_db.txt
  db/re/skill_db.txt
  db/re/skill_unit_db.txt
  npc/re/instances/NightmarishJitterbug.txt
  npc/re/scripts_athena.conf
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:script, mode:renewal, status:code-review

#4107 Corrected a compile error
  src/map/battle.cpp
Labels: status:code-review

#4065 Fixed AG_BATTLE and AG_TAMING achievements
  src/map/achievement.cpp
  src/map/achievement.hpp
  src/map/intif.cpp
Labels: status:code-review

#4099 Reduced MAX_MAP_SERVERS and MAX_SERVERS size
  src/char/char.hpp
  src/login/login.hpp
Labels: status:code-review

#4103 Corrected script command logmes
  src/map/map.cpp
Labels: status:code-review

#4090 Cleaned up instance script commands
  doc/script_commands.txt
  npc/re/instances/HorrorToyFactory.txt
  npc/re/instances/MorseCave.txt
  src/map/script.cpp
Labels: status:code-review

#4047 Added an item group for Token of Siegfried
  db/pre-re/item_misc.txt
  db/re/item_misc.txt
  src/map/clif.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: status:code-review

#3661 Corrected Enchant Arms status icon
  doc/status_change.txt
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4121 Corrected Cross Slash
  src/map/battle.cpp
Labels: status:code-review

#4104 unitwarp npc - issue #4087
  src/map/npc.cpp
  src/map/unit.cpp
Labels: status:code-review

#4129 Fixed a SQL item database error
  db/re/item_db.txt
Labels: status:code-review
