Repository rathena/rathena, pull requests merged in 2020-11, with the labels that each got.

#5486 Item DB update (part of ep17.2)
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, status:code-review

#5366 Fix other character disguises on @refresh
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5519 Fixed a useless warning for PACKETVER < 20141016
  src/char/char.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5520 Resolves null YAML node checks
  src/common/database.cpp
  src/map/itemdb.cpp
Labels: status:code-review

#5518 Fixed item restrictions for "All"
  src/map/itemdb.cpp
  src/map/map.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#5522 Fixed max Doram ASPD
  conf/battle/player.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, type:bug

#5445 Initial support for enchantgrade
  sql-files/main.sql
  sql-files/upgrades/upgrade_20201105.sql
  src/char/char.cpp
  src/char/int_auction.cpp
  src/char/int_mail.cpp
  src/common/mmo.hpp
  src/map/buyingstore.cpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
  src/map/searchstore.cpp
  src/map/searchstore.hpp
  src/map/storage.cpp
  src/map/vending.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5343 Fixes Venom Pressure combo with Poisoning Weapon
  src/map/skill.cpp
Labels: status:code-review

#5521 Fixed invisible items after VIP expiration
  src/map/clif.cpp
  src/map/storage.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5527 Adds SQL to TXT dump
  sql-files/README.md
  sql-files/tools/item_db2_re_to_txt.sql
  sql-files/tools/item_db2_to_txt.sql
  sql-files/tools/item_db_re_to_txt.sql
  sql-files/tools/item_db_to_txt.sql
Labels: status:code-review

#5494 Converts the random option databases to YAML
  db/const.txt
  db/import-tmpl/item_randomopt_db.txt
  db/import-tmpl/item_randomopt_db.yml
  db/import-tmpl/item_randomopt_group.txt
  db/import-tmpl/item_randomopt_group.yml
  db/item_randomopt_db.yml
  db/item_randomopt_group.yml
  db/pre-re/item_randomopt_db.txt
  db/pre-re/item_randomopt_group.txt
  db/re/item_randomopt_db.txt
  db/re/item_randomopt_db.yml
  db/re/item_randomopt_group.txt
  db/re/item_randomopt_group.yml
  db/re/mob_drop.txt
  doc/yaml/db/item_randomopt_db.yml
  doc/yaml/db/item_randomopt_group.yml
  src/common/utilities.hpp
  src/map/atcommand.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/status.cpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#5532 Corrected some mistakes in item_combo_db.txt
  db/re/item_combo_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#5530 Item_db update (cards)
  db/re/item_combo_db.txt
  db/re/item_db_etc.yml
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review

#4905 Fixes skill elemental damage
  src/map/battle.cpp
Labels: status:code-review

#5136 Adjusts behavior of skill fixed cast time
  conf/battle/skill.conf
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/skill.cpp
Labels: status:code-review

#5533 Added shadow equipment in item db
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5539 Corrected some typo in shadow equipments
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5538 Item_db update (armor)
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5531 Item_db update (weapon)
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5544 Corrected a combo in item_combo_db
  db/re/item_combo_db.txt
Labels: component:database, mode:renewal, status:code-review

#5545 Woe controller pre-renewal
  npc/custom/woe_controller.txt
Labels: status:code-review

#5550 Small correction for checkre script command
  doc/script_commands.txt
  npc/jobs/2-1/hunter.txt
  npc/kafras/functions_kafras.txt
Labels: mode:renewal, status:code-review

#5558 Fixed headgears for autotraders
  src/map/intif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5552 Fixed missing dummy item after reloading
  src/common/database.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/tool/csv2yaml.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5557 Fixed some potential csv2yaml crashes
  src/tool/csv2yaml.cpp
Labels: component:tool, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5553 Fixed a bug in reloadnpcfile
  src/map/atcommand.cpp
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5535 Suggestion: ALL_THIRD, Both_Accessory, Both_Hand in item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/item_db.txt
  src/map/itemdb.hpp
  src/map/script_constants.hpp
  src/tool/csv2yaml.cpp
  src/tool/yaml2sql.cpp
Labels: status:code-review

#5565 Added monsters Furious Wickebine Tres and Elusive Eremes in DB
  db/re/mob_db.txt
  db/re/mob_skill_db.txt
  npc/re/mobs/championmobs.txt
Labels: status:code-review

#5562 Converted penalty db to YAML
  db/import-tmpl/level_penalty.txt
  db/import-tmpl/level_penalty.yml
  db/level_penalty.yml
  db/re/level_penalty.txt
  db/re/level_penalty.yml
  doc/yaml/db/level_penalty.yml
  src/map/atcommand.cpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/tool/csv2yaml.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#5566 Cleanup of rAthena templates and docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  doc/logo.png
Labels: status:code-review

#5563 Update droplight effects
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, type:bug

#5560 Cleanup/skill db fixes
  db/import-tmpl/skill_db.yml
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  db/skill_db.yml
  doc/yaml/db/skill_db.yml
  src/tool/csv2yaml.cpp
Labels: status:code-review

#5559 Cleanup of MVP mode checking
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/mob.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5554 Fixed an issue with fake NPCs
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5574 Min/max issue
  doc/script_commands.txt
  npc/test/ci/5573.txt
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5424 Fixes Advent of Star Emperor behavior
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#5192 Implements new guild skills
  conf/battle/guild.conf
  db/pre-re/guild_skill_tree.yml
  db/pre-re/skill_db.yml
  db/re/guild_skill_tree.yml
  db/re/mob_db.txt
  db/re/skill_db.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/guild.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#5583 Fix Friendlist disappear in 2020-09-02ragexeRE or above
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5578 Unlock target when setunitdata TARGETID 0
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5422 Fixes a potential crash when adding new maps
  src/map/map.cpp
Labels: status:code-review
