Repository rathena/rathena, pull requests merged in 2020-08, with the labels that each got.

#5282 Cancel skill usage keeping on failure
  src/map/skill.cpp
Labels: status:code-review

#5281 Adjusts homunculi hunger delay rate when starving
  conf/battle/homunc.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/homunculus.cpp
Labels: status:code-review

#5260 Follow up to 2e88b27
  src/map/npc.cpp
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5261 Fixes refine attack bonus
  src/map/status.cpp
Labels: status:code-review

#5270 Adjusts npcskilleffect and skilleffect
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#5274 Implements NPC_HELLBURNING
  db/re/mob_skill_db.txt
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#5240 Updates map_cache for Izlude Academy
  db/re/map_cache.dat
Labels: status:code-review

#5238 Fixes RODEX retrieve all button
  conf/char_athena.conf
  src/char/char.cpp
  src/char/char.hpp
  src/char/int_mail.cpp
  src/map/clif.cpp
Labels: status:code-review

#5287 Fixes sphere requirement for Knuckle Arrow
  db/re/skill_db.yml
Labels: status:code-review

#5293 Fixed Estun not damaging all monsters
  src/map/battle.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5264 Fixed mobskill_event not triggering with plant mode monsters
  src/map/battle.cpp
Labels: status:code-review

#5017 Adjusts NPC_EARTHQUAKE behavior
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: status:code-review

#5283 Fixed memory leak from pet imports
  src/map/pet.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5289 Adjusts disabled NPC with waiting rooms
  npc/jobs/2-1/assassin.txt
  npc/jobs/2-1/knight.txt
  npc/jobs/2-2/crusader.txt
  npc/jobs/2-2/sage.txt
  npc/re/jobs/3-1/warlock.txt
Labels: status:code-review

#5284 Added additional idle options
  conf/battle/player.conf
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/pc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4897 Job Improvement Project - Warlock
  db/re/item_db.txt
  db/re/item_flag.txt
  db/re/skill_db.yml
  db/re/skill_tree.txt
  db/re/spellbook_db.yml
  sql-files/upgrades/upgrade_20200505.sql
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/itemdb.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#5304 Enables new Special Pharmacy Potions
  db/re/item_db.txt
  db/re/produce_db.txt
Labels: status:code-review

#5307 Fix Arrow Crafting db with high item ids
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5302 Fixed logging out on newer clients
  conf/battle/client.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5310 Fixes renewal Brandish Spear range
  src/map/battle.cpp
Labels: status:code-review

#5313 Fixes Brandish Spear splash area
  db/re/skill_db.yml
Labels: status:code-review

#5308 Counteragent Mixture - Name Typo
  npc/quests/counteragent_mixture.txt
  npc/re/merchants/ticket_refiner.txt
Labels: component:script, mode:prerenewal, mode:renewal, type:enhancement

#5315 Fixes item production with high item IDs
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_grm.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/char/int_storage.cpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#5316 Adjust the Hell Inferno dark element check
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#5297 Episode 15 update
  db/re/item_db.txt
  db/re/mob_db.txt
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/kafras/cool_event_corp.txt
  npc/re/quests/quests_15_1.txt
  npc/re/quests/quests_15_2.txt
  npc/re/scripts_athena.conf
  npc/re/warps/other/un_myst.txt
  npc/re/warps/other/verus.txt
  sql-files/upgrades/upgrade_20200729.sql
Labels: mode:renewal, status:code-review

#5319 Removed skilleffect/npcskilleffect cap
  src/map/script.cpp
Labels: status:code-review

#5314 Adjusts map_foreachindir to include caster's cell
  conf/battle/skill.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/map.cpp
Labels: status:code-review

#5339 Resolves Warlock Spell Books being consumed
  db/re/item_flag.txt
Labels: status:code-review

#5341 Fixed skill usage keeping timer being set when skill id is 0
  src/map/skill.cpp
Labels: status:code-review

#5255 Fixed battlegrounds not resetting on reloadscript
  npc/battleground/kvm/kvm01.txt
  npc/battleground/kvm/kvm02.txt
  npc/battleground/kvm/kvm03.txt
  src/map/atcommand.cpp
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5335 Corrects some details about new Alchemist Potions
  db/re/produce_db.txt
  src/map/battle.cpp
Labels: status:code-review

#5355 Fixes timer deletion errors from skill_keep_using
  src/map/skill.cpp
Labels: status:code-review

#4840 Charleston Crisis instance (old version)
  db/re/instance_db.yml
  db/re/mob_db.txt
  db/re/mob_skill_db.txt
  npc/re/instances/CharlestonCrisis.txt
  npc/re/merchants/enchan_verus.txt
  npc/re/scripts_athena.conf
  sql-files/mob_db_re.sql
  sql-files/mob_skill_db_re.sql
Labels: mode:renewal, status:code-review

#5359 Added/improved SG's maps and monsters reset script and GM commands
  conf/msg_conf/map_msg.conf
  doc/atcommands.txt
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/pc.cpp
  src/map/script.cpp
Labels: status:code-review, type:enhancement

#4592 Excellion trader and enchant npcs
  db/re/item_db.txt
  db/re/quest_db.yml
  npc/re/merchants/enchan_verus.txt
  sql-files/item_db_re.sql
Labels: component:script, mode:renewal, status:code-review

#5344 Updates the Magic Book NPC
  npc/re/quests/magic_books.txt
Labels: status:code-review

#5360 Adds Advanced Potion Merchant NPC
  npc/re/merchants/shops.txt
Labels: status:code-review

#3990 Terra Gloria (episode 16.2) - walkthrough conversion
  db/re/instance_db.yml
  db/re/item_db.txt
  db/re/mob_db.txt
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/pre-re/scripts_warps.conf
  npc/pre-re/warps/cities/einbroch.txt
  npc/re/instances/HeartHunterWarBase.txt
  npc/re/instances/WernerLaboratoryCentralRoom.txt
  npc/re/mobs/dungeons/slabw01.txt
  npc/re/other/global_npcs.txt
  npc/re/quests/quests_16_2.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/cities/einbech.txt
  npc/re/warps/cities/einbroch.txt
  npc/re/warps/dungeons/slabw01.txt
  npc/warps/cities/einbroch.txt
  sql-files/item_db_re.sql
  sql-files/mob_db_re.sql
  sql-files/mob_skill_db_re.sql
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:script, status:code-review, status:need more info

#5361 Fixed Magic Bible Vol 1
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: status:code-review
