Repository rathena/rathena, pull requests merged in 2020-12, with the labels that each got.

#5591 Corrected the jobs for item ID 16054
  db/re/item_db_equip.yml
Labels: status:code-review

#5592 Correction for item IDs 16065 and 16089
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#5601 Adds item bonus bReduceDamageReturn
  doc/item_bonus.txt
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
Labels: status:code-review

#5610 Implemented items ID 310178/310179
  db/re/item_db_etc.yml
Labels: component:database, status:code-review

#5561 Removes a useless nullification loop
  src/map/pc.cpp
Labels: status:code-review

#5631 Fixes compile errors on GCC 10.2
  src/map/instance.cpp
  src/map/skill.cpp
Labels: status:code-review

#5640 Fixed an issue with status point reset
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5641 Converted a few more packets to structs
  src/map/clif.cpp
  src/map/packets.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5635 Added missing maps to mapcache
  conf/maps_athena.conf
  db/map_index.txt
  db/re/map_cache.dat
Labels: status:code-review

#5633 Fixes renewal weapon attack display
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#5645 Corrected script for some item
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review, type:bug
