Repository rathena/rathena, pull requests merged in 2020-02, with the labels that each got.

#4585 Cleaned up CSV2YAML skill database label
  doc/yaml/db/skill_db.yml
  src/tool/csv2yaml.cpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, status:code-review

#4581 Fixed wrong equip descriptions in refiners
  npc/re/merchants/advanced_refiner.txt
  npc/re/merchants/blessed_refiner.txt
  npc/re/merchants/hd_refiner.txt
  npc/re/merchants/refine.txt
Labels: component:script, mode:renewal, status:code-review, type:bug

#4586 Fixed a compiler warning in script.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4565 Fixed some database redundencies
  sql-files/main.sql
  sql-files/upgrades/upgrade_20200125.sql
  src/char/char.cpp
  src/char/int_guild.cpp
  src/common/mmo.hpp
  src/map/guild.cpp
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4594 Removed leftover Improvised Song database
  db/import-tmpl/skill_improvise_db.txt
Labels: status:code-review

#4595 Added SA_TAMINGMONSTER to pre-renewal
  db/abra_db.yml
  db/pre-re/abra_db.yml
Labels: status:code-review

#4560 Pushcart Decoration npc
  db/re/item_db.txt
  npc/re/quests/skills/merchant_skills.txt
  npc/re/scripts_jobs.conf
Labels: component:script, mode:renewal, status:code-review

#4593 Corrected script of Velum_Flail
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#4591 Last room instance update
  npc/re/instances/LastRoom.txt
Labels: component:script, mode:renewal, status:code-review

#4601 Fixed a compiler warning in pc.cpp
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#4602 Fixed view id of 19381
  db/re/item_db.txt
Labels: component:database, mode:renewal, type:bug

#4488 Fixed Hocus and Improvised Song ignoring mapflags
  src/map/skill.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4603 Renamed upgrade 20200125.sql to correct date
  sql-files/upgrades/upgrade_20200204.sql
Labels: component:database, mode:prerenewal, mode:renewal, type:maintenance

#4454 Fixed some skill crit bonuses
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#4606 Added an option to block discount in shop
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#3659 Updated 3rd class from RO 16th Anniversary Patch
  db/pre-re/skill_db.yml
  db/pre-re/skill_tree.txt
  db/re/skill_db.yml
  db/re/skill_tree.txt
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#4610 Corrects Soul Staff and Wizardry Staff view ID
  db/pre-re/item_db.txt
Labels: status:code-review

#4608 Removed SQL Upgrade files older than 2 years
  sql-files/upgrades/upgrade_20160106.sql
  sql-files/upgrades/upgrade_20160112.sql
  sql-files/upgrades/upgrade_20160614.sql
  sql-files/upgrades/upgrade_20160814.sql
  sql-files/upgrades/upgrade_20160814_log.sql
  sql-files/upgrades/upgrade_20161013.sql
  sql-files/upgrades/upgrade_20161116.sql
  sql-files/upgrades/upgrade_20170113_log.sql
  sql-files/upgrades/upgrade_20170215.sql
  sql-files/upgrades/upgrade_20170218.sql
  sql-files/upgrades/upgrade_20170218_log.sql
  sql-files/upgrades/upgrade_20170327.sql
  sql-files/upgrades/upgrade_20170417.sql
  sql-files/upgrades/upgrade_20170417_logs.sql
  sql-files/upgrades/upgrade_20170509.sql
  sql-files/upgrades/upgrade_20170620.sql
  sql-files/upgrades/upgrade_20170702.sql
  sql-files/upgrades/upgrade_20170727.sql
  sql-files/upgrades/upgrade_20170806.sql
  sql-files/upgrades/upgrade_20170830.sql
  sql-files/upgrades/upgrade_20171001.sql
  sql-files/upgrades/upgrade_20171001_logs.sql
  sql-files/upgrades/upgrade_20171019.sql
  sql-files/upgrades/upgrade_20180404.sql
  sql-files/upgrades/upgrade_20180623.sql
  sql-files/upgrades/upgrade_20180705_logs.sql
  sql-files/upgrades/upgrade_20180729_logs.sql
  sql-files/upgrades/upgrade_20180830.sql
  sql-files/upgrades/upgrade_20181010.sql
  sql-files/upgrades/upgrade_20181220.sql
  sql-files/upgrades/upgrade_20181224.sql
Labels: component:database, mode:prerenewal, mode:renewal, type:maintenance

#4570 Fixed SA_FREECAST aspd calculation
  src/map/status.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4387 3rd_trader.txt update according to KRO Sakray
  npc/re/merchants/3rd_trader.txt
Labels: component:script, mode:renewal, type:bug

#4613 Correcting import due to compiler warning
  src/common/cli.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#4626 Fixed some compiler warnings on prere
  src/map/battle.cpp
Labels: component:core, mode:prerenewal, status:code-review, type:bug

#4624 Resolves Tetra Vortex AoE
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: status:code-review

#4633 Quest data should be cleared on char deletion
  src/char/char.cpp
Labels: status:code-review

#4625 Fixed #4616
  db/re/item_db.txt
  sql-files/item_db_re.sql
  src/map/itemdb.cpp
  src/map/itemdb.hpp
Labels: component:core, mode:renewal, type:bug

#4632 Corrects Feint Bomb knockback
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: status:code-review

#4627 Added support for RSW 2.2
  src/common/grfio.cpp
  src/common/grfio.hpp
  src/map/map.cpp
  src/tool/mapcache.cpp
Labels: component:core, component:tool, mode:renewal, status:code-review, type:bug

#3995 Implemented the Battleground Queue System
  conf/battle/feature.conf
  conf/msg_conf/map_msg.conf
  db/battleground_db.yml
  db/import-tmpl/battleground_db.yml
  doc/script_commands.txt
  npc/battleground/flavius/flavius01.txt
  npc/battleground/flavius/flavius02.txt
  npc/battleground/flavius/flavius_enter.txt
  npc/battleground/kvm/kvm01.txt
  npc/battleground/kvm/kvm02.txt
  npc/battleground/kvm/kvm03.txt
  npc/battleground/kvm/kvm_enter.txt
  npc/battleground/kvm/kvm_item_pay.txt
  npc/battleground/tierra/tierra01.txt
  npc/battleground/tierra/tierra02.txt
  npc/battleground/tierra/tierra_enter.txt
  npc/custom/battleground/unofficial/bg_common.txt
  npc/custom/battleground/unofficial/bg_flavius_01.txt
  npc/custom/battleground/unofficial/bg_flavius_02.txt
  npc/custom/battleground/unofficial/bg_kvm01.txt
  npc/custom/battleground/unofficial/bg_kvm02.txt
  npc/custom/battleground/unofficial/bg_kvm03.txt
  npc/custom/battleground/unofficial/bg_tierra_01.txt
  npc/custom/battleground/unofficial/bg_tierra_02.txt
  src/common/utilities.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/battleground.cpp
  src/map/battleground.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  tools/ci/npc.bat
  tools/ci/npc.sh
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4651 Resolves an issue with mob avail options
  src/map/mob.cpp
Labels: status:code-review

#4653 Corrects SQL import
  sql-files/main.sql
Labels: status:code-review

#4652 Resolves compile warnings
  src/tool/csv2yaml.cpp
  src/tool/mapcache.cpp
Labels: status:code-review

#4634 Removes leftover Magic Mushroom database
  db/import-tmpl/magicmushroom_db.txt
Labels: status:code-review

#4609 Updated Central Laboratory instance
  npc/other/gm_npcs.txt
  npc/re/instances/CentralLaboratory.txt
Labels: component:script, mode:renewal, status:code-review

#4648 Battleground Queue fixes
  doc/script_commands.txt
  npc/battleground/flavius/flavius01.txt
  npc/battleground/flavius/flavius02.txt
  npc/battleground/kvm/kvm02.txt
  npc/battleground/kvm/kvm03.txt
  npc/battleground/tierra/tierra02.txt
  src/map/battleground.cpp
  src/map/battleground.hpp
  src/map/clif.cpp
Labels: status:code-review

#4657 Adds reload attendance database atcommand
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  db/attendance.yml
  db/import-tmpl/attendance.yml
  db/pre-re/attendance.yml
  db/re/attendance.yml
  src/map/atcommand.cpp
  src/map/pc.cpp
  src/map/pc.hpp
Labels: status:code-review

#4658 Cleans up Summoner dual-cast attacks
  src/map/skill.cpp
Labels: status:code-review

#4637 Fixed a few bugs in custom WoE controller
  npc/custom/woe_controller.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review, type:bug
