Repository rathena/rathena, pull requests merged in 2020-05, with the labels that each got.

#4885 Fixes an issue with status timers being destroyed
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4867 Heat Barrel should be giving fixed ASPD
  src/map/status.cpp
Labels: status:code-review

#4874 Corrects Feint Bomb not hiding the caster
  src/map/skill.cpp
Labels: status:code-review

#4892 More fixes on duplicate itemshops and pointshops
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4425 Job Improvement Project - Kagerou & Oboro
  db/re/skill_db.yml
  db/re/skill_tree.txt
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4900 Adjusts Adoramus cooldown
  db/re/skill_db.yml
Labels: status:code-review

#4429 Job Improvement Project - Super Novice
  db/job_db2.txt
  db/re/job_db1.txt
  db/re/skill_db.yml
  db/re/skill_tree.txt
  sql-files/upgrades/upgrade_20200506.sql
  src/map/battle.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#4888 Fixed Piano Key Quest hidden warp position in pre-re
  npc/pre-re/quests/quests_niflheim.txt
  npc/pre-re/scripts_athena.conf
  npc/quests/quests_niflheim.txt
  npc/re/quests/quests_niflheim.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:prerenewal, status:code-review, type:bug

#4924 Fixed Back Slide animation on pre-re
  src/map/skill.cpp
Labels: component:skill, mode:prerenewal, status:code-review, type:bug

#4910 npctalk script command accept <color>
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#4919 Adds skill placeholder for Super Novice Expanded
  db/pre-re/skill_db.yml
Labels: status:code-review

#4813 Few Genetic skill fixes
  db/pre-re/skill_db.yml
  db/re/item_db.txt
  db/re/produce_db.txt
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/pc.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: status:code-review

#4945 Fixes instance map names over 1000
  src/map/instance.cpp
  src/map/map.cpp
Labels: status:code-review

#4967 Adjusts area size config back to 14 cells
  conf/battle/client.conf
  db/re/skill_db.yml
Labels: status:code-review

#4701 Job Improvement Project - Minstrel/Wanderer
  db/import-tmpl/improvise_db.yml
  db/improvise_db.yml
  db/pre-re/skill_db.yml
  db/pre-re/skill_tree.txt
  db/re/improvise_db.yml
  db/re/skill_db.yml
  db/re/skill_nocast_db.txt
  db/re/skill_tree.txt
  doc/skill_db.txt
  doc/yaml/db/improvise_db.yml
  sql-files/upgrades/upgrade_2020xxxx.sql
  src/map/battle.cpp
  src/map/map-server.vcxproj
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4705 Job Improvement Project - Guillotine Cross
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4970 Fixed getcharid error in Continental Guard quest
  npc/quests/quests_morocc.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4709 Job Improvement Project - Rune Knight (Part 2)
  db/re/item_db.txt
  db/re/item_delay.txt
  db/re/item_stack.txt
  db/re/skill_db.yml
  doc/item_bonus.txt
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#4920 Fixes Adoramus' interaction with Land Protector
  src/map/skill.cpp
Labels: status:code-review

#4902 Skill Database cleanups
  conf/battle/skill.conf
  doc/atcommands.txt
  doc/item_bonus.txt
  doc/mapflags.txt
  doc/script_commands.txt
  src/map/skill.cpp
Labels: status:code-review

#4921 Resolves Autospell displaying errors to console
  src/map/skill.cpp
Labels: status:code-review

#4958 Remove Summoner Hide when changing maps
  src/map/pc.cpp
Labels: status:code-review

#4968 Fixes Blood Sucker not being able to be recast
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4979 Removes nullpo checks from CSV2YAML
  src/tool/csv2yaml.cpp
Labels: status:code-review

#4982 Corrects NPC_DARKBREATH behavior
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#4989 Fixes a potential crash with atcommand time
  src/map/atcommand.cpp
Labels: status:code-review

#3749 Changed item with expire_time sell value
  conf/battle/items.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/npc.cpp
Labels: status:code-review

#4985 Added enchant npc for temporal shoes slotted and ogh card exchange
  npc/re/merchants/OldGlastHeim_merchants.txt
Labels: component:script, status:code-review

#4725 Resolves some Battleground issues
  conf/battle/battleground.conf
  conf/msg_conf/map_msg.conf
  db/battleground_db.yml
  db/import-tmpl/battleground_db.yml
  doc/script_commands.txt
  npc/battleground/flavius/flavius01.txt
  npc/battleground/flavius/flavius02.txt
  npc/battleground/kvm/kvm01.txt
  npc/battleground/kvm/kvm02.txt
  npc/battleground/kvm/kvm03.txt
  npc/battleground/tierra/tierra01.txt
  npc/battleground/tierra/tierra02.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/battleground.cpp
  src/map/battleground.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: status:code-review

#4995 Adjusts a few checks for item tradability
  doc/script_commands.txt
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: status:code-review

#5012 Fixes Decorate Cart requirement
  db/re/skill_db.yml
Labels: status:code-review

#5000 Fixes looter mobs getting stuck
  src/map/mob.cpp
Labels: status:code-review

#5009 Corrected OnTouch(_) behaviour
  src/map/npc.cpp
Labels: status:code-review

#5013 Adjusts Reverberation behavior
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: status:code-review

#5010 Fixes Mercenary kill counter
  src/map/mob.cpp
Labels: status:code-review

#5029 Fix missing pet egg checks
  src/map/clif.cpp
  src/map/skill.cpp
  src/map/storage.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug
