Repository rathena/rathena, pull requests merged in 2020-06, with the labels that each got.

#5033 Added a missing percentheal
  npc/re/quests/quests_rockridge.txt
Labels: component:script, mode:renewal, status:code-review, type:bug

#4944 Initial support for newer packet versions
  conf/battle/client.conf
  sql-files/main.sql
  sql-files/upgrades/upgrade_20200603.sql
  src/char/char.cpp
  src/common/mmo.hpp
  src/common/socket.cpp
  src/common/socket.hpp
  src/config/packets.hpp
  src/login/loginclif.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/buyingstore.cpp
  src/map/buyingstore.hpp
  src/map/cashshop.cpp
  src/map/cashshop.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/clif_shuffle.hpp
  src/map/map-server.vcxproj
  src/map/map-server.vcxproj.filters
  src/map/map.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/searchstore.cpp
  src/map/searchstore.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/storage.cpp
  src/map/vending.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5006 Removed account gender
  sql-files/main.sql
  sql-files/upgrades/upgrade_20200604.sql
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_mapif.cpp
  src/common/mmo.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#4942 Add Card Drops for Devil Tower Instance
  db/re/mob_db.txt
Labels: component:database, mode:renewal, type:bug

#4996 Fix issue with mob not spawning at selected option
  npc/re/instances/NightmarishJitterbug.txt
Labels: component:script, mode:renewal, type:bug

#5041 Added support for skill scale display
  conf/battle/client.conf
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/script_constants.hpp
  src/map/skill.hpp
  src/map/unit.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5051 Deprecates support for old compilers
  appveyor.yml
  src/common/core.cpp
  src/config/core.hpp
  tools/serv.bat
Labels: component:core, mode:prerenewal, mode:renewal, type:maintenance

#5055 Fixes Bard and Dancer Soul Link bonus
  src/map/pc.cpp
Labels: status:code-review

#4999 Clean up Summoner Power skill checks
  src/map/battle.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#4839 Costume exchange NPC in malangdo
  db/re/item_combo_db.txt
  db/re/item_db.txt
  db/re/item_misc.txt
  npc/re/merchants/malangdo_costume.txt
  npc/re/scripts_athena.conf
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: mode:renewal, status:code-review

#5071 Correction for WOE Controller Reward issue
  npc/custom/woe_controller.txt
Labels: status:code-review

#4896 Add NPC for exchanging Cute Pet Tickets to eggs
  npc/re/merchants/pet_trader.txt
  npc/re/scripts_athena.conf
Labels: status:code-review

#5070 Cleaned up chlogif_parse functions
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/char/char_logif.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#5072 Fixed some invalid packet version checks
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#4966 Corrects Hell's Plant behavior
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/map.cpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
Labels: status:code-review

#4957 Cleans up Genetic creation skills
  src/map/skill.cpp
Labels: status:code-review

#5085 Removed iRO-specific bonus from Rideword_Hat (5208)
  db/re/item_db.txt
Labels: component:database, mode:renewal, status:code-review

#5014 Fixes Ensemble skills behavior
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#5027 Fixes Rune Mastery visual effects
  src/map/skill.cpp
Labels: status:code-review

#5021 Adds support for sharing battle-type Achievements
  conf/battle/monster.conf
  src/map/achievement.cpp
  src/map/achievement.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
Labels: status:code-review

#5102 Fixed sending of storages full of equip
  src/map/clif.cpp
  src/map/packets.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5082 Fixes Rolling Cutter counter not resetting
  src/map/skill.cpp
Labels: status:code-review

#5088 Fixes IM_CHAR instances to persist relog
  src/map/pc.cpp
Labels: status:code-review

#5095 Adds a config for slave teleporting to master
  conf/battle/monster.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
Labels: status:code-review

#5073 Adds support for instance destruction button
  db/import-tmpl/instance_db.yml
  db/instance_db.yml
  db/pre-re/instance_db.yml
  db/re/instance_db.yml
  doc/yaml/db/instance_db.yml
  src/common/mmo.hpp
  src/map/clan.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/npc.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.cpp
  src/map/pc.hpp
Labels: status:code-review

#5080 Adds script commands to count rental items
  doc/script_commands.txt
  npc/re/instances/MalangdoCulvert.txt
  npc/re/instances/OctopusCave.txt
  src/map/script.cpp
Labels: status:code-review

#5120 Lux Anima is no longer able to be canceled
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#5133 Fixed typo in GeffenMagicTournament.txt
  npc/custom/official/GeffenMagicTournament.txt
Labels: status:code-review

#5131 Fix for guild relay timer
  npc/quests/guildrelay.txt
  sql-files/upgrades/upgrade_20200622.sql
Labels: status:code-review

#5135 Corrected 'Healer Haru' npc
  npc/re/custom/lasagna/lasagna_npcs.txt
Labels: status:code-review

#5129 Fixes NC_REPAIR and NC_SHAPESHIFT requirements
  src/map/skill.cpp
Labels: status:code-review

#5139 Fixed lucky roulette updating
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5140 Sarah and fenrir instance hotfix
  db/re/mob_db.txt
  npc/re/instances/SarahAndFenrir.txt
Labels: mode:renewal, status:code-review

#5093 Web token feature
  conf/login_athena.conf
  sql-files/main.sql
  sql-files/upgrades/upgrade_20200625.sql
  src/char/char.cpp
  src/common/sql.cpp
  src/common/sql.hpp
  src/login/account.cpp
  src/login/account.hpp
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginclif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5138 Fixed an issue with guild storage log
  src/map/clif.cpp
  src/map/packets.hpp
  src/map/storage.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5145 Fixed accessory-card insertion
  src/map/clif.cpp
  src/map/pc.cpp
Labels: status:code-review

#5132 Added the race RC_PLAYER_DORAM
  conf/battle/player.conf
  db/import-tmpl/item_db.txt
  db/pre-re/item_combo_db.txt
  db/pre-re/item_db.txt
  db/pre-re/pet_db.yml
  db/re/item_combo_db.txt
  db/re/item_db.txt
  db/re/item_randomopt_db.txt
  db/re/pet_db.yml
  doc/item_bonus.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/map.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#5134 OnTouch support when npc is walking
  src/map/clif.cpp
  src/map/map.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#5150 Fixed slave monsters not teleporting with their master
  src/map/unit.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5117 Fixes a crash non-player objects and timed skills
  src/map/skill.cpp
Labels: status:code-review

#5118 Improvements to skill_detonator
  src/map/skill.cpp
Labels: status:code-review

#5123 Corrects Power Swing and Axe Boomerang behavior
  src/map/skill.cpp
Labels: status:code-review

#5143 Corrects Fire Dance ammo consumption
  db/re/skill_db.yml
Labels: status:code-review

#5148 Fixes Flame Launcher burning duration
  src/map/skill.cpp
Labels: status:code-review

#5142 Soul Reaper souls now persist relog
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: status:code-review

#5144 Guild emblem implementation for late 2019 clients or later
  src/char/int_guild.cpp
  src/char/inter.cpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/packets_struct.hpp
Labels: status:code-review

#5160 Fixes MF_PVP_NIGHTMAREDROP not clearing on reload
  src/map/map.cpp
Labels: status:code-review

#5157 Added leader change during WoE restriction to @changegm command
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_spn.conf
  src/map/atcommand.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#3993 Random options update
  db/const.txt
  db/re/item_randomopt_db.txt
  doc/atcommands.txt
  doc/item_bonus.txt
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/status.cpp
Labels: component:core, component:database, mode:renewal, status:inprogress, type:enhancement
