Repository rathena/rathena, pull requests merged in 2020-07, with the labels that each got.

#5159 Added a config for triggering OnPCLogout events on autotrade
  conf/battle/misc.conf
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5167 Fixed a potential segfault in pc_insert_card
  src/map/pc.cpp
Labels: priority:high, status:code-review

#5040 Added and fixed some pet features
  sql-files/upgrades/upgrade_20200703.sql
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/pet.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5158 Adds several missing player session checks
  src/char/char.hpp
  src/char/char_clif.cpp
Labels: status:code-review

#5171 Adds support for object groups and titles
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/unit.hpp
Labels: status:code-review

#5182 Fixes party name display
  src/map/clif.cpp
Labels: status:code-review

#5193 Fixed several items
  db/pre-re/item_db.txt
  db/re/item_db.txt
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5175 Added some missing pet egg checks
  src/map/atcommand.cpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5198 Custom woe controller script update
  npc/custom/woe_controller.txt
Labels: status:code-review

#5205 Improved web authentication token generation
  src/login/account.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5206 Cancel skill usage keeping on death
  src/map/pc.cpp
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5202 Fixed a few possible crashes
  src/common/socket.cpp
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5200 countbound script command update
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#5191 Added support for race/size/element/min level/max level quest objectives
  db/import-tmpl/quest_db.yml
  db/pre-re/quest_db.yml
  db/quest_db.yml
  db/re/quest_db.yml
  doc/yaml/db/quest_db.yml
  npc/re/quests/quests_16_1.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/quest.cpp
  src/map/quest.hpp
Labels: status:code-review

#2381 Adjusted script command progressbar_npc behavior
  doc/script_commands.txt
  src/map/script.cpp
Labels: status:code-review

#5225 Fixes skill failure message that require items
  src/map/skill.cpp
Labels: status:code-review

#5213 Added the ability to make dynamic cash/item/point shops
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5231 Fixes Adoramus' area of effect
  db/re/skill_db.yml
Labels: status:code-review

#5237 Fixes weight of Throwing Weapons
  db/re/item_db.txt
Labels: status:code-review

#5254 Fixes Veteran Axe Hammerfall bonus
  db/re/item_db.txt
Labels: status:code-review

#5239 Fixed secure timeout triggering npc_scriptcont debug messages
  src/map/clif.cpp
  src/map/npc.cpp
  src/map/script.cpp
Labels: status:code-review

#5236 Fixes NPC_RUN behavior
  db/pre-re/mob_skill_db.txt
  db/re/mob_skill_db.txt
  src/map/mob.cpp
  src/map/skill.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: status:code-review

#4377 Adjust EXP storage to uint64
  db/import-tmpl/job_exp.txt
  db/re/job_exp.txt
  sql-files/main.sql
  sql-files/upgrades/upgrade_20200728.sql
  src/char/char.cpp
  src/char/int_guild.cpp
  src/common/mmo.hpp
  src/common/utilities.cpp
  src/common/utilities.hpp
  src/common/utils.cpp
  src/common/utils.hpp
  src/config/const.hpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5257 Fixes Wind Blade and Wind Charm bonus
  src/map/battle.cpp
Labels: status:code-review

#5253 Fixes Jewelry Ring item bonus
  db/re/item_db.txt
Labels: status:code-review

#5269 Removes waitingroom check for Maya Purple hackfix
  src/map/clif.cpp
Labels: status:code-review

#3129 Updates behavior of statuses that reduce damage
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/skill.cpp
Labels: status:code-review

#5259 Fixes attack cursor not showing up in duels
  src/map/clif.cpp
Labels: status:code-review
