Repository rathena/rathena, pull requests merged in 2021-05, with the labels that each got.

#5922 Resolves players warping to freed maps
  src/map/map.cpp
Labels: status:code-review

#5517 Job Improvement Bundle patch
  conf/battle/exp.conf
  db/re/item_db_usable.yml
  db/re/produce_db.txt
  db/re/skill_db.yml
  db/status_disabled.txt
  doc/script_commands.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/homunculus.cpp
  src/map/itemdb.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: status:code-review

#5935 Resolves a map crash from an equipment lookup
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5930 Updates Monster Transform statuses
  db/re/item_db_usable.yml
  src/map/itemdb.hpp
  src/map/pc.cpp
  src/map/status.cpp
Labels: status:code-review

#5942 Fixed int64 support for some exp commands
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5948 Fixes Increase Soil Card effects
  db/pre-re/item_db_etc.yml
  db/re/item_db_etc.yml
  sql-files/item_db_etc.sql
  sql-files/item_db_re_etc.sql
Labels: status:code-review

#5949 Remove delayed consumption when switching types
  src/map/itemdb.cpp
Labels: status:code-review

#5954 Additional item combo
  db/re/item_combo_db.txt
Labels: component:database, mode:renewal

#5959 Implemented status change for Packing_Envelope item
  db/re/item_db_usable.yml
  doc/status_change.txt
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: mode:renewal, status:code-review

#5967 Fix tools compilation
  src/tool/Makefile.in
Labels: component:tool, mode:prerenewal, mode:renewal, status:code-review

#5962 Fixes another possible crash with atcommand time
  src/map/atcommand.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5977 Fixes Gate of Hell SP damage bonus formula
  src/map/battle.cpp
Labels: component:skill, mode:renewal, priority:low, status:code-review, type:bug

#5972 Increased possible storage limit
  src/common/mmo.hpp
Labels: component:core, mode:prerenewal, mode:renewal, type:enhancement

#5975 Improved support for enchantgrade
  doc/script_commands.txt
  sql-files/logs.sql
  sql-files/upgrades/upgrade_20210530_logs.sql
  src/char/int_auction.cpp
  src/char/int_storage.cpp
  src/map/log.cpp
  src/map/npc.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug
