Repository rathena/rathena, pull requests merged in 2021-06, with the labels that each got.

#5976 mob_chat_db txt to yml
  db/import-tmpl/mob_chat_db.txt
  db/import-tmpl/mob_chat_db.yml
  db/mob_chat_db.txt
  db/mob_chat_db.yml
  db/re/mob_skill_db.txt
  doc/yaml/db/mob_chat_db.yml
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:core, component:database, mode:prerenewal, mode:renewal, status:code-review

#5988 Removed an extra variable assignment in quests_alberta.txt
  npc/quests/quests_alberta.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#5987 Added missing quests log in quests_rachel.txt
  npc/quests/quests_rachel.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#5986 Added missing item script for Holy_Egg_Hat (ID: 5551)
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal, status:code-review

#5985 Corrected the quests log in quests_amatsu.txt
  npc/quests/quests_amatsu.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#5984 whodrops should respect drop_rate0item
  src/map/atcommand.cpp
Labels: component:core, mode:renewal, priority:low

#5994 Fixes typos in archer_skills.txt
  npc/quests/skills/archer_skills.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#5996 Fixes a possible quest log mistake
  npc/quests/quests_rachel.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#6001 Commented wrong quests log in ayothaya quest
  npc/quests/quests_ayothaya.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#5993 Display more info on the location of the deprecated constant
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#6002 Converted exp_homun database to yaml
  db/exp_homun.yml
  db/import-tmpl/exp_homun.txt
  db/import-tmpl/exp_homun.yml
  db/pre-re/exp_homun.txt
  db/pre-re/exp_homun.yml
  db/re/exp_homun.txt
  db/re/exp_homun.yml
  doc/yaml/db/exp_homun.yml
  src/map/homunculus.cpp
  src/map/homunculus.hpp
  src/map/map-server.vcxproj
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:core, component:database, mode:prerenewal, mode:renewal, status:code-review

#6011 Converted mob_boss to yaml
  db/import-tmpl/mob_boss.txt
  db/import-tmpl/mob_branch.txt
  db/import-tmpl/mob_classchange.txt
  db/import-tmpl/mob_mission.txt
  db/import-tmpl/mob_poring.txt
  db/import-tmpl/mob_pouch.txt
  db/import-tmpl/mob_random_db.txt
  db/import-tmpl/mob_summon.yml
  db/mob_classchange.txt
  db/mob_mission.txt
  db/mob_pouch.txt
  db/mob_summon.yml
  db/pre-re/item_db_usable.yml
  db/pre-re/mob_boss.txt
  db/pre-re/mob_branch.txt
  db/pre-re/mob_poring.txt
  db/pre-re/mob_random_db.txt
  db/pre-re/mob_summon.yml
  db/re/item_db_usable.yml
  db/re/mob_boss.txt
  db/re/mob_branch.txt
  db/re/mob_poring.txt
  db/re/mob_random_db.txt
  db/re/mob_summon.yml
  doc/yaml/db/mob_summon.yml
  sql-files/item_db_re_usable.sql
  sql-files/item_db_usable.sql
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:core, component:database, mode:prerenewal, mode:renewal, status:code-review

#6003 Quest log corrections in quests_lighthalzen.txt (lhz_rekenber variable)
  npc/quests/quests_lighthalzen.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#6027 Fixed Assumptio increased healing
  doc/status_change.txt
  src/map/skill.cpp
Labels: component:core, mode:renewal, status:confirmed

#6042 Random options update
  db/re/item_randomopt_db.yml
  src/tool/csv2yaml.hpp
Labels: component:database, mode:renewal, type:bug

#6044 Fixes Spore Explosion item consumption
  src/map/skill.cpp
Labels: component:skill, mode:renewal, priority:low, status:code-review

#6043 Fixes Dark Claw boss damage
  src/map/battle.cpp
Labels: component:skill, mode:renewal, priority:low, status:code-review

#6029 Fixes Lightning Walk versus magic skills
  src/map/battle.cpp
Labels: status:code-review

#6039 Converted create_arrow_db.txt to YAML
  db/create_arrow_db.txt
  db/create_arrow_db.yml
  db/import-tmpl/create_arrow_db.txt
  db/import-tmpl/create_arrow_db.yml
  doc/yaml/db/create_arrow_db.yml
  src/map/clif.cpp
  src/map/map-server.vcxproj
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review

#6036 16.2 instance content related monster drop corrections.
  db/re/mob_db.yml
Labels: component:database, mode:renewal

#6064 Fixed an issue where the player get stuck in Rekenber Job quest
  npc/quests/quests_lighthalzen.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#6063 Added quest log for turtle island quest
  npc/quests/quests_alberta.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:code-review

#6065 Increased the lengh of name_english in item db SQL
  sql-files/item_db.sql
  sql-files/item_db2.sql
  sql-files/item_db2_re.sql
  sql-files/item_db_re.sql
  sql-files/upgrades/upgrade_20210629.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review
