Repository rathena/rathena, pull requests merged in 2021-11, with the labels that each got.

#6342 Fixed a mail weight check
  src/map/mail.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6341 Yet another autospell fix
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6352 Fixes AutoSpell target checks
  src/map/pc.cpp
Labels: status:code-review

#6351 NPC_COMET skill fix
  src/map/skill.cpp
Labels: component:core, mode:renewal, status:code-review

#6345 Corrected script for some item
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal, status:code-review

#6355 Fixes AutoSpellOnSkill targetting
  src/map/pc.cpp
Labels: status:code-review

#6356 Minor fixes and cleanups to the mob database
  db/import-tmpl/mob_db.yml
  db/mob_db.yml
  db/pre-re/mob_db.yml
  db/re/mob_db.yml
  doc/yaml/db/mob_db.yml
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#4759 Converts Job databases to YAML
  conf/atcommands.yml
  conf/battle/player.conf
  conf/msg_conf/map_msg.conf
  db/import-tmpl/job_basehpsp_db.txt
  db/import-tmpl/job_db1.txt
  db/import-tmpl/job_db2.txt
  db/import-tmpl/job_exp.txt
  db/import-tmpl/job_param_db.txt
  db/import-tmpl/job_stats.yml
  db/job_db2.txt
  db/job_stats.yml
  db/pre-re/job_basehpsp_db.txt
  db/pre-re/job_basepoints.yml
  db/pre-re/job_db1.txt
  db/pre-re/job_exp.txt
  db/pre-re/job_exp.yml
  db/pre-re/job_param_db.txt
  db/pre-re/job_stats.yml
  db/pre-re/skill_tree.txt
  db/re/job_basehpsp_db.txt
  db/re/job_basepoints.yml
  db/re/job_db1.txt
  db/re/job_exp.txt
  db/re/job_exp.yml
  db/re/job_param_db.txt
  db/re/job_stats.yml
  db/re/skill_tree.txt
  doc/atcommands.txt
  doc/yaml/db/job_basepoints.yml
  doc/yaml/db/job_exp.yml
  doc/yaml/db/job_stats.yml
  src/common/mmo.hpp
  src/config/core.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/map-server.vcxproj
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
  src/tool/yaml.hpp
Labels: status:code-review

#6208 Corrects costume exchanges for enchant box 4-21
  npc/re/merchants/malangdo_costume.txt
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#6359 Updated the docs with the new trait/talent stats
  doc/item_bonus.txt
Labels: component:documentation, mode:renewal, status:code-review

#6362 Updated Classes field in item_db.yml
  doc/item_db.txt
  sql-files/item_db2_re.sql
  sql-files/item_db_re.sql
  sql-files/upgrades/upgrade_20211118.sql
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
  src/tool/yaml2sql.cpp
Labels: component:database, component:core, mode:renewal, status:code-review

#6322 Added removespecialeffect/removespecialeffect2 script commands
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6357 Corrected script for some item
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#6282 Remove Maximum Power-Thrust buff on weapon unequip. Fixes #6277
  src/map/pc.cpp
Labels: status:code-review, hacktoberfest-accepted

#6343 Implemented some NPC skills
  db/pre-re/skill_db.yml
  db/re/mob_skill_db.txt
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, status:code-review

#6364 Corrected script for some item
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#6366 Updated the english item name of few items
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#6361 Fixes HP/SP table issues
  db/re/job_basepoints.yml
  db/re/job_stats.yml
  src/map/pc.cpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#6363 Implemented news cards and enchants
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review

#6102 Converted elemental_db to YAML
  db/elemental_db.txt
  db/elemental_db.yml
  db/elemental_skill_db.txt
  db/import-tmpl/elemental_db.txt
  db/import-tmpl/elemental_db.yml
  db/import-tmpl/elemental_skill_db.txt
  doc/yaml/db/elemental_db.yml
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/elemental.cpp
  src/map/elemental.hpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
  src/tool/yaml.hpp
  src/tool/yaml2sql.cpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review
