Repository rathena/rathena, pull requests merged in 2021-10, with the labels that each got.

#6279 Adds MF_NOCASHSHOP
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_grm.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/map/clif.cpp
  src/map/map.hpp
  src/map/script_constants.hpp
Labels: status:code-review

#6275 Fixes card bonus damage reaching the cap
  src/map/battle.cpp
Labels: status:code-review

#6283 Added a missing initialization
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6288 Adjusted the check of the jexp value in quests_mora.txt
  npc/re/quests/quests_mora.txt
Labels: component:script, mode:renewal, status:code-review

#6278 Adds drop effect to dropped random option items
  conf/battle/drops.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
Labels: component:core, mode:renewal, status:code-review, type:enhancement

#6287 Small correction in SealedShrine.txt
  npc/instances/SealedShrine.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#6290 Fixed SQL files
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review, type:bug

#6293 Caps the item and mob display name length
  db/re/item_db_equip.yml
  db/re/mob_db.yml
  sql-files/item_db_re_equip.sql
  sql-files/mob_db_re.sql
  src/map/battleground.cpp
  src/map/itemdb.cpp
  src/map/mob.cpp
Labels: component:database, component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review
