Repository rathena/rathena, pull requests merged in 2021-12, with the labels that each got.

#6379 Walking npc and official_cell_stack_limit
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6391 Updated F_IsCharm function
  npc/other/Global_Functions.txt
Labels: component:script, mode:renewal

#6381 Added etc item according to the items description up to nov 2021
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review

#6385 Fix missing condition for HW_GANBANTEIN
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6376 Fix yamlupgrade compiler error on linux
  src/tool/yamlupgrade.cpp
Labels: component:tool, mode:renewal, mode:prerenewal, type:bug

#6377 Cleanup as follow up to a205287
  doc/yaml/db/elemental_db.yml
  src/common/mmo.hpp
  src/map/elemental.cpp
  src/map/elemental.hpp
  src/map/mob.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6384 Fix SC_WINKCHARM behavior
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6373 Updated Malangdo Costume enchant services
  npc/re/merchants/malangdo_costume.txt
Labels: component:script, mode:renewal, type:bug

#6382 Fix SC_CHANGE not using max matk
  src/map/battle.cpp
Labels: component:core, mode:prerenewal, status:code-review, type:bug

#6101 Converted mercenary_db to YAML format
  db/import-tmpl/mercenary_db.txt
  db/import-tmpl/mercenary_db.yml
  db/import-tmpl/mercenary_skill_db.txt
  db/mercenary_db.txt
  db/mercenary_db.yml
  db/mercenary_skill_db.txt
  db/pre-re/mercenary_db.yml
  db/re/mercenary_db.yml
  db/re/mob_db.yml
  doc/yaml/db/mercenary_db.yml
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/map.hpp
  src/map/mercenary.cpp
  src/map/mercenary.hpp
  src/map/mob.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review

#6392 Added an exception for quest locations
  db/import-tmpl/quest_db.yml
  db/pre-re/quest_db.yml
  db/quest_db.yml
  db/re/quest_db.yml
  doc/yaml/db/quest_db.yml
  src/map/quest.cpp
Labels: component:database, component:core, mode:prerenewal, status:code-review

#6394 New card subtype
  db/import-tmpl/item_db.yml
  db/item_db.yml
  db/pre-re/item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/item_db.txt
  doc/script_commands.txt
  doc/yaml/db/item_db.yml
  npc/custom/card_seller.txt
  npc/events/RWC_2012.txt
  npc/re/merchants/card_separation.txt
  npc/re/merchants/enchan_ko.txt
  npc/re/merchants/enchan_mal.txt
  npc/re/merchants/enchan_mora.txt
  npc/re/merchants/enchan_rockridge.txt
  npc/re/merchants/enchan_upg.txt
  npc/re/merchants/enchan_verus.txt
  npc/re/quests/quests_malangdo.txt
  src/map/itemdb.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review

#6398 Fixed an issue with skill db conversion
  src/tool/csv2yaml.cpp
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6397 Adds missing baby classes to the HP/SP table
  db/re/job_basepoints.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#6399 Added shadow eq according to the items description up to nov 2021
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#6402 Fixed an issue with bAutoSpellWhenHit
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6407 Added latest constants and names
  db/re/mob_db.yml
  src/map/npc.hpp
  src/map/script_constants.hpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#6374 Implementation of setinstancevar
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, component:script, mode:renewal, mode:prerenewal, status:code-review

#6070 Converts the Skill Tree Tables file into YAML
  db/import-tmpl/skill_tree.txt
  db/import-tmpl/skill_tree.yml
  db/pre-re/skill_tree.txt
  db/pre-re/skill_tree.yml
  db/re/skill_tree.txt
  db/re/skill_tree.yml
  db/skill_tree.yml
  doc/yaml/db/skill_tree.yml
  src/map/atcommand.cpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review

#6401 Corrected script for some item
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#6409 Fixed some small mistakes with skill tree
  db/import-tmpl/skill_tree.yml
  db/pre-re/skill_tree.yml
  db/re/skill_tree.yml
  db/skill_tree.yml
  src/tool/csv2yaml.cpp
Labels: component:database, component:tool, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6412 Added basic support for 4th and 4th-ex class
  conf/atcommands.yml
  conf/msg_conf/char_msg.conf
  conf/msg_conf/map_msg.conf
  db/re/job_basepoints.yml
  db/re/job_exp.yml
  db/re/job_stats.yml
  src/char/inter.cpp
  src/common/mmo.hpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#6413 Add menu for adoption system
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6416 3rd job items usable by 4th job
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#6420 Updates getenchantgrade()
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:database, component:script, mode:renewal, status:code-review

#6419 New armors and weapons - up to nov 2021
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#6424 Fixed getexp calls in quests_mora.txt
  npc/re/quests/quests_mora.txt
Labels: component:script, mode:renewal, status:code-review, type:bug
