Repository rathena/rathena, pull requests merged in 2021-02, with the labels that each got.

#5081 Adds support for new Madogear appearance
  db/re/item_db_usable.yml
  doc/atcommands.txt
  doc/script_commands.txt
  sql-files/item_db_re_usable.sql
  sql-files/upgrades/upgrade_20210201.sql
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#5726 Fixed MO_CHAINCOMBO for Knuckle Weapons
  src/map/battle.cpp
Labels: component:core, mode:renewal, type:bug

#5500 Small corrections of some item data
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, status:code-review

#5267 Fixes Gate of Hell behavior
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.hpp
Labels: status:code-review

#5737 Small items corrections
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal

#5734 Item script correction
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/mob_race2_db.txt
  db/re/pet_db.yml
  db/re/skill_db.yml
  npc/re/merchants/nightmare_biolab.txt
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal

#5435 Converts the mob database to YAML
  .gitignore
  conf/msg_conf/map_msg.conf
  db/import-tmpl/mob_db.txt
  db/import-tmpl/mob_db.yml
  db/import-tmpl/mob_drop.txt
  db/import-tmpl/mob_race2_db.txt
  db/mob_db.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/mob_db.txt
  db/pre-re/mob_db.yml
  db/pre-re/mob_drop.txt
  db/pre-re/mob_race2_db.txt
  db/re/item_db_etc.yml
  db/re/mob_db.txt
  db/re/mob_db.yml
  db/re/mob_drop.txt
  db/re/mob_race2_db.txt
  doc/mob_db.txt
  doc/mob_db_mode_list.txt
  doc/yaml/db/mob_db.yml
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
  npc/custom/card_seller.txt
  sql-files/item_db_etc.sql
  sql-files/item_db_re_etc.sql
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  src/common/database.hpp
  src/common/mmo.hpp
  src/common/utilities.hpp
  src/map/achievement.cpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/map-server.vcxproj
  src/map/map.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/quest.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
  src/tool/csv2yaml.cpp
  src/tool/yaml2sql.cpp
Labels: component:core, component:database, hacktoberfest-accepted, status:code-review, type:enhancement

#5742 Atcommand Killmonster2 bypassed the "no drops"-flag. Do check without…
  src/map/atcommand.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5746 Fixes Poisoning Weapon icon display after relog
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#5747 Fixes script command getgroupitem
  src/map/itemdb.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5329 Fixed some changequest/setquest errors
  npc/quests/quests_13_1.txt
  npc/quests/quests_moscovia.txt
  npc/quests/quests_rachel.txt
Labels: component:script, mode:prerenewal, mode:renewal, status:inprogress, type:bug

#5748 Adds script command channel_getopt
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5749 Adds support for Green Aura MVP damage
  db/import-tmpl/mob_db.yml
  db/mob_db.yml
  db/pre-re/mob_db.yml
  db/re/mob_db.yml
  doc/mob_db.txt
  doc/yaml/db/mob_db.yml
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/tool/yaml2sql.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#5704 Clean up instance map name generation
  src/char/char_clif.cpp
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/map.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review

#5723 Fixes Alchemist Marine Sphere being triggered more than once
  db/pre-re/mob_skill_db.txt
  db/re/mob_skill_db.txt
  src/map/mob.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5717 Resolves Cross Impact and bNoKnockback
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5594 Implements autoloot support for Mercenary
  conf/battle/drops.conf
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: status:code-review

#5761 Removes Fatal Menace skill cast restrictions
  db/pre-re/skill_nocast_db.txt
  db/re/skill_nocast_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug
