Repository rathena/rathena, pull requests merged in 2021-03, with the labels that each got.

#4719 Updates 16.1 quests to official scripts
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/mob_db.yml
  db/re/quest_db.yml
  npc/re/instances/RitualOfBlessing.txt
  npc/re/instances/RoomOfConsciousness.txt
  npc/re/mobs/prt_cas.txt
  npc/re/quests/quests_16_1.txt
  npc/re/quests/quests_16_2.txt
  npc/re/warps/cities/prontera.txt
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  sql-files/mob_db_re.sql
  sql-files/upgrades/upgrade_20210308.sql
Labels: mode:renewal, status:code-review

#5781 Added a note to progressbar documentation
  doc/script_commands.txt
Labels: component:documentation, mode:prerenewal, mode:renewal, type:bug

#5785 Weight update gemstone (yellow, red, blue)
  db/re/item_db_etc.yml
  npc/custom/itemmall.txt
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, type:bug

#5784 Fixed an issue with mob db reload
  src/map/mob.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5794 Item Weight and EquipLevelMin update
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal, status:code-review

#5803 Added some missing Shadow equipments
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5807 Fix getnameditem command
  sql-files/upgrades/upgrade_20210331.sql
  src/map/atcommand.cpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5813 Adjusts Assassin Cross of Sunset ASPD bonus
  src/map/status.cpp
Labels: status:code-review

#5815 Fixes Head Crush vs Boss class
  src/map/skill.cpp
Labels: status:code-review
