Repository rathena/rathena, pull requests merged in 2021-09, with the labels that each got.

#6225 Adds missing effect to ID29463 Rune Knight Stone (Garment)
  db/re/item_db_etc.yml
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review, type:bug

#6241 Added an additional safeguard
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6243 Added an error message to openmail
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6244 Synced mobs and effects from divine pride
  db/re/mob_db.yml
  src/map/npc.hpp
  src/map/script_constants.hpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6245 Fixed an issue with RODEX's retrieve all
  src/map/mail.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6247 Script command "delitemidx"
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#5268 Fixes Fire Pillar item requirement check
  db/import-tmpl/skill_db.yml
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  db/skill_db.yml
  doc/skill_db.txt
  doc/yaml/db/skill_db.yml
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/csv2yaml.cpp
Labels: status:code-review

#6249 Pet autofeed config fix
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/pet.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6250 Added Custom Weight Check on quests_13_2
  npc/quests/quests_13_2.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6248 Clean-up the npc_enable_target function
  src/map/atcommand.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6252 Suggestion to support the aegis mob name for npc
  src/map/npc.cpp
  src/map/status.cpp
Labels: mode:renewal, mode:prerenewal, status:code-review

#6256 Added missing status_calc_npc for unitwalk script command
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6255 Fixes a potential map crash for atcommand mapflag
  src/map/atcommand.cpp
  src/map/map.cpp
Labels: status:code-review

#6257 Fixed autobonus on the same equip slot
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6262 Fixed opt_flag collision in status_change_end. Fixes #6192
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#6264 Fixed an issue in the quest system
  src/map/quest.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6240 Fixes skill aftercast delay
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review
