Repository rathena/rathena, pull requests merged in 2021-01, with the labels that each got.

#5667 Fixed memory leak when using loadnpc or reloadnpcfile command
  src/map/atcommand.cpp
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5670 Fixed a crash with cashshop errors
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5675 Fixed a critical bug in the sale system
  src/map/cashshop.cpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#5669 Added checks in geffen magic tournament instance
  npc/custom/official/GeffenMagicTournament.txt
Labels: status:code-review

#5673 Fixed an inverted nullpointer check
  src/map/battleground.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5674 Added boss icons for pets
  src/map/clif.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5671 Added some missing Kagerou/Oboro flags
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review, type:bug

#5668 [Suggestion] Item DB format for Script field
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  sql-files/item_db_equip.sql
  sql-files/item_db_etc.sql
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  sql-files/item_db_usable.sql
Labels: component:database, mode:prerenewal, mode:renewal, status:code-review, type:maintenance

#5647 RED_PILLAR to cards
  db/import-tmpl/item_db.yml
  db/item_db.yml
  db/pre-re/item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/item_db.txt
  doc/yaml/db/item_db.yml
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review

#5676 Fixed dummy item in SQL mode
  src/map/itemdb.cpp
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5672 Fixed monster exp definitions
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/map/atcommand.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/party.cpp
  src/map/party.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5598 Fixes Bowling Bash behavior
  conf/battle/skill.conf
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#5685 RoomOfConsciousness check
  npc/re/instances/RitualOfBlessing.txt
  npc/re/instances/RoomOfConsciousness.txt
Labels: component:script, status:code-review

#5683 Fixes Magic Immunity and status changes
  src/map/status.cpp
Labels: status:code-review

#5388 Session check standarization
  src/char/char.cpp
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/inter.cpp
  src/common/socket.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
Labels: status:code-review

#5564 Quest type: hunting location
  db/import-tmpl/quest_db.yml
  db/pre-re/quest_db.yml
  db/quest_db.yml
  db/re/quest_db.yml
  doc/yaml/db/quest_db.yml
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/quest.cpp
  src/map/quest.hpp
  src/tool/csv2yaml.cpp
Labels: component:core, component:database, mode:renewal, type:bug

#5596 Fix soulball packet in client 20200724ragexeRE+
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#4569 Refactored automatic mail deletion
  conf/char_athena.conf
  src/char/char.cpp
  src/char/char.hpp
  src/char/int_mail.cpp
  src/common/mmo.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5694 Fixed Costume Silent Executor Position
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review, type:bug

#5523 Questinfo correction
  doc/script_commands.txt
  src/map/map.cpp
  src/map/map.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/unit.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5700 Fixed memory leaks in getunits and addrid
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5699 Added Woodie card
  db/re/item_db_etc.yml
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review, type:bug

#5703 Fixes Cart Termination not ignoring autoguard/cicada
  db/pre-re/skill_db.yml
Labels: component:database, mode:prerenewal

#5705 Added atcommand documentation
  doc/atcommands.txt
Labels: component:documentation, mode:prerenewal, mode:renewal

#5709 Corrects Varetyr Spear cooldown and hit count
  db/re/skill_db.yml
Labels: status:code-review

#5460 Changed the way gender restrictions work
  conf/battle/items.conf
  db/import-tmpl/item_db.yml
  db/pre-re/item_db_equip.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  sql-files/item_db2.sql
  sql-files/item_db2_re.sql
  sql-files/item_db_equip.sql
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
Labels: component:database, mode:renewal, status:code-review, type:bug

#5718 Adds MVP attribute to Bijou
  db/re/mob_db.txt
Labels: status:code-review

#5720 Corrected the constant name for the Costume Enchantment Stone Boxes
  db/re/item_db_usable.yml
  sql-files/item_db_re_usable.sql
Labels: status:code-review

#5715 Added a config for respawn time variance
  conf/battle/monster.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5721 setnpcdisplay potential crash
  src/map/npc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5722 bReduceDamageReturn issue
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5711 Fixed homunculus exp definitions
  src/char/int_homun.cpp
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/homunculus.cpp
  src/map/homunculus.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5719 Fixes Golden X potion reflect effect
  src/map/battle.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5724 Setting to turn off a potential exploit in RoomOfConsciousness.txt
  npc/re/instances/RoomOfConsciousness.txt
Labels: component:script, mode:renewal, status:code-review, type:enhancement
