Repository rathena/rathena, pull requests merged in 2021-04, with the labels that each got.

#5782 Fix potential crash in pc_setpos
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:bug

#5819 Suggestion getiteminfo script command update
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/sample/getiteminfo.txt
  doc/script_commands.txt
  npc/custom/etc/autopot.txt
  npc/custom/item_signer.txt
  npc/custom/quests/quest_shop.txt
  npc/events/RWC_2012.txt
  npc/merchants/socket_enchant.txt
  npc/merchants/socket_enchant2.txt
  npc/other/Global_Functions.txt
  npc/other/monster_race.txt
  npc/quests/cooking_quest.txt
  npc/re/merchants/coin_exchange.txt
  npc/re/merchants/enchan_mal.txt
  npc/re/merchants/enchan_mora.txt
  npc/re/merchants/malangdo_costume.txt
  npc/re/quests/eden/eden_tutorial.txt
  npc/re/quests/quests_dewata.txt
  sql-files/item_db_etc.sql
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/item_db_re_usable.sql
  sql-files/item_db_usable.sql
  src/map/itemdb.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: status:code-review

#5826 Adjusts Loyalists Hood to Garment
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
  src/tool/yaml2sql.cpp
Labels: status:code-review

#5821 Added new cards and enchants
  db/re/item_combo_db.txt
  db/re/item_db_etc.yml
  sql-files/item_db_re_etc.sql
Labels: status:code-review

#5827 Fixes an example for script command makeitem3
  doc/script_commands.txt
Labels: status:code-review

#5833 Hotfix for issue 5831 (getequiprefinerycnt)
  db/re/item_db_etc.yml
  doc/script_commands.txt
  sql-files/item_db_re_etc.sql
Labels: component:database, status:code-review

#5818 Fixes Maya Purple Card and Box of Sunlight usage
  src/map/status.cpp
Labels: status:code-review

#5823 Fixes Cross Impact on GvG and Battleground maps
  src/map/skill.cpp
Labels: status:code-review

#5834 Removed duplicate combo
  db/re/item_combo_db.txt
Labels: component:database, status:code-review

#5809 Corrections in card_seller.txt
  npc/custom/card_seller.txt
Labels: component:script, status:code-review

#5824 Fixes Strip Weapon/Shield skills
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: status:code-review

#5825 Resolves Mercenary's Lex Divina skill
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: status:code-review

#5832 Corrects the behavior of Vacuum Extreme
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
Labels: status:code-review

#5812 Add support for new insurance
  npc/re/merchants/new_insurance.txt
  npc/re/scripts_athena.conf
  src/map/itemdb.hpp
  src/map/pc.cpp
Labels: component:core, component:database, component:script, mode:renewal, status:code-review, type:bug

#5841 Item DB update (weapon)
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#2494 Initial release of the refine UI
  conf/battle/feature.conf
  conf/battle/items.conf
  conf/msg_conf/map_msg.conf
  db/import-tmpl/refine.yml
  db/import-tmpl/refine_db.yml
  db/pre-re/refine.yml
  db/pre-re/refine_db.yml
  db/re/refine.yml
  db/re/refine_db.yml
  db/refine.yml
  doc/atcommands.txt
  doc/script_commands.txt
  npc/merchants/refine.txt
  npc/re/jobs/novice/academy.txt
  npc/re/merchants/advanced_refiner.txt
  npc/re/merchants/hd_refiner.txt
  npc/re/merchants/refine.txt
  npc/re/merchants/shadow_refiner.txt
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5842 Fixed RODEX's retrieve all feature
  src/map/clif.cpp
  src/map/mail.cpp
  src/map/pc.cpp
  src/map/pc.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5822 Fixes monster Sharp Shooting damage formula
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#5838 Fix TK_POWER Attack Bonus
  src/map/battle.cpp
Labels: component:skill, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5843 Fixed warning for YAML database header
  src/common/database.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5854 Fixed refine bonuses
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, priority:high, status:code-review, type:bug

#5858 Updated some enchants script according to KRO description
  db/re/item_db_etc.yml
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, status:code-review

#5859 Fixed items using F_CashPartyCall
  db/re/item_db_usable.yml
  npc/other/CashShop_Functions.txt
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal, status:code-review

#5861 Updated tomb of honor equipment (18972-18984)
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5866 Disables costumes on GvG maps
  npc/mapflag/gvg.txt
  npc/re/mapflag/gvg.txt
Labels: status:code-review

#5864 Fixed pet eggs in the cashshop
  src/map/cashshop.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5874 Updated enchant costumes box
  db/re/item_db_usable.yml
  db/re/item_misc.txt
  db/re/item_package.txt
  sql-files/item_db_re_usable.sql
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#5862 Added High Upgrade ATK
  db/re/refine.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#5868 Fixes Shadow Leap and Shadow Slash cast ranges
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: status:code-review

#5882 Fixes Ancilla and Spore Explosion consuming twice
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: status:code-review

#5883 Fixes Sharp Shooting ammo consumption
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#5888 Added some missing lapine Box
  db/re/item_db_usable.yml
  sql-files/item_db_re_usable.sql
Labels: component:database, mode:renewal, status:code-review

#5890 Fixed ViewID For Item ID 20236 & 31710
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, type:bug

#5892 Fixed get_githash
  src/map/script.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5893 Fixed reloading of statusdb
  src/map/atcommand.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5894 Removed refine UI state during warp
  doc/atcommands.txt
  npc/merchants/refine.txt
  npc/re/merchants/refine.txt
  src/map/pc.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5896 Added support for nemo's cashshop preview
  src/config/core.hpp
  src/map/clif.cpp
  src/map/packets_struct.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5897 Fixed the menu of the HD refiner and Basta npcs
  npc/re/merchants/hd_refiner.txt
Labels: component:script, mode:renewal, status:code-review

#5895 Added CL_CLL to all message categories
  src/common/showmsg.cpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5891 Made the char-server name available
  src/char/char_mapif.cpp
  src/map/chrif.cpp
  src/map/chrif.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:enhancement

#5899 Added some items used in the lapine system
  db/re/item_combo_db.txt
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: mode:renewal, status:code-review

#5900 Fixed potential crash on BG queue
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:prerenewal, mode:renewal, status:code-review, type:bug

#5911 Display item_id of current item combo set
  src/map/status.cpp
Labels: component:core, mode:prerenewal, mode:renewal, type:enhancement

#5913 Script correction of item 2185 (Magic_Reflector)
  db/re/item_db_equip.yml
  sql-files/item_db_re_equip.sql
Labels: component:database, mode:renewal, status:code-review

#5912 Fixed some issue in lasagna_npcs.txt
  npc/re/custom/lasagna/lasagna_npcs.txt
Labels: component:script, mode:renewal
