Repository rathena/rathena, pull requests merged in 2022-02, with the labels that each got.

#4370 Thanatos Tower Minor Fix
  npc/quests/thana_quest.txt
Labels: status:need more info

#6560 Resolves cardfix calculation going below zero
  src/map/battle.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6578 Correction of a bug with mob avail
  src/map/npc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6561 Updates to a few Sorcerer skills
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: status:code-review

#6562 Updates Golden Thief Bug card behavior
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/script_constants.hpp
  src/map/skill.hpp
  src/map/status.cpp
Labels: status:code-review

#6577 Changes the default value of itemDB's "Override" to 100
  db/import-tmpl/item_db.yml
  db/item_db.yml
  db/pre-re/item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/yaml/db/item_db.yml
  src/map/itemdb.cpp
  src/tool/csv2yaml.cpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6554 Infinite Space Instance
  db/re/instance_db.yml
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  npc/re/cities/comodo.txt
  npc/re/instances/InfiniteSpace.txt
  npc/re/mapflag/nobranch.txt
  npc/re/mapflag/nomemo.txt
  npc/re/mapflag/nosave.txt
  npc/re/mapflag/noteleport.txt
  npc/re/mapflag/nowarp.txt
  npc/re/mapflag/nowarpto.txt
  npc/re/mapflag/restricted.txt
  npc/re/merchants/InfiniteSpace_merchants.txt
  npc/re/scripts_athena.conf
Labels: component:database, component:script, mode:renewal, status:code-review, type:bug

#6565 Corrected script for some item #2
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, type:bug

#6582 Removes an extra sanity check for cardfix bonuses
  src/map/battle.cpp
Labels: status:code-review

#6590 Removed extra space/tab and sort the item id
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review

#6571 Added support for unlimited supplies in market shops
  doc/script_commands.txt
  sql-files/main.sql
  sql-files/upgrades/upgrade_20220204.sql
  src/map/clif.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6593 Fix wrong command to get armor level.
  db/re/item_db_etc.yml
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review, type:enhancement

#6604 Fix compiling for PACKETVER 20130807
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6599 Implements Synthesis and Upgrade UI items
  db/re/item_db_equip.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#6605 Fixes cooking value not updating properly
  src/map/pc.cpp
  src/map/skill.cpp
Labels: status:code-review

#6607 Fixes monster MD_SWORD_FISH modes
  db/re/item_db_equip.yml
  db/re/mob_db.yml
Labels: component:database, mode:renewal, type:bug

#5112 Allow creating instance without timer or data
  db/import-tmpl/instance_db.yml
  db/instance_db.yml
  db/pre-re/instance_db.yml
  db/re/instance_db.yml
  doc/script_commands.txt
  doc/yaml/db/instance_db.yml
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6616 Fixes Tuna Belly and Shrimp Party behaviors
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#6618 Implements MF_NOPETCAPTURE
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_grm.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  doc/mapflags.txt
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script_constants.hpp
Labels: status:code-review

#6624 Changes mapflag storage type to vector
  src/map/map.cpp
  src/map/map.hpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6626 Corrected property name on skill_db.yml header doc
  db/import-tmpl/skill_db.yml
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: component:documentation, mode:renewal, mode:prerenewal, type:bug

#6629 Removed duplicate entry on re/job_exp.yml
  db/re/job_exp.yml
Labels: component:database, mode:renewal, type:bug

#6600 Dummy Summoner Star Emperor Soul Reaper Level 175+
  db/re/job_basepoints.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#6597 Removed leftovers from unreleased classes
  conf/atcommands.yml
  db/import-tmpl/job_stats.yml
  db/pre-re/job_exp.yml
  db/re/job_basepoints.yml
  db/re/job_exp.yml
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#6625 Revamped Laphine UIs
  db/import-tmpl/item_group_db.yml
  db/import-tmpl/laphine_synthesis.yml
  db/import-tmpl/laphine_upgrade.yml
  db/item_group_db.yml
  db/laphine_synthesis.yml
  db/laphine_upgrade.yml
  db/pre-re/item_group_db.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/item_randomopt_group.yml
  db/re/laphine_synthesis.yml
  db/re/laphine_upgrade.yml
  doc/script_commands.txt
  doc/yaml/db/item_group_db.yml
  sql-files/logs.sql
  sql-files/upgrades/upgrade_20220222_logs.sql
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/tool/csv2yaml.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#6633 Added RC2_Malangdo race groups
  db/re/mob_db.yml
  doc/item_bonus.txt
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  sql-files/upgrades/upgrade_20220224.sql
  src/map/map.hpp
  src/map/mob.cpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, mode:prerenewal, type:bug

#6634 Adjusted Homun S Quest to support Biolo
  npc/re/quests/homun_s.txt
Labels: component:script, mode:renewal, type:bug
