Repository rathena/rathena, pull requests merged in 2022-10, with the labels that each got.

#7297 Database entries for Episode 16.1 and 16.2 Memorial Dungeons
  db/re/instance_db.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/mercenary_db.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
Labels: component:database, mode:renewal, hacktoberfest-accepted

#7301 Implemented refine result broadcast packet
  conf/battle/items.conf
  db/import-tmpl/refine.yml
  db/pre-re/refine.yml
  db/re/refine.yml
  db/refine.yml
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review, hacktoberfest-accepted

#7316 Fixed several item scripts
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review, hacktoberfest-accepted

#7277 Corrected script for some item #11
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/laphine_upgrade.yml
Labels: component:database, mode:renewal, status:code-review

#7293 Initial release of the Poring village instance
  db/mob_chat_db.yml
  db/re/instance_db.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/instances/PoringVillage.txt
  npc/re/scripts_athena.conf
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, component:script, mode:renewal, status:code-review

#7326 Allow Blacksmith Blessing usage on level 5 weapons and level 2 armors
  db/re/refine.yml
Labels: status:code-review

#7333 Fixes Marine Sphere behavior
  db/pre-re/mob_skill_db.txt
  db/re/mob_skill_db.txt
  src/map/mob.cpp
  src/map/skill.cpp
Labels: status:code-review

#7329 Updates the script command doc min/max int value
  doc/script_commands.txt
Labels: priority:low, component:documentation, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7325 add nlohmann json to better support web service
  3rdparty/CMakeLists.txt
  3rdparty/README.txt
  3rdparty/json/CMakeLists.txt
  3rdparty/json/LICENSE.MIT
  3rdparty/json/include/nlohmann/json.hpp
  3rdparty/json/include/nlohmann/json_fwd.hpp
  src/web/CMakeLists.txt
  src/web/Makefile.in
  src/web/charconfig_controller.cpp
  src/web/merchantstore_controller.cpp
  src/web/userconfig_controller.cpp
  src/web/web-server.vcxproj
  src/web/webutils.cpp
  src/web/webutils.hpp
Labels: component:core, priority:high, mode:renewal, mode:prerenewal, status:code-review, type:bug, type:enhancement

#7339 Fixed zero-length packet warning on party member logoff. Fixes #7324
  src/map/clif.cpp
Labels: status:code-review

#7338 Fixed "Unequip All" button not working on main server clients.
  src/map/clif.cpp
Labels: status:code-review

#7323 Initial release of Yuno (Juno?) monster society
  db/re/quest_db.yml
  npc/re/quests/juno_monster_society.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#7341 Updated rockridge npcs
  npc/re/merchants/enchan_rockridge.txt
Labels: status:confirmed, component:script, mode:renewal, hacktoberfest-accepted

#7327 Updates NPC_SIEGEMODE comment to known behavior
  src/map/skill.cpp
Labels: component:skill, priority:low, mode:renewal, mode:prerenewal, type:bug

#7304 Fixed an invalid primary key in web.sql
  sql-files/upgrades/upgrade_20221001.sql
  sql-files/web.sql
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug, hacktoberfest-accepted

#7305 Removed a debug message in web-server
  src/web/charconfig_controller.cpp
  src/web/userconfig_controller.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug, hacktoberfest-accepted

#7317 Fixed some more hardcoded directions
  src/map/map.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance, hacktoberfest-accepted

#7265 Adds SC_WEAPONBREAKER status
  db/pre-re/skill_db.yml
  db/pre-re/status.yml
  db/re/skill_db.yml
  db/re/status.yml
  doc/status_change.txt
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#7308 Update Autopot NPC
  npc/custom/etc/autopot.txt
Labels: hacktoberfest-accepted

#7354 Updated mapcache
  conf/maps_athena.conf
  db/map_cache.dat
  db/map_index.txt
Labels: component:database, mode:renewal, status:code-review

#7328 Fixes SA_DRAGONOLOGY MATK behavior
  src/map/status.cpp
Labels: component:skill, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7306 Updates the cooldowns for new guild skills
  db/re/skill_db.yml
Labels: status:code-review, hacktoberfest-accepted

#7353 Replaced itemdb_exists by item_db.exists
  src/map/cashshop.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/quest.cpp
  src/map/script.cpp
  src/map/searchstore.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7311 Fixes a possible size mismatch for isspace()
  src/common/strlib.cpp
Labels: status:code-review, hacktoberfest-accepted

#7352 Added support mob name as parameter in mob spawn definition
  src/map/npc.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#7315 Adds support for macro detection
  conf/battle/client.conf
  conf/groups.yml
  db/captcha_db.yml
  db/import-tmpl/captcha_db.yml
  doc/captcha_db.txt
  doc/permissions.txt
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/packets_struct.hpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pc_groups.hpp
Labels: status:code-review, hacktoberfest-accepted

#7361 Minor fix script Carbonated Water Vending Machine
  npc/re/quests/juno_monster_society.txt
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#7357 Added new items up to october 2022
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review

#7286 Okolnir quest (missed warp coordinates)
  npc/quests/okolnir.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#7368 SubType correction of item ID 28141
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#7307 Add cap_value script command
  doc/script_commands.txt
  src/map/script.cpp
Labels: hacktoberfest-accepted

#6304 Enable *plagiarism script commands
  doc/script_commands.txt
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7309 Add *getrandmobid script command
  doc/script_commands.txt
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: hacktoberfest-accepted

#7310 Add PC Fame script commands
  doc/script_commands.txt
  src/map/script.cpp
Labels: hacktoberfest-accepted

#7375 Follow up to c3a171d
  src/map/pc.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7372 Added UMOB_DAMAGETAKEN for mob controller
  doc/script_commands.txt
  src/map/battle.cpp
  src/map/mob.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/status.cpp
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#7373 Added missing SubType for item ID 1998
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#7362 Added Missing Shops Script
  npc/re/merchants/Emperium_Seller.txt
  npc/re/merchants/Slot_Move_Card_Sales.txt
  npc/re/merchants/shops.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted
