Repository rathena/rathena, pull requests merged in 2022-09, with the labels that each got.

#7225 Implemented the /call command
  sql-files/main.sql
  sql-files/upgrades/upgrade_20220831.sql
  src/char/char.cpp
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7230 Fixed a crash caused by wrong attribute ordering. Fixes #7229
  src/map/itemdb.cpp
Labels: status:code-review

#7231 Fixes an issue with whisper unblocks
  src/map/clif.cpp
Labels: status:confirmed, component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7213 Added several missing items
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review

#7232 Fixes pre-re item table loading
  src/map/itemdb.cpp
Labels: status:confirmed, component:core, priority:low, mode:renewal, mode:prerenewal, type:bug

#7235 Fixes a compile error for older clients
  src/map/clif.cpp
Labels: status:code-review

#7228 Added mob name support to some script commands
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7219 Fixed billing slots
  src/common/mmo.hpp
  src/config/core.hpp
  src/login/account.cpp
  src/login/login.cpp
  src/login/loginchrif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7237 Added some missing ifdefs for old clients
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7186 Initial release of item enchant UI
  conf/msg_conf/map_msg.conf
  db/import-tmpl/item_enchant.yml
  db/item_enchant.yml
  db/re/item_db_usable.yml
  db/re/item_enchant.yml
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/packets.hpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7249 Fixes Offertorium and Magnificat stacking
  db/pre-re/status.yml
  db/re/status.yml
Labels: status:code-review

#7124 Adjusts Enchanting Shadow behavior
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: status:code-review

#7253 Added missing status flag for Active_Monster_Transform and Monster_Transform
  db/pre-re/status.yml
Labels: component:database, mode:prerenewal, status:code-review

#7254 Updated the english name of some items
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#7257 Fixes Lif - Brain Surgery SP bonus
  src/map/status.cpp
Labels: status:code-review

#5204 Fixed some issue with clif_loadConfirm
  src/map/clan.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/party.cpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7242 Modified the Bug Report Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type:enhancement

#7177 Corrected script for some item #10
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/status.yml
  npc/re/merchants/malangdo_costume.txt
  src/map/itemdb.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, mode:renewal, status:code-review

#7239 Initial release of item package selection
  db/import-tmpl/item_packages.yml
  db/item_packages.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/item_packages.yml
  sql-files/logs.sql
  sql-files/upgrades/upgrade_20220912_logs.sql
  src/char/packets.hpp
  src/config/packets.hpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/clif_shuffle.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/map-server.vcxproj
  src/map/packets.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7262 Adds a battle config for Guild Skill saving
  conf/battle/guild.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/chrif.cpp
Labels: status:code-review

#7267 Fixed potential crash via skill GN_FIRE_EXPANSION.
  src/map/skill.cpp
Labels: status:code-review

#7053 Implements petautobonus script commands
  db/re/pet_db.yml
  doc/script_commands.txt
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7278 Adds support for the new form for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: status:code-review, type:enhancement

#7272 Fixes petautobonus issues
  src/map/pet.cpp
Labels: status:code-review

#7275 Fixed caching of databases during runtime
  src/common/database.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7281 Nemo patch ExtendOldCashShopPreview
  src/config/core.hpp
  src/map/clif.cpp
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:enhancement

#7276 Fixed some packets for 2022 clients
  src/map/atcommand.cpp
  src/map/battleground.cpp
  src/map/buyingstore.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/elemental.cpp
  src/map/guild.cpp
  src/map/npc.cpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7258 Fixes Skill Damage Database reflecting damage
  src/map/battle.cpp
Labels: status:code-review

#7266 Fixes the EXP, Drop, and Penalty message at login
  src/map/clif.cpp
Labels: status:code-review

#7264 Fixes to Lullaby, Pang Voice, and Wink of Charm
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#7214 Refactor generator to support future features
  doc/map_server_generator.md
  rAthena.sln
  src/common/cli.cpp
  src/map/Makefile.in
  src/map/battle.cpp
  src/map/map-server-generator.vcxproj
  src/map/map-server-generator.vcxproj.filters
  src/map/map.cpp
  src/map/map.hpp
  src/map/navi.cpp
  src/map/navi.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  tools/navigenerator.bat
Labels: component:core, component:tool, status:code-review, type:enhancement
