Repository rathena/rathena, pull requests merged in 2022-12, with the labels that each got.

#7189 Fix grade upgrade fail announcement
  db/enchantgrade.yml
  db/import-tmpl/enchantgrade.yml
  db/re/enchantgrade.yml
  src/map/clif.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review

#7477 Update GitHub workflows
  .github/workflows/build_servers_clang.yml
  .github/workflows/build_servers_cmake.yml
  .github/workflows/build_servers_gcc.yml
  .github/workflows/build_servers_modes.yml
  .github/workflows/build_servers_msbuild.yml
  .github/workflows/build_servers_packetversions.yml
  .github/workflows/build_servers_vip.yml
  .github/workflows/npc_db_validation.yml
Labels: priority:low, component:tool, status:code-review, type:enhancement

#5579 Fix WE_CALLPARTNER, WE_CALLPARENT and WE_CALLBABY falltrough check
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
  src/map/skill.cpp
Labels: status:code-review

#7484 Minor corrections to SQL readme
  sql-files/README.md
Labels: priority:low, component:documentation, status:code-review, type:enhancement

#7359 New macro detection features
  conf/battle/client.conf
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/status.cpp
Labels: component:core, priority:low, mode:renewal, status:code-review, type:enhancement

#7356 Refactor status change entries
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battleground.cpp
  src/map/buyingstore.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/elemental.cpp
  src/map/mail.cpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, priority:medium, status:code-review, type:enhancement, type:maintenance

#7312 Adds battle config mob_respawn_time
  conf/battle/monster.conf
  doc/script_commands.txt
  npc/pre-re/mobs/dungeons/nyd_dun.txt
  npc/pre-re/mobs/dungeons/prt_maze.txt
  npc/re/mobs/dungeons/glastheim.txt
  npc/re/mobs/verus.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
  src/map/npc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement, hacktoberfest-accepted

#7493 Update items first aid starter pack
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#7486 Multiple dynamic npc
  src/map/npc.cpp
  src/map/pc.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7495 Cleaned up monster skill status checks
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7208 Added CodeQL analysis
  .github/workflows/analysis_codeql.yml
  src/common/ers.cpp
  src/map/battle.cpp
  src/map/script.cpp
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7496 Small correction for SHC_SAVAGE_IMPACT and SHC_DANCING_KNIFE skills
  src/map/path.cpp
  src/map/path.hpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, status:code-review

#7413 Update warper npc
  npc/custom/warper.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#7497 Fixed dynamic NPC timeout
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/npc.cpp
  src/map/packets.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7451 Added and Updated Missing Items
  db/re/item_db_equip.yml
  db/re/item_group_db.yml
  db/re/laphine_synthesis.yml
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#7450 Initial version of cashmall
  conf/battle/feature.conf
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/laphine_synthesis.yml
  npc/merchants/cash_hair.txt
  npc/re/mapflag/nobranch.txt
  npc/re/mapflag/nomemo.txt
  npc/re/mapflag/nopenalty.txt
  npc/re/mapflag/nopvp.txt
  npc/re/mapflag/noteleport.txt
  npc/re/merchants/barters.yml
  npc/re/merchants/barters/cashmall.yml
  npc/re/merchants/cashmall.txt
  npc/re/merchants/enchan_upg.txt
  npc/re/merchants/shadow_refiner.txt
  npc/re/other/item_merge.txt
  npc/re/scripts_athena.conf
  npc/scripts_athena.conf
  sql-files/item_db_re_equip.sql
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/itemdb.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: component:database, component:script, mode:renewal, status:code-review, type:bug

#7449 Fixed gaps in random options
  sql-files/upgrades/upgrade_20221218.sql
  src/map/clif.cpp
  src/map/itemdb.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7498 Fixed a potential issue with getmapxy
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7502 Fixed specialeffect with npc names
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#7494 Adds official Wand of Hermode clear list
  db/pre-re/status.yml
  db/re/status.yml
  doc/status.txt
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:skill, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7303 Start refactoring the core to C++
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_cnslif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/common/cli.cpp
  src/common/core.cpp
  src/common/core.hpp
  src/common/socket.cpp
  src/common/socket.hpp
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginchrif.cpp
  src/login/loginclif.cpp
  src/login/logincnslif.cpp
  src/map/atcommand.cpp
  src/map/channel.cpp
  src/map/chrif.cpp
  src/map/chrif.hpp
  src/map/clif.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
  src/tool/mapcache.cpp
  src/tool/yaml2sql.cpp
  src/tool/yamlupgrade.cpp
  src/tool/yamlupgrade.hpp
  src/web/web.cpp
  src/web/web.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance, hacktoberfest-accepted

#7489 Added new etc/equipment up to december 2022
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_enchant.yml
  db/re/laphine_synthesis.yml
Labels: component:database, mode:renewal, status:code-review

#7224 Initial release of adventure agency
  conf/inter_athena.conf
  sql-files/main.sql
  sql-files/upgrades/upgrade_20221220.sql
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/packets.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.hpp
  src/web/partybooking_controller.cpp
  src/web/partybooking_controller.hpp
  src/web/sqllock.cpp
  src/web/sqllock.hpp
  src/web/web-server.vcxproj
  src/web/web-server.vcxproj.filters
  src/web/web.cpp
  src/web/web.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7505 Fixes GitHub Workflow Concurrency flag
  .github/workflows/analysis_codeql.yml
  .github/workflows/build_servers_clang.yml
  .github/workflows/build_servers_cmake.yml
  .github/workflows/build_servers_gcc.yml
  .github/workflows/build_servers_modes.yml
  .github/workflows/build_servers_msbuild.yml
  .github/workflows/build_servers_packetversions.yml
  .github/workflows/build_servers_vip.yml
  .github/workflows/npc_db_validation.yml
Labels: priority:low, component:tool, status:code-review, type:enhancement

#7485 Corrected script for some item #13
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/laphine_upgrade.yml
Labels: component:database, mode:renewal, status:code-review

#7518 Fixed an issue with mail
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7516 Fixed bAddMonsterDropItemGroup
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug
