Repository rathena/rathena, pull requests merged in 2022-03, with the labels that each got.

#4003 Implemented Ghost Palace exchange NPC
  db/re/item_db_etc.yml
  npc/re/instances/GhostPalace.txt
  npc/re/merchants/ghost_palace_exchange.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, type:bug

#6641 Mapflag Cleanup
  npc/mapflag/battleground.txt
  npc/mapflag/gvg.txt
  npc/mapflag/gvg_noparty.txt
  npc/mapflag/hidemobhpbar.txt
  npc/mapflag/jail.txt
  npc/mapflag/night.txt
  npc/mapflag/nightmare.txt
  npc/mapflag/nobranch.txt
  npc/mapflag/nocostume.txt
  npc/mapflag/noicewall.txt
  npc/mapflag/nomemo.txt
  npc/mapflag/nopenalty.txt
  npc/mapflag/nopvp.txt
  npc/mapflag/noreturn.txt
  npc/mapflag/nosave.txt
  npc/mapflag/noskill.txt
  npc/mapflag/noteleport.txt
  npc/mapflag/nowarp.txt
  npc/mapflag/nowarpto.txt
  npc/mapflag/partylock.txt
  npc/mapflag/pvp.txt
  npc/mapflag/pvp_noguild.txt
  npc/mapflag/pvp_noparty.txt
  npc/mapflag/reset.txt
  npc/mapflag/restricted.txt
  npc/mapflag/skill_damage.txt
  npc/mapflag/skill_duration.txt
  npc/mapflag/town.txt
  npc/re/mapflag/gvg.txt
  npc/re/mapflag/hidemobhpbar.txt
  npc/re/mapflag/night.txt
  npc/re/mapflag/nobranch.txt
  npc/re/mapflag/nocostume.txt
  npc/re/mapflag/noicewall.txt
  npc/re/mapflag/nomemo.txt
  npc/re/mapflag/nopenalty.txt
  npc/re/mapflag/nopvp.txt
  npc/re/mapflag/nosave.txt
  npc/re/mapflag/noteleport.txt
  npc/re/mapflag/nowarp.txt
  npc/re/mapflag/nowarpto.txt
  npc/re/mapflag/partylock.txt
  npc/re/mapflag/privateairship.txt
  npc/re/mapflag/reset.txt
  npc/re/mapflag/restricted.txt
  npc/re/mapflag/skill_duration.txt
  npc/re/mapflag/town.txt
  npc/re/scripts_mapflags.conf
Labels: component:script, mode:renewal, mode:prerenewal, type:maintenance

#6119 Fixed CG_HERMODE
  src/map/skill.cpp
Labels: component:skill, mode:renewal, status:code-review, type:bug

#6637 Illusion of Moonlight
  db/mob_chat_db.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/merchants/enchan_illusion_16_2.txt
  npc/re/mobs/dungeons/pay_d03_i.txt
  npc/re/quests/quests_16_2_illusion.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_monsters.conf
Labels: component:database, component:script, mode:renewal, status:code-review, type:bug

#6651 Added missing export for bWeaponSubSize
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6542 Added a Github Action for CMake
  .github/workflows/build_servers_cmake.yml
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6659 Fixes a crash with script command sc_end
  src/map/script.cpp
Labels: status:code-review

#6660 Fixes Slim Potion Pitcher item lookup
  src/map/skill.cpp
Labels: status:code-review

#6503 Updated rockridge npcs to official
  db/re/item_db_etc.yml
  db/re/laphine_synthesis.yml
  db/re/mob_db.yml
  db/re/quest_db.yml
  npc/re/merchants/enchan_rockridge.txt
  npc/re/quests/quests_rockridge.txt
  sql-files/upgrades/upgrade_20221103.sql
Labels: component:script, mode:renewal, status:code-review

#6652 Corrected script for some item #4
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#6662 open_quest_ui script command
  doc/script_commands.txt
  src/map/clif.hpp
  src/map/script.cpp
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#6674 sc_end SC_ALL fix
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6668 Spiral pierce immune fix
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6678 Fixed atcommand jail
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6679 Added a new flag SCF_NOFORCEDEND
  db/pre-re/status.yml
  db/re/status.yml
  doc/status.txt
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6592 kRO patch 2022-02-03/04 items
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/laphine_synthesis.yml
  db/re/laphine_upgrade.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#6682 Adds some missing statuses to skills
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6623 kRO patch 2022-02-16 items
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#6683 Fixed EFST initialization
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6690 Expands the SC start check
  db/pre-re/status.yml
  db/re/status.yml
  doc/status.txt
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:code-review

#6684 Implements some Reform UI items
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#6697 Fixed soul linking
  db/re/status.yml
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6698 Fixed mado gear display
  src/map/clif.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#6661 Converts the SCB flags to bitset
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#6699 Fixed SL_HIGH
  src/common/random.cpp
  src/common/random.hpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6700 Cleanup for some Soul Reaper skills
  db/re/status.yml
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#6301 Update Item Card slot count
  doc/script_commands.txt
  src/map/pc.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug, hacktoberfest-accepted

#6707 Fixes NoWalkDelay item bonus
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6714 Fixes Wug Rider allowing physical attacks
  src/map/unit.cpp
Labels: status:code-review

#6728 Adds 10 new enchant items
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal

#6733 Fixes SCB calculations
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/homunculus.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6716 Fixes Grand Cross self damage
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#6663 Corrected script for some item #5
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal

#6740 Fixes remaining status calculation flag issues
  src/map/status.cpp
Labels: component:core, priority:high, mode:renewal, mode:prerenewal, status:code-review

#6736 Updates Quest skills from kRO patch
  db/re/produce_db.txt
  db/re/skill_db.yml
  doc/status_change.txt
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: status:code-review

#6737 Adds INF2_ISTOGGLEABLE skill flag
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: component:database, component:core, component:skill, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6739 Fixed a mistake in quests_rockridge.txt
  npc/re/quests/quests_rockridge.txt
Labels: component:script, mode:renewal, status:code-review

#6738 Temporary fix of malangdo costume NPC Menu
  npc/re/merchants/malangdo_costume.txt
Labels: component:script, mode:renewal, status:code-review

#6281 Implemented new bonus for official Sarah Card behavior. Fixes #6189
  db/re/item_db_etc.yml
  doc/item_bonus.txt
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
Labels: status:code-review, hacktoberfest-accepted

#6759 Corrects sql upgrade file name for upgrade_20220311
  sql-files/upgrades/upgrade_20220311.sql
Labels: component:database

#6757 Fixes monster_ai battle config
  src/map/battle.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6711 Fixes Reading Spellbook behavior
  db/re/status.yml
  src/map/skill.cpp
  src/map/skill.hpp
Labels: status:code-review

#6760 Fixes mobs res/mres always 0
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review

#6758 Some Items Fixes
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, type:bug

#6755 Natural recovery formula and interval behavior
  src/map/elemental.cpp
  src/map/homunculus.cpp
  src/map/mercenary.cpp
  src/map/pc.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6766 Fixed Pre-Re SoftDEF Formula
  src/map/battle.cpp
Labels: component:core, mode:prerenewal, type:bug

#6767 Fixed some LGTM warnings
  src/char/char_mapif.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#6750 Update RE Renter NPC
  npc/re/merchants/renters.txt
Labels: component:script, mode:renewal, status:code-review, type:bug
