Repository rathena/rathena, pull requests merged in 2022-01, with the labels that each got.

#6435 Disallow changing to 4th on pre-renewal
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, status:code-review, type:bug

#6438 Fixed pc_checkskill in pre-renewal
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, status:code-review, type:bug

#6439 Fixed pet capture rate
  conf/battle/pet.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pet.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6431 Initial support for 2021-11-03RagexeRE
  src/char/char-server.vcxproj
  src/char/char-server.vcxproj.filters
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/packets.hpp
  src/config/packets.hpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/clif_shuffle.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6446 Initial release of stylist UI
  conf/battle/client.conf
  conf/msg_conf/map_msg.conf
  db/import-tmpl/stylist.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/stylist.yml
  db/stylist.yml
  doc/atcommands.txt
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/map-server.vcxproj
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/packets.hpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#6204 Fixed Giant Fly Wing behavior
  doc/script_commands.txt
  npc/other/CashShop_Functions.txt
  src/map/script.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, hacktoberfest-accepted

#6490 Fix esma with no buffs
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6499 Added 4th class related random options
  db/re/item_randomopt_db.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#6162 Converted item_combo_db txt to yml
  db/import-tmpl/item_combo_db.txt
  db/import-tmpl/item_combos.yml
  db/item_combos.yml
  db/pre-re/item_combo_db.txt
  db/pre-re/item_combos.yml
  db/re/item_combo_db.txt
  db/re/item_combos.yml
  doc/atcommands.txt
  doc/yaml/db/item_combos.yml
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/status.cpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review

#6485 Implemented inventory expansion
  sql-files/main.sql
  sql-files/upgrades/upgrade_20220112.sql
  src/char/char.cpp
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/storage.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6504 Added a check for MAX_SKILL being to small
  src/common/mmo.hpp
  src/map/achievement.cpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/yaml.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6498 Added some missing shield view ids
  db/pre-re/item_db_equip.yml
  db/re/item_db_equip.yml
  src/map/itemdb.cpp
Labels: component:database, mode:renewal, status:code-review, type:bug

#6495 Synced packets_struct.hpp with Hercules
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6491 Addition of Episode 15.2 : Infinite Space monsters
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
Labels: component:database, mode:renewal, type:bug

#6511 Fixed players without can_trade permission selling items to NPC
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6517 Fixed viewing player equipment
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6518 Fixed vending packets for 2020 and 2021
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6514 Script command healap
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:script, mode:renewal

#6513 Updated pc_cant_act2
  src/map/pc.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6516 Corrected callshop arguments in eden_market.txt
  doc/script_commands.txt
  npc/re/merchants/eden_market.txt
Labels: component:script, mode:renewal, status:code-review

#6502 Implemented new items up to january 5, 2022
  db/re/item_combos.yml
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#6522 Fix small typo on Jobmaster
  npc/custom/jobmaster.txt
Labels: component:script, mode:renewal, mode:prerenewal, type:bug

#6512 Github Build Actions for Pull Requests
  .github/workflows/build_servers.yml
  tools/ci/import_sql.sh
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:enhancement, (╯°□°)╯︵ ┻━┻

#6526 Implemented missing beat shop items
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#6527 Minor bonus script const fix
  db/re/item_db_etc.yml
Labels: component:database, mode:renewal, status:code-review, type:enhancement

#6520 Github Action for NPC and DB Validation
  .github/workflows/npc_db_validation.yml
  tools/ci/import_sql.sh
  tools/ci/sql.sh
Labels: component:database, component:script, component:tool, mode:renewal, mode:prerenewal, status:code-review, (╯°□°)╯︵ ┻━┻

#6531 Removed appveyor CI
  README.md
  appveyor.yml
Labels: component:tool, mode:renewal, mode:prerenewal, type:maintenance

#6532 Removed travis CI
  .travis.yml
  README.md
Labels: component:tool, mode:renewal, mode:prerenewal, type:maintenance

#6534 Episode 14.3 - Flame Basin Daily Quest Reward
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#6506 Implementing Stylist UI Script
  npc/merchants/hair_dyer.txt
  npc/merchants/hair_style.txt
  npc/pre-re/merchants/hair_dyer.txt
  npc/pre-re/merchants/hair_style.txt
  npc/pre-re/scripts_athena.conf
  npc/pre-re/scripts_warps.conf
  npc/pre-re/warps/cities/alberta.txt
  npc/re/custom/lasagna/lasagna_npcs.txt
  npc/re/merchants/Extended_Stylist.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_warps.conf
  npc/re/warps/cities/alberta.txt
  npc/warps/cities/alberta.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6535 Fixed a display problem in refine UI
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6540 Added Frost_Crystal consumable effect
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, type:bug

#6508 Initial release of barter shops
  conf/inter_athena.conf
  doc/script_commands.txt
  npc/barters.yml
  npc/custom/barters.yml
  npc/re/merchants/barters.yml
  sql-files/logs.sql
  sql-files/main.sql
  sql-files/upgrades/upgrade_20220121.sql
  sql-files/upgrades/upgrade_20220121_logs.sql
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/packets.hpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6541 Added a new mapflag for disabling renewal exp & drop penalty
  doc/mapflags.txt
  src/map/map.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#6523 Corrected script for some item #1
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#6539 Quest Database - TimeLimit cleanup
  db/re/quest_db.yml
Labels: component:database, mode:renewal, type:bug

#6546 Removed duplicates combos in item_combos.yml
  db/re/item_combos.yml
Labels: component:database, mode:renewal, status:code-review

#6548 Fix packet size calculation for normal barter shops
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#6549 Added feature configs for barter shops
  conf/battle/feature.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/npc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6575 Added BaseASPD default values when reading JobDatabase
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review
