Repository rathena/rathena, pull requests merged in 2022-06, with the labels that each got.

#6995 Adds safety check for Barter Shops
  src/map/npc.cpp
Labels: component:core, priority:low, mode:renewal, status:code-review, type:bug

#6993 Added barter npcs to sell/exchange refine ore
  db/re/item_db_etc.yml
  npc/re/merchants/barters.yml
  npc/re/merchants/barters/refine.yml
  npc/re/merchants/refine.txt
Labels: component:script, mode:renewal, status:code-review

#7001 Added Beginner Items
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#7002 Fixes Battlegrounds and atcommand reloadscript
  npc/battleground/flavius/flavius01.txt
  npc/battleground/flavius/flavius02.txt
  npc/battleground/kvm/kvm01.txt
  npc/battleground/kvm/kvm02.txt
  npc/battleground/kvm/kvm03.txt
  npc/battleground/tierra/tierra01.txt
  npc/battleground/tierra/tierra02.txt
Labels: status:code-review

#6998 Fixes Ride In Lightning SP cost
  db/re/skill_db.yml
Labels: component:database, status:confirmed, component:skill, priority:low, mode:renewal, status:code-review

#7005 Player skills no longer proc equip break on mobs
  conf/battle/battle.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/skill.cpp
Labels: status:code-review

#7006 Increases the server config character limit
  src/char/inter.cpp
  src/login/account.cpp
  src/map/map.cpp
Labels: status:code-review

#6986 Adds the CONVERT_ALL macro for YAML tools
  src/tool/readme.md
  src/tool/yaml.hpp
  src/tool/yaml2sql.cpp
Labels: priority:low, component:tool, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7018 Small fix on duplicate item
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#7013 Store item prices update
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#6980 Resolves duplicate status calculation on players
  src/map/status.cpp
Labels: status:code-review

#6988 Fixes an issue with instance timer display
  src/map/instance.cpp
  src/map/instance.hpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6400 Fixed intimacy reduction for Vanilmirth Self-destruction and S.B.R.44
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, status:need more info, type:bug

#7036 Added missing script on some items
  db/re/item_db_equip.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#7041 Adds support for Spirit Handler in SQL items
  sql-files/item_db2_re.sql
  sql-files/item_db_re.sql
  src/map/itemdb.cpp
  src/tool/yaml2sql.cpp
Labels: component:database, component:core, priority:low, mode:renewal, type:bug

#6999 Allow Skill Damage Adjustments account for reflect
  src/map/battle.cpp
  src/map/battle.hpp
Labels: status:code-review

#7046 Fixed Splendid Box2 Type
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#7047 Updated mapcache
  conf/maps_athena.conf
  db/map_cache.dat
  db/map_index.txt
Labels: component:database, mode:renewal, status:code-review

#7050 Fixed Archer Tutorial NPC not showing dialog
  npc/quests/first_class/tu_archer.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7042 Weapon Blocking can now trigger on ATK_MISS
  src/map/battle.cpp
Labels: status:code-review

#7056 Fix 1 item script (Item ID: 23012)
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#7061 Fixes a potential crash with database reloading
  src/common/database.hpp
Labels: status:code-review

#7065 Fixed reloadpcdb
  src/common/database.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7072 Fixes some bonus inconsistencies
  db/pre-re/item_db_equip.yml
  db/re/item_db_equip.yml
  db/re/pet_db.yml
Labels: status:code-review
