Repository rathena/rathena, pull requests merged in 2022-08, with the labels that each got.

#7149 Fixes script command equip
  src/map/script.cpp
Labels: status:code-review

#7122 Fixes script command rentalcountitem
  src/map/script.cpp
Labels: status:code-review

#7158 Removed duplicate combos
  db/re/item_combos.yml
Labels: component:database, mode:renewal, status:code-review

#7159 Correction of the item script of the item "Hourglass Necklace"
  db/re/item_db_equip.yml
Labels: component:database, mode:renewal, status:code-review

#7164 Cleaned up
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#7160 Fixes pre-renewal duet dancing
  src/map/status.cpp
Labels: status:code-review

#7157 Updates the behavior of Overheat
  src/map/battle.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, component:skill, priority:low, mode:renewal, status:code-review, type:bug

#7154 Allow the player to stand on a cell occupied by disabled/hidden npc
  src/map/map.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7156 Implemented map specific drops
  db/import-tmpl/map_drops.yml
  db/map_drops.yml
  db/re/map_drops.yml
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7115 Corrected script for some item #9
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/mob_db.yml
Labels: component:database, mode:renewal, status:code-review

#7166 Cleans up Dancing cancellation
  src/map/status.cpp
Labels: component:core, component:skill, priority:low, mode:prerenewal, status:code-review, type:bug

#7127 Fixes skill_keep_using timer mismatch
  src/map/skill.cpp
Labels: status:code-review

#7151 Fixes a couple mob skill conditions
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#7176 Added training zone
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  npc/re/mapflag/nobranch.txt
  npc/re/mobs/towns.txt
  npc/re/mobs/tra_fild.txt
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/other/TrainingZone.txt
Labels: component:database, component:script, mode:renewal, status:code-review

#7179 cleanup a bit of cbasetypes
  src/common/cbasetypes.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#7150 Fixes Cart Cannon defense reduction
  src/map/battle.cpp
Labels: status:code-review

#7064 Fixed memory consumption of caches
  src/common/database.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7181 Fixed returned mails from deleted chars
  sql-files/upgrades/upgrade_20220818.sql
  src/char/char.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7126 Allow PK damage modifiers to affect flat damage
  src/map/battle.cpp
Labels: status:code-review

#7184 Initial release of reputation UI
  db/import-tmpl/reputation.yml
  db/re/reputation.yml
  db/reputation.yml
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map-server.vcxproj
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7193 Rockridge armor dealer fix
  npc/re/merchants/enchan_rockridge.txt
Labels: component:script, mode:renewal

#7180 Script command for enchantgrade
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  doc/atcommands.txt
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/script.cpp
Labels: component:core, component:documentation, mode:renewal, status:code-review

#7204 Updates github CI version for Ubuntu
  .github/workflows/build_servers_clang.yml
  .github/workflows/build_servers_cmake.yml
  .github/workflows/build_servers_gcc.yml
  .github/workflows/build_servers_modes.yml
  .github/workflows/build_servers_packetversions.yml
  .github/workflows/build_servers_vip.yml
  .github/workflows/npc_db_validation.yml
  src/common/core.cpp
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7185 Initial release of item reform UI
  db/import-tmpl/item_reform.yml
  db/item_reform.yml
  db/re/item_combos.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  db/re/item_reform.yml
  db/re/laphine_synthesis.yml
  db/re/laphine_upgrade.yml
  db/re/mob_db.yml
  doc/script_commands.txt
  npc/re/instances/GhostPalace.txt
  npc/re/merchants/ghost_palace_exchange.txt
  sql-files/item_db_re_equip.sql
  sql-files/item_db_re_etc.sql
  sql-files/mob_db_re.sql
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/packets.hpp
  src/map/pc.hpp
  src/map/script.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7206 Updated runserver.bat
  tools/runserver.bat
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7203 Fix Aspersio not removing scroll enchant
  db/pre-re/status.yml
Labels: component:database, mode:prerenewal, type:bug

#7211 Cleaned up status_change_end
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/guild.cpp
  src/map/homunculus.cpp
  src/map/map.cpp
  src/map/mercenary.cpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7212 Fixed some more SC_STONEWAIT issues
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7218 Added 'Gradable' in item DB
  db/import-tmpl/item_db.yml
  db/item_db.yml
  db/pre-re/item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  doc/item_db.txt
  doc/yaml/db/item_db.yml
  doc/yaml/sql/item_db2_re.sql
  doc/yaml/sql/item_db_re.sql
  sql-files/item_db2_re.sql
  sql-files/item_db_re.sql
  src/map/clif.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/tool/yaml2sql.cpp
Labels: component:database, component:core, mode:renewal, status:code-review

#7220 Added missing increase of ITEM_DB versioning
  db/import-tmpl/item_db.yml
  db/item_db.yml
  db/pre-re/item_db.yml
  db/pre-re/item_db_equip.yml
  db/pre-re/item_db_etc.yml
  db/pre-re/item_db_usable.yml
  db/re/item_db.yml
  db/re/item_db_equip.yml
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  src/map/itemdb.hpp
  src/tool/csv2yaml.cpp
  src/tool/yamlupgrade.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, type:enhancement

#7217 Better error message for YAML syntax errors
  src/common/database.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7210 Resolves spawn direction not saving at relog
  sql-files/main.sql
  sql-files/upgrades/upgrade_20220830.sql
  src/char/char.cpp
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: status:code-review

#7227 Suggestion getmonsterinfo update
  doc/script_commands.txt
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7222 laphine_synthesis script command update
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, status:code-review
