Repository rathena/rathena, pull requests merged in 2023-06, with the labels that each got.

#7792 Fixes Lux Anima applying Giant Growth
  src/map/skill.cpp
Labels: component:skill, priority:low, mode:renewal, status:code-review, type:bug

#7797 Fixes a party check for Weekend Dungeon
  npc/re/instances/WeekendDungeon.txt
Labels: status:code-review

#7796 Fixes Lux Anima status not applying
  src/map/skill.cpp
Labels: status:code-review

#7763 Added support for really big cashshops
  src/common/malloc.cpp
  src/common/malloc.hpp
  src/common/socket.cpp
  src/common/socket.hpp
  src/map/clif.cpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7805 Fix issue with bonus3 bAddEffOnSkill
  src/map/pc.cpp
Labels: status:confirmed, component:core, priority:low, status:code-review, type:bug

#7803 Added more information for atcommand refine
  conf/msg_conf/map_msg.conf
  doc/atcommands.txt
  src/map/atcommand.cpp
Labels: status:code-review

#7804 Atcommand setcard
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  doc/atcommands.txt
  src/map/atcommand.cpp
Labels: status:code-review

#7435 Resolves movable skill unit stack
  src/map/skill.cpp
Labels: status:code-review

#6959 Resolves an issue with RENEWAL_ASPD
  db/job_stats.yml
  db/pre-re/job_aspd.yml
  db/pre-re/job_stats.yml
  db/re/job_aspd.yml
  db/re/job_stats.yml
  src/common/database.cpp
Labels: status:code-review

#7813 Initial release of illusion investigation quests
  db/re/quest_db.yml
  npc/re/quests/illusion_investigation.txt
  npc/re/scripts_athena.conf
  npc/re/warps/cities/prontera.txt
Labels: component:database, component:script, mode:renewal, status:code-review

#7808 Adds option to set item buy/sell values to 0
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
  src/map/itemdb.cpp
  src/map/itemdb.hpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review

#7814 Update produce_db.txt
  db/pre-re/produce_db.txt
  db/re/produce_db.txt
Labels: component:database, mode:renewal

#7612 Convert guild_db to unordered_map
  src/char/int_guild.cpp
  src/char/int_guild.hpp
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battleground.cpp
  src/map/channel.cpp
  src/map/channel.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/instance.cpp
  src/map/intif.cpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/storage.cpp
Labels: component:core, priority:high, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7820 Card Album Update
  db/re/item_group_db.yml
Labels: component:database, mode:renewal

#7832 Fixed wrong index check in clif_parse_laphine_synthesis
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug
