Repository rathena/rathena, pull requests merged in 2023-11, with the labels that each got.

#7985 Implemented DK_DRAGONIC_BREATH
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, status:code-review

#7996 fixes RK_DRAGONBREATH/RK_DRAGONBREATH_WATER scaling with 4th job
  src/map/battle.cpp
Labels: component:skill, mode:renewal, status:code-review

#7781 Resolves players escaping jail early
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7972 Add has_autoloot script command
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, status:code-review, hacktoberfest-accepted

#8005 Implemented script command opentips
  doc/script_commands.txt
  src/map/clif.hpp
  src/map/script.cpp
Labels: status:code-review

#8011 Updated SC_*_LIFEPOTION and SC_S_MANAPOTION
  src/map/status.cpp
Labels: status:code-review

#8014 Updated Illusion dungeon exchange NPCs
  npc/re/merchants/barters/enchan_illusion_dungeons.yml
  npc/re/merchants/enchan_illusion_dungeons.txt
Labels: component:script, mode:renewal, status:code-review

#8016 Updated Old glast heim instance
  npc/re/instances/OldGlastHeim.txt
Labels: component:script, mode:renewal, status:code-review
