Repository rathena/rathena, pull requests merged in 2023-03, with the labels that each got.

#7640 Change copied bl type to BL_NUL for delayed clif_clearunit
  src/map/clif.cpp
Labels: component:core, priority:medium, status:code-review, type:bug

#7635 Implement NPC_GRADUAL_GRAVITY
  db/re/skill_db.yml
  db/re/status.yml
  src/common/mmo.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#7637 Implement NPC_ALL_STAT_DOWN
  db/re/skill_db.yml
  db/re/status.yml
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#7636 Implement NPC_MOVE_COORDINATE
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#7642 Implemented NPC_LEASH
  db/re/skill_db.yml
  src/common/mmo.hpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7643 Implemented NPC_WIDELEASH
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7624 Adds skill NPC_KILLING_AURA
  db/re/skill_db.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#7568 Add other player in mail transactions
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/buyingstore.cpp
  src/map/clif.cpp
  src/map/intif.cpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/mail.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/trade.cpp
  src/map/vending.cpp
Labels: component:core, priority:medium, status:code-review, type:enhancement

#7638 Implement NPC_DAMAGE_HEAL and NPC_IMMUNE_PROPERTY
  db/re/skill_db.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#7349 Added nif_dun quests
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/mobs/dungeons/nif_dun.txt
  npc/re/quests/quests_dungeons_200.txt
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/dungeons/nif_dun.txt
Labels: component:database, component:script, mode:renewal, status:code-review

#7648 Fix builds that don't use the memory manager
  src/common/strlib.cpp
  src/common/strlib.hpp
Labels: component:core, priority:high, status:code-review, type:bug

#7654 Added some entries in instance_db.yml
  db/re/instance_db.yml
Labels: component:database, mode:renewal, status:code-review

#7651 Deduplicate strlib code
  src/common/malloc.hpp
  src/common/strlib.cpp
  src/common/strlib.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7649 Fix ASAN crashes and LSAN leaks
  src/char/char_clif.cpp
  src/char/char_mapif.cpp
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7592 Fixes getrefine failing in OnEquip/OnUnequip scripts
  src/map/pc.cpp
  src/map/script.cpp
Labels: component:core, priority:medium, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7657 Fix memory leak on map quit
  src/map/chrif.cpp
Labels: component:core, status:code-review, type:bug

#7622 Added returning to instances
  conf/battle/feature.conf
  npc/mapflag/nosave.txt
  npc/pre-re/mapflag/nosave.txt
  npc/re/mapflag/nosave.txt
  sql-files/main.sql
  sql-files/upgrades/upgrade_20230224.sql
  src/char/char.cpp
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7652 Fixed an issue where normal NPC had no sprite when walking
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#7662 Small correction on the attribute table
  db/re/attr_fix.yml
Labels: component:database, mode:renewal, status:code-review

#7655 Removed NoForcedEnd for SC_MONSTER_TRANSFORM
  db/re/status.yml
Labels: component:database, mode:renewal, status:code-review

#7614 Implemented the skills NPC_RELIEVE_ON and NPC_RELIEVE_OFF
  db/re/skill_db.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:skill, mode:renewal, status:code-review
