Repository rathena/rathena, pull requests merged in 2023-04, with the labels that each got.

#7675 Implemented the skill: NPC_RAINOFMETEOR
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#7670 Fixes an issue with clones receiving 1 damage
  src/map/mob.cpp
Labels: status:code-review

#7683 Added new maps up to April 05 2023
  conf/maps_athena.conf
  db/map_cache.dat
  db/map_index.txt
Labels: component:database, mode:renewal, status:code-review

#7681 Updated achievement_db.yml
  db/re/achievement_db.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#7684 Updated unitskilluseid and unitskillusepos script commands
  doc/script_commands.txt
  src/map/script.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: status:code-review

#7677 Implemented NPC_GROUNDDRIVE
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: status:code-review

#7336 Added amicitia1 and amicitia2, dungeons level 200
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/mobs/dungeons/amicitia.txt
  npc/re/quests/quests_dungeons_200.txt
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/dungeons/amicitia.txt
Labels: component:database, component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#7676 Updates map_drops.yml
  db/import-tmpl/map_drops.yml
  db/map_drops.yml
  db/re/map_drops.yml
  src/common/random.cpp
  src/common/random.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/tool/yamlupgrade.cpp
Labels: status:code-review

#7465 Initial release of Illusion of Turtle
  db/re/item_randomopt_group.yml
  db/re/map_drops.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/merchants/enchan_illusion_16_2.txt
  npc/re/mobs/dungeons/tur_dun.txt
  npc/re/quests/quests_16_2_illusion.txt
Labels: component:script, mode:renewal, status:code-review

#7207 Added mag_dun03
  db/re/item_randomopt_group.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/mobs/dungeons/mag_dun.txt
  npc/re/quests/quests_exp_175.txt
  npc/re/scripts_warps.conf
  npc/re/warps/dungeons/mag_dun.txt
Labels: component:database, component:script, mode:renewal, status:inprogress

#7671 Updated disablenpc/enablenpc
  src/map/clif.cpp
  src/map/map.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#6923 NPC basic state
  doc/script_commands.txt
  src/map/npc.cpp
  src/map/npc.hpp
Labels: mode:renewal, mode:prerenewal, status:inprogress, type:enhancement

#7695 Fixed an issue with npc_enable_target
  src/map/npc.cpp
Labels: status:code-review

#7298 Episode 16.1 - Edda Half Moon In The Daylight
  npc/re/instances/EddaHalfMoonInTheDaylight.txt
  npc/re/merchants/enchan_edda_half_moon.txt
  npc/re/other/global_npcs.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#7300 Episode 16.2 - Friday Memorial Dungeon
  npc/re/instances/FridayDungeon.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, hacktoberfest-accepted

#7559 Initial release of Illusion of Luanda
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/merchants/enchan_illusion_16_2.txt
  npc/re/mobs/dungeons/beach_dun.txt
  npc/re/quests/quests_16_2_illusion.txt
  src/map/script.cpp
Labels: component:database, component:script, mode:renewal, status:code-review

#7521 Initial release of Illusion of underwater
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/merchants/barters.yml
  npc/re/merchants/barters/enchan_illusion_16_2.yml
  npc/re/merchants/enchan_illusion_16_2.txt
  npc/re/mobs/dungeons/iz_dun.txt
  npc/re/quests/quests_16_2_illusion.txt
Labels: component:database, component:script, mode:renewal, status:code-review

#6799 Episode 17.2 - Sage's Legacy
  db/re/item_db_usable.yml
  db/re/item_randomopt_group.yml
  db/re/laphine_upgrade.yml
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/pet_db.yml
  db/re/quest_db.yml
  doc/item_bonus.txt
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
  npc/re/instances/HiddenGarden.txt
  npc/re/instances/LostFarm.txt
  npc/re/instances/TwilightGarden.txt
  npc/re/instances/WaterGarden.txt
  npc/re/merchants/barters.yml
  npc/re/merchants/barters/quests_17_2.yml
  npc/re/merchants/enchan_sage_legacy_17_2.txt
  npc/re/mobs/dungeons/ba_2whs.txt
  npc/re/mobs/dungeons/ba_bath.txt
  npc/re/mobs/dungeons/ba_lib.txt
  npc/re/mobs/dungeons/ba_pw.txt
  npc/re/mobs/fields/ba_lost.txt
  npc/re/mobs/fields/ba_maison.txt
  npc/re/other/Global_Functions.txt
  npc/re/quests/quests_17_1.txt
  npc/re/quests/quests_17_2.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_monsters.conf
  npc/re/scripts_warps.conf
  npc/re/warps/cities/prontera.txt
  npc/re/warps/other/ba_2whs.txt
  npc/re/warps/other/ba_maison.txt
  npc/re/warps/other/ba_pw.txt
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  sql-files/upgrades/upgrade_20220407.sql
  src/map/map.hpp
  src/map/mob.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: component:database, component:core, component:script, mode:renewal, status:code-review

#7702 Do not call pet_set_intimate twice
  src/map/pc.cpp
  src/map/pet.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:enhancement

#7714 4th Improvement - Dragon Knight
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7713 4th Improvement - Imperial Guard
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7712 4th Improvement - Meister
  db/re/skill_db.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7711 4th Improvement - Biolo
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7710 4th Improvement - Shadow Cross
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/unit.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7709 4th Improvement - Abyss Chaser
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7708 4th Improvement - Arch Mage
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7707 4th Improvement - Elemental Master
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7706 4th Improvement - Cardinal
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7705 4th Improvement - Inquisitor
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7704 4th Improvement - Wind Hawk
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7703 4th Improvement - Troubadour & Trouvere
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7715 Fixed an issue with cloaknpc
  src/map/pc.cpp
Labels: status:code-review

#7717 Corrected animation of the skill SHC_SAVAGE_IMPACT
  src/map/skill.cpp
Labels: status:code-review

#7701 Add debug logs for debugging client connections
  src/char/char_clif.cpp
  src/login/loginclif.cpp
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:enhancement

#7719 Fixes the pincode system
  src/char/char.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7729 Prevent an uint underflow and reformat array_size occurences in some commands
  src/map/script.cpp
Labels: status:confirmed, component:core, priority:medium, status:code-review, type:bug

#7735 Fixed an issue for map_drops.yml
  src/map/mob.cpp
Labels: status:code-review
