Repository rathena/rathena, pull requests merged in 2023-01, with the labels that each got.

#7513 Enabled conformance mode in MSVS
  src/char/char-server.vcxproj
  src/common/common-minicore.vcxproj
  src/common/common.vcxproj
  src/login/login-server.vcxproj
  src/map/map-server-generator.vcxproj
  src/map/map-server.vcxproj
  src/tool/csv2yaml.vcxproj
  src/tool/mapcache.vcxproj
  src/tool/yaml2sql.vcxproj
  src/tool/yamlupgrade.vcxproj
  src/web/web-server.vcxproj
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7517 Small doc update
  doc/script_commands.txt
Labels: component:documentation, mode:renewal, mode:prerenewal, status:code-review

#7523 Adds char_server config for clearing parties
  conf/char_athena.conf
  src/char/char.cpp
  src/char/char.hpp
  src/char/int_party.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6430 Prevent opening vending UI multiple times
  src/map/clif.cpp
  src/map/intif.cpp
  src/map/pc.hpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7525 Added support for new maps
  conf/maps_athena.conf
  db/map_cache.dat
  db/map_index.txt
Labels: component:database, mode:renewal, status:code-review

#7526 Add extra validation checks for map coordinates
  src/common/mmo.hpp
  src/map/battleground.cpp
  src/map/battleground.hpp
  src/map/instance.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6299 Converted cash shop database to YAML
  conf/inter_athena.conf
  db/import-tmpl/item_cash.yml
  db/import-tmpl/item_cash_db.txt
  db/item_cash.yml
  db/pre-re/item_cash_db.txt
  db/re/item_cash_db.txt
  doc/yaml/db/item_cash.yml
  sql-files/README.md
  sql-files/item_cash_db.sql
  sql-files/item_cash_db2.sql
  src/common/mmo.hpp
  src/map/cashshop.cpp
  src/map/cashshop.hpp
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/map-server.vcxproj
  src/map/map.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/tool/csv2yaml.cpp
  src/tool/csv2yaml.hpp
  src/tool/yaml.hpp
  src/tool/yaml2sql.cpp
  tools/ci/sql.bat
  tools/ci/sql.sh
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#6285 Added new guild UI features
  db/castle_db.yml
  db/import-tmpl/castle_db.yml
  db/pre-re/castle_db.yml
  db/re/castle_db.yml
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/script_constants.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#7530 Added reloadbarterdb
  conf/msg_conf/map_msg.conf
  doc/atcommands.txt
  src/map/atcommand.cpp
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7514 Replaced DBMap usage in char-server
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_auction.cpp
  src/char/int_clan.cpp
  src/char/int_guild.cpp
  src/char/int_mail.cpp
  src/char/int_party.cpp
  src/char/inter.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7539 Fixed online_char_db
  src/char/char.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7544 Fixs cash shop database import
  src/map/map-server-generator.vcxproj
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#7533 Removed mapindex from char-server
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_party.cpp
  src/char/inter.cpp
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/battleground.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/instance.cpp
  src/map/intif.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#7547 Fixes instances with infinite duration
  src/map/instance.cpp
  src/map/instance.hpp
Labels: status:code-review

#7546 Added support for map selection
  src/char/char_clif.cpp
  src/char/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7545 fix NPC_EARTHQUAKE from R001_BESTIA
  db/re/mob_skill_db.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#7488 Added missing NPCs in rgsr_in
  db/re/item_db_usable.yml
  db/re/item_randomopt_group.yml
  db/re/item_reform.yml
  db/re/mob_db.yml
  npc/re/merchants/barters.yml
  npc/re/merchants/barters/rgsr_in.yml
  npc/re/merchants/rgsr_in.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review

#7553 Added more missing items
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal

#7551 Corrected the logic for Juno quest in ve_fild04
  db/re/quest_db.yml
  npc/re/quests/juno_monster_society.txt
Labels: component:database, component:script, mode:renewal, status:code-review

#7532 Improved itemlink logic
  conf/battle/feature.conf
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chn.conf
  conf/msg_conf/map_msg_frn.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_rus.conf
  conf/msg_conf/map_msg_spn.conf
  conf/msg_conf/map_msg_tha.conf
  src/map/atcommand.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#7552 Implemented missing skills
  db/re/skill_db.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: component:database, component:core, mode:renewal, status:code-review
