Repository rathena/rathena, pull requests merged in 2024-11, with the labels that each got.

#8752 Move the Inn NPC from Einbroch to inn.txt
  npc/cities/einbroch.txt
  npc/merchants/inn.txt
Labels: component:script, mode:renewal, mode:prerenewal

#8780 Corrects sql syntax error in script
  sql-files/upgrades/upgrade_20241026.sql
Labels: component:database, mode:renewal, mode:prerenewal, type:bug

#8777 Corrected SC_GROUNDGRAVITY ratio
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8737 Follow up to c683520
  src/map/clif.cpp
  src/map/guild.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8775 Corrected Matk status calculation
  db/pre-re/status.yml
  db/re/status.yml
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review

#8724 Implemented packet PACKET_ZC_GUILD_POSITION
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8701 Fixed a warning in clif.cpp
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8664 Implemented new Shadow Cross skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8783 Fixed TICK_CACHE support
  src/common/timer.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8594 Converted ZC_ADD_SKILL to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/pc.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8778 Monster behavior when hiding
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#8770 Fix cast time for MO_FINGEROFFENSIVE in RENEWAL mode
  src/map/unit.cpp
Labels: component:core, mode:renewal, type:bug

#8662 Implemented new Meister skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8661 Implemented new Imperial Guard skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#8686 Remove spawn info when unloading npc files
  src/map/map.hpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/npc.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8788 Converted ZC_MEMBER_NEWENTRY to struct
  src/map/chat.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8790 Converted ZC_MEMBER_EXIT to struct
  src/map/chat.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8791 Small cleanup to clif_getareachar_item
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8792 Converted CZ_MOVETO_MAP to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8793 Converted CZ_BROADCAST to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8794 Converted CZ_REQ_WEAR_EQUIP to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8795 Converted CZ_CONTACTNPC to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8796 Converted CZ_ACK_SELECT_DEALTYPE to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8797 Converted CZ_CREATE_CHATROOM to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8786 Added script support to status changes
  db/import-tmpl/status.yml
  db/pre-re/status.yml
  db/re/status.yml
  db/status.yml
  doc/status.txt
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8785 Corrected magic damage with SC_MAGIC_POISON debuff (comet debuff)
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8800 Star Gladiator Heat Official Behavior
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#8803 Corrected SC_CLIMAX_BLOOM and SC_CLIMAX_EARTH
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8789 Converted ZC_ROLE_CHANGE to struct
  src/map/chat.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8807 Fixed a wrong check in the monk quest
  npc/jobs/2-2/monk.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8806 Fixed some wrong Zeny checks
  npc/quests/gunslinger_quests.txt
  npc/quests/quests_yuno.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8663 Implemented new Biolo skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  db/re/status.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.hpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8808 Fixed mapflag pvp_nightmaredrop
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8810 Fixed exorcism chance of Amatsu quest
  npc/quests/quests_amatsu.txt
Labels: component:script, mode:renewal, mode:prerenewal

#8813 Corrected SC_MISTYFROST
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8817 War Badge mistype
  db/pre-re/item_db_etc.yml
  db/re/item_db_etc.yml
  sql-files/item_db_etc.sql
  sql-files/item_db_re_etc.sql
Labels: component:database, mode:renewal, mode:prerenewal, type:bug

#8814 Corrected high wizard and warlock skills (renewal)
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8811 Dehardcoded status change
  db/pre-re/item_db_usable.yml
  db/pre-re/status.yml
  db/re/item_db_usable.yml
  db/re/status.yml
  npc/re/instances/CorOperation.txt
  npc/re/instances/OldGlastHeim.txt
  src/map/battle.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review

#8782 Updated RDTSC support
  src/common/timer.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8805 Converted all ranking packets to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8830 Added status_change::empty
  src/map/battle.cpp
  src/map/battleground.cpp
  src/map/clif.cpp
  src/map/elemental.cpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8829 Removed RFIFOHEAD macro
  src/char/int_clan.cpp
  src/char/int_guild.cpp
  src/char/int_party.cpp
  src/char/int_pet.cpp
  src/char/int_storage.cpp
  src/common/socket.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8828 Removed some old deprecated constant
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8833 Corrected damage climax buffs and bSkillatk
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8820 Converted CZ_LESSEFFECT to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8821 Converted CZ_ACTIVE_QUEST to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8822 Converted CZ_JOIN_BABY to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8823 Converted CZ_AUCTION_ITEM_SEARCH to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8836 Corrected calculation that ignores mdef
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review

#8831 Dehardcoded status change
  db/pre-re/status.yml
  db/re/item_db_usable.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/pc.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review

#8825 Converted CZ_AUCTION_ADD to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8838 Implemented missing status change
  db/re/item_db_usable.yml
  db/re/status.yml
  src/map/script_constants.hpp
  src/map/status.hpp
Labels: component:database, mode:renewal, status:code-review

#8845 Fixes cash foods effect
  db/pre-re/status.yml
Labels: component:database, mode:prerenewal, status:code-review, type:bug

#8850 Corrected WZ_FROSTNOVA and SC_WHITEIMPRISON
  src/map/battle.cpp
Labels: component:skill, mode:renewal, status:code-review
