Repository rathena/rathena, pull requests merged in 2024-07, with the labels that each got.

#8487 Fixed NoNearNPC flag
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8483 Refactored get/set unitdata
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8486 Fixed packets 0x440 and 0x8cf
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/pc.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8473 Reverting Magic Wand Quest to request Trunks
  npc/re/quests/eden/56-70.txt
Labels: component:script, mode:renewal

#8493 Clear start_items when reading a new value
  src/char/char.cpp
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8491 Fixed searchstores incorrectly updating uses
  src/map/clif.cpp
  src/map/script.cpp
  src/map/searchstore.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8469 Fixed vending_over_max behavior to match official
  conf/battle/items.conf
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/vending.cpp
Labels: status:code-review

#8479 Monster Losing Target Display
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: component:core, mode:renewal, mode:prerenewal

#8496 Fix stack overflow in npc_parse_shop
  src/map/npc.cpp
Labels: component:core, priority:medium, status:code-review, type:bug

#8501 Resolve Death Valley HP/SP adjustment
  src/map/skill.cpp
Labels: component:skill, mode:renewal, status:code-review

#8503 Fixed custom warper var
  npc/custom/warper.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8504 Updated Old Glast Heim instance
  npc/re/instances/OldGlastHeim.txt
Labels: component:script, mode:renewal, status:code-review

#8509 Corrected pet_db.yml script
  db/re/pet_db.yml
Labels: component:database, mode:renewal, status:code-review

#8517 Removed Gunslinger Mine Damage Delay
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#8508 Fixed homunculus cooldown and aftercast delays
  conf/battle/homunc.conf
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/homunculus.cpp
  src/map/homunculus.hpp
  src/map/pc.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8513 Fixed Homunculus Lif skills
  db/pre-re/skill_db.yml
  db/pre-re/status.yml
  db/re/skill_db.yml
  db/re/status.yml
  doc/status.txt
  doc/status_change.txt
  src/map/clif.cpp
  src/map/homunculus.cpp
  src/map/pc.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, component:skill, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8528 Fixed Slow Potion effect on pre-re
  db/pre-re/item_db_usable.yml
Labels: component:database, mode:prerenewal, status:code-review, type:bug
