Repository rathena/rathena, pull requests merged in 2024-10, with the labels that each got.

#8696 Corrected 12462/12463/12464/12465 item scripts (SC_ already implemented)
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#8699 Moved pc_skillatk_bonus after mdef reduction (renewal)
  src/map/battle.cpp
Labels: component:core, mode:renewal, status:code-review

#8697 openstorage2 script command update
  doc/script_commands.txt
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8700 Cleanup CLI config parsing
  src/char/char.cpp
  src/common/cli.cpp
  src/common/cli.hpp
  src/common/sql.cpp
  src/login/login.cpp
  src/login/login.hpp
  src/login/logincnslif.cpp
  src/login/logincnslif.hpp
  src/map/map.cpp
Labels: status:code-review

#8708 Fix Disable Call for some skills
  src/map/skill.cpp
Labels: component:core, mode:renewal, status:code-review

#8703 Added a check for undefined weapontypes
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8710 Added missing check for pc_skillatk_bonus
  src/map/battle.cpp
Labels: component:core, mode:renewal

#8706 Corrected Matk status calculation
  src/map/status.cpp
Labels: component:core, mode:renewal, status:code-review

#8538 Implemented missing ZC_HO_PAR_CHANGE packet
  sql-files/main.sql
  sql-files/upgrades/upgrade_20241005.sql
  src/char/int_homun.cpp
  src/common/mmo.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/homunculus.cpp
  src/map/homunculus.hpp
  src/map/packets.hpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug, hacktoberfest-accepted

#8714 Fixed magic damage with SC_TELEKINESIS_INTENSE buff
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8719 Correct Lucky Roulette Ticket
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#8721 Correct a map crash from slaves_inherit_mode
  src/map/mob.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8725 Fixed guild name not showing on login
  src/map/guild.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8728 Converted Buche De Noel bonus_script to SC_BUCHEDENOEL
  db/re/item_db_usable.yml
  db/re/status.yml
  doc/status_change.txt
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, mode:renewal, status:code-review

#8723 Fix battle_attr_fix logic for ele level
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8731 Initial release of 20th Event Anniversary Skill
  db/re/item_db_etc.yml
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal

#8715 Add missing knockback values for SR_KNUCKLEARROW
  db/re/skill_db.yml
Labels: status:code-review

#8735 Converted Amplification Scroll and Intellect Amplification Scroll bonus_script to SC_STR_SCROLL and SC_INT_SCROLL
  db/re/item_db_usable.yml
  db/re/status.yml
  doc/status_change.txt
  src/map/script_constants.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, mode:renewal, status:code-review

#8740 Updating PACKET_ZC_PAR_CHANGE_USER
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8727 Corrected renewal battle_calc_cardfix (magic)
  src/map/battle.cpp
Labels: component:core, mode:renewal, status:code-review

#8711 Party Name Should Be Displayed
  conf/battle/party.conf
Labels: mode:renewal

#8747 Fixed Hyper Novice skills formula
  db/re/job_stats.yml
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8754 Corrected SP_CURSEEXPLOSION and Soulcurse status
  db/re/status.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8756 Fixed Yorscalp combos
  db/re/item_combos.yml
Labels: component:database, mode:renewal, status:code-review

#8760 Corrected Doram skills
  db/pre-re/status.yml
  db/re/status.yml
  src/map/status.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8763 Renewal Element on Mild Wind and Guillotine Fist
  src/map/battle.cpp
Labels: component:core, mode:renewal
