Repository rathena/rathena, pull requests merged in 2024-05, with the labels that each got.

#8292 Moved battle_fix_damage definition to battle.cpp
  src/map/battle.cpp
  src/map/battle.hpp
Labels: component:tool, mode:renewal, mode:prerenewal, type:bug

#8258 Script correction of Lux Anima Runestone IDs 22540
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#8254 Cleaned up a few TODOs from #7963
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/elemental.cpp
  src/map/elemental.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/mob.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/unit.cpp
  src/map/vending.cpp
  src/map/vending.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8281 Small optimization on change sex
  src/char/char_logif.cpp
Labels: status:code-review, type:maintenance

#8296 Cleaned up 2 size_t warnings in char.cpp
  src/char/char.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8294 Fixed clif type conversion warnings
  src/map/battleground.cpp
  src/map/battleground.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/party.cpp
  src/map/party.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8299 Fix auto spell list on renewal
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8297 Converted some banking packets to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8275 Script correction of NPC ammo_boxes
  npc/re/merchants/ammo_boxes.txt
Labels: component:script, mode:renewal, status:code-review, type:bug

#8308 Fixed clif_wis_message
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8288 Fixed SHC_SHADOW_STAB damage bonus
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, type:bug

#8147 Resolves a potential crash from Howling Mine
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:skill, priority:low, mode:renewal, status:code-review

#3257 Added a command to reload cash shop db
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  src/map/atcommand.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8316 Monster Powerskill Levels, Silver Sniper, Magic Decoy
  db/pre-re/mob_db.yml
  db/pre-re/mob_skill_db.txt
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  doc/mob_skill_db_powerskill.txt
Labels: component:database, mode:renewal, mode:prerenewal, type:bug

#8318 Added missing columns for yaml2sql
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
Labels: component:tool, mode:renewal, mode:prerenewal, type:bug

#8295 Converted a bunch of packets to structs
  src/map/atcommand.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/homunculus.cpp
  src/map/mail.cpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/storage.cpp
  src/map/trade.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8330 Fixed clif_sendfakenpc
  src/map/clif.cpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8320 Small cleanup to NJ_ZENYNAGE
  src/map/battle.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8329 Fixed plagiarized skill not removed
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8286 Fix unlimited use of potion.
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#8336 Fix Boss Meow not having boss class in db/re/mob_db.yml
  db/re/mob_db.yml
Labels: component:database, mode:renewal

#8338 Update build_servers_gcc.yml
  .github/workflows/build_servers_gcc.yml
Labels: component:tool, mode:renewal, mode:prerenewal, type:bug

#7978 Fix slavemob bahavior
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, type:bug

#8324 Spawn and Free Cell Search Behavior
  conf/battle/misc.conf
  conf/battle/monster.conf
  doc/script_commands.txt
  npc/re/mobs/championmobs.txt
  npc/re/mobs/fields/prontera.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8332 Converted some packets to structs
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/homunculus.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8351 Converted some packets to structs
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/chat.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/storage.cpp
  src/map/trade.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8357 Missing nodynamicnpc on mapflag
  npc/re/scripts_mapflags.conf
  npc/scripts_mapflags.conf
Labels: component:script, mode:renewal, mode:prerenewal, type:bug

#8305 Synchronize Damage Feature
  conf/battle/battle.conf
  db/import-tmpl/mob_db.yml
  db/mob_db.yml
  db/pre-re/mob_db.yml
  db/re/mob_db.yml
  doc/mob_db.txt
  doc/yaml/db/mob_db.yml
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, type:bug

#8353 Converted some packets to structs
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/intif.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/skill.cpp
  src/map/storage.cpp
  src/map/unit.cpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8361 Replaced custom with official message names
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/pc.cpp
  src/map/trade.cpp
Labels: status:inprogress, type:maintenance

#8367 New pcblock flag PCBLOCK_EQUIP
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/script.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:enhancement

#8368 Updated Hercules packets
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8371 Fixed clif_clearchar_skillunit
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8385 Removed whitespace & duplicate label in runserver.bat
  tools/check-doc.pl
  tools/config.pl
  tools/convert_emotions.py
  tools/convert_monstermode.pl
  tools/convert_sql.pl
  tools/runserver.bat
  tools/stackdump
  tools/update.pl
Labels: component:tool

#8386 Arch Mage, S.MATK, Warlock Summon/Release
  db/re/job_stats.yml
  src/map/battle.cpp
Labels: component:database, component:core, mode:renewal, type:bug

#8383 Illusion of underwater fix
  npc/re/quests/quests_illusion_dungeons.txt
Labels: component:script, mode:renewal

#8369 Generic cleanup of packets
  src/char/char_clif.cpp
  src/login/loginclif.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/npc.cpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug, type:maintenance
