Repository rathena/rathena, pull requests merged in 2024-12, with the labels that each got.

#8860 Fixed NPC_SELFDESTRUCTION not giving items and exp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, status:code-review

#8857 Turned SqlStmt into a C++ class
  src/char/CMakeLists.txt
  src/char/char-server.vcxproj
  src/char/char.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_achievement.cpp
  src/char/int_auction.cpp
  src/char/int_homun.cpp
  src/char/int_mail.cpp
  src/char/int_quest.cpp
  src/char/int_storage.cpp
  src/common/sql.cpp
  src/common/sql.hpp
  src/login/CMakeLists.txt
  src/login/account.cpp
  src/login/login-server.vcxproj
  src/map/CMakeLists.txt
  src/map/log.cpp
  src/map/map-server-generator.vcxproj
  src/map/map-server.vcxproj
  src/map/map.hpp
  src/map/mapreg.cpp
  src/map/npc.cpp
  src/map/storage.cpp
  src/web/CMakeLists.txt
  src/web/auth.cpp
  src/web/charconfig_controller.cpp
  src/web/emblem_controller.cpp
  src/web/merchantstore_controller.cpp
  src/web/partybooking_controller.cpp
  src/web/userconfig_controller.cpp
  src/web/web-server.vcxproj
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8856 Converted possible value of lr_flag to enum
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8863 Fixed a crash in script command summon
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8865 Corrected SC_INFINITY_DRINK, SC_MTF_MHP and SC_MTF_MSP sc bonus
  db/re/item_db_usable.yml
  db/re/status.yml
Labels: component:database, mode:renewal, status:code-review

#8864 Fixed stockall counter
  src/map/atcommand.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8841 Fixed Giant Fly Wing
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8826 Improved pet command and fixed Green Maiden
  db/pre-re/item_db_usable.yml
  db/pre-re/pet_db.yml
  db/re/item_db_usable.yml
  db/re/pet_db.yml
  doc/script_commands.txt
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review

#8866 Corrected WL_CHAINLIGHTNING_ATK behaviour
  src/map/skill.cpp
Labels: component:skill, mode:renewal, status:code-review

#8837 Converted ZC_DRESSROOM_OPEN to struct
  doc/script_commands.txt
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8809 Item Script for forgotten area 1 and 2 Crystal
  db/re/item_db_usable.yml
  npc/re/mapflag/noteleport.txt
Labels: component:database, mode:renewal, status:code-review, type:bug

#8827 Add cooldown saving for homunculus and mercenary
  conf/inter_athena.conf
  sql-files/main.sql
  sql-files/upgrades/upgrade_20241216.sql
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_mapif.cpp
  src/char/int_homun.cpp
  src/char/int_mercenary.cpp
  src/common/mmo.hpp
  src/common/utilities.hpp
  src/map/atcommand.cpp
  src/map/chrif.cpp
  src/map/chrif.hpp
  src/map/guild.cpp
  src/map/homunculus.cpp
  src/map/homunculus.hpp
  src/map/mercenary.cpp
  src/map/mercenary.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8718 Converted ZC_ROOM_NEWENTRY to struct
  src/map/chat.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8849 Algorithm for opening group items in renewal
  db/import-tmpl/item_group_db.yml
  db/item_group_db.yml
  db/pre-re/item_db_usable.yml
  db/pre-re/item_group_db.yml
  db/re/item_group_db.yml
  doc/item_group.txt
  doc/script_commands.txt
  doc/yaml/db/item_group_db.yml
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/mob.cpp
  src/map/script_constants.hpp
  src/tool/csv2yaml.cpp
  src/tool/yamlupgrade.cpp
Labels: component:database, component:core, component:documentation, mode:renewal

#8745 Fix Alberta Ship Warp Coordinates
  npc/cities/amatsu.txt
  npc/cities/ayothaya.txt
  npc/cities/brasilis.txt
  npc/cities/gonryun.txt
  npc/cities/louyang.txt
  npc/cities/moscovia.txt
  npc/re/cities/dewata.txt
  npc/re/cities/malaya.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8883 Updated Whip size fix
  db/pre-re/size_fix.yml
  db/re/size_fix.yml
  db/size_fix.yml
Labels: component:database, mode:renewal, status:code-review

#8876 Added a multi project launch profile for MSVS
  .gitignore
  rAthena.slnLaunch
Labels: component:tool, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8884 Updated accessible maps and coordinates
  src/char/char_clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8680 Cleanup duplicate Baby class stats
  db/pre-re/job_stats.yml
  db/re/job_stats.yml
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8880 Improved Monster Search and Summon
  src/common/utilities.cpp
  src/common/utilities.hpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#6822 Added the forgotten Laphine Log SQL
  sql-files/upgrades/upgrade_20220222_logs.sql
Labels: component:database, mode:renewal, mode:prerenewal, type:bug

#8891 Added MapDrops of Horror Toy Factory
  db/re/map_drops.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#8892 Fixed atcommand use in playerless scripts
  npc/test/ci/8886.txt
  src/map/log.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8893 status_get_name to reference
  src/map/clif.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8895 Monster Damage Log Improvements
  src/map/map.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#8894 Removed player damage log
  src/map/clif.cpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pc.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8898 Fixed pre-re items using bAtkRate bonus
  db/pre-re/item_db_equip.yml
Labels: component:database, mode:prerenewal

#8900 Report an error on bAtkRate in Pre-Renewal
  src/map/pc.cpp
Labels: component:core, mode:prerenewal, status:code-review, type:enhancement

#8162 Initial implementation of Soul Ascetic
  db/re/skill_db.yml
  db/re/skill_tree.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/clif.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#8904 Corrected SU_TUNAPARTY
  src/map/status.cpp
Labels: component:skill, mode:renewal, status:code-review

#8905 Corrected SC_FRESHSHRIMP
  src/map/status.cpp
Labels: component:skill, mode:renewal, status:code-review

#8903 Added skill ALL_NIFLHEIM_RECALL
  db/re/skill_db.yml
  db/re/status.yml
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug
