Repository rathena/rathena, pull requests merged in 2024-03, with the labels that each got.

#8157 Corrected DK_SERVANTWEAPON_ATK formula
  src/map/battle.cpp
Labels: component:skill, mode:renewal, status:code-review

#8150 Initial implementation of Night Watch
  db/re/skill_db.yml
  db/re/skill_tree.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#8152 Update SU_LUNATICCARROTBEAT formula
  src/map/battle.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#8161 Rebalance Night Watch 2022-12-21
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8156 Rebalance Hyper Novice 2024-02-05
  src/map/battle.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8154 Rebalance Elemental Master 2024-02-05
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8153 Rebalance Abyss Chaser 2024-02-05
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#8164 Rebalance Night Watch 2024-02-05
  db/re/skill_db.yml
  db/re/status.yml
Labels: component:database, component:skill, mode:renewal, status:code-review

#8167 Updated NPCs list and mobs list according to KRO client
  db/re/mob_db.yml
  src/map/npc.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review

#8179 Item DB corrections
  db/re/item_db_etc.yml
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal, status:code-review

#8182 Implemented the permission "TRADE_UNCONDITIONAL"
  conf/groups.yml
  doc/permissions.txt
  src/map/pc.cpp
  src/map/pc_groups.hpp
Labels: mode:renewal, mode:prerenewal, status:code-review

#8116 Extended TimeLimit format (quest DB)
  doc/quest_db.txt
  src/map/quest.cpp
  src/map/quest.hpp
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review

#8207 Updated renewal item group DB
  db/re/item_db_usable.yml
  db/re/item_group_db.yml
  src/map/itemdb.hpp
  src/map/script_constants.hpp
Labels: component:database, mode:renewal, status:code-review
