Repository rathena/rathena, pull requests merged in 2024-01, with the labels that each got.

#8073 Make the global packet_buffer owned by common
  src/common/socket.cpp
  src/common/socket.hpp
Labels: component:core, status:code-review, type:bug

#8078 Rebalance Imperial Guard 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8068 Rebalance Troubadour & Trouvere 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8077 Rebalance Dragon Knight 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8076 Rebalance Meister 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8084 Fixed convex mirror
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8081 Rebalance Abyss chaser 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8092 Updated hidden garden instance
  npc/re/instances/HiddenGarden.txt
Labels: component:script, mode:renewal, status:code-review

#8094 Cleanup of PATK calculation
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8096 Corrected CD_ARBITRIUM_ATK area of damage
  db/re/skill_db.yml
Labels: component:database, component:skill, mode:renewal, status:code-review

#8095 Corrected IG_GRAND_JUDGEMENT
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#8097 Some bonus ignored left_cardfix_to_right
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8102 Fixed RK_WINDCUTTER not ignoring def
  src/map/battle.cpp
Labels: component:core, mode:renewal, status:code-review, type:bug

#8099 Corrected boss spawn in lhz_dun_n
  npc/re/mobs/dungeons/lhz_dun_n.txt
Labels: component:script, mode:renewal, status:code-review

#8103 Update renewal Base exp and Job exp
  db/re/job_exp.yml
Labels: component:database, mode:renewal, status:code-review

#8107 Fixed some memleaks
  src/map/itemdb.cpp
  src/map/npc.cpp
  src/map/script.cpp
  src/map/script.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8101 Initial implementation of Hyper Novice
  db/re/skill_db.yml
  db/re/skill_tree.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#8108 Updated to Level 260/55
  db/pre-re/statpoint.yml
  db/re/job_basepoints.yml
  db/re/job_exp.yml
  db/re/job_stats.yml
  db/re/statpoint.yml
  src/map/map.hpp
Labels: component:database, mode:renewal, status:code-review

#7854 Added illusion Merchant
  npc/re/merchants/barters/enchan_illusion_dungeons.yml
  npc/re/merchants/enchan_illusion_dungeons.txt
Labels: component:script, mode:renewal

#8111 Rebalance Hyper Novice 20221221
  db/re/skill_db.yml
  src/map/battle.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#8075 Corrected Shrink Stuns target
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#7930 Added null pointer checks in map_delblock
  src/map/map.cpp
Labels: mode:renewal, mode:prerenewal, status:code-review
