Repository rathena/rathena, pull requests merged in 2024-06, with the labels that each got.

#8397 Fixed Random Spawns
  src/map/npc.cpp
Labels: component:core

#8370 Changed droplists from ERI to STL
  src/map/map.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/pet.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8391 Fixed all warnings in MSVS
  .github/workflows/build_servers_gcc.yml
  .github/workflows/build_servers_msbuild.yml
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_achievement.cpp
  src/char/int_clan.cpp
  src/char/int_guild.cpp
  src/char/int_quest.cpp
  src/char/inter.cpp
  src/common/grfio.cpp
  src/common/grfio.hpp
  src/login/account.cpp
  src/map/atcommand.cpp
  src/map/battleground.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/instance.cpp
  src/map/instance.hpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/map.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/unit.cpp
  src/tool/csv2yaml.cpp
  src/tool/mapcache.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8399 Fixed PCBLOCK_EQUIP
  src/map/pc.hpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8402 Added missing conformance mode in MSVS
  src/char/char-server.vcxproj
  src/common/common-minicore.vcxproj
  src/common/common.vcxproj
  src/login/login-server.vcxproj
  src/map/map-server-generator.vcxproj
  src/map/map-server.vcxproj
  src/tool/csv2yaml.vcxproj
  src/tool/mapcache.vcxproj
  src/tool/yaml2sql.vcxproj
  src/tool/yamlupgrade.vcxproj
  src/web/web-server.vcxproj
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8403 Triple Attack vs. Plant Mode
  src/map/battle.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#8411 Renewal Spiral Pierce, Element vs. Status Attack
  src/map/battle.cpp
Labels: status:confirmed, component:skill, mode:renewal

#8265 Fix dynamic npc timer mismatch
  src/map/buyingstore.cpp
  src/map/mob.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8404 Added sanity checks to pincode decryption
  src/char/char.cpp
  src/char/char.hpp
  src/char/char_clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8360 Fixed potentially dangerous map_addflooritem calls and related behaviors
  conf/battle/items.conf
  conf/battle/pet.conf
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_idn.conf
  conf/msg_conf/map_msg_por.conf
  conf/msg_conf/map_msg_spn.conf
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8405 Fixed clif_move to use the correct movement packets
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/mob.cpp
  src/map/packets.hpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/status.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8412 Added pincode state tracking
  src/char/char.hpp
  src/char/char_clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8416 Preparatory cleanup of clans
  src/map/clan.cpp
  src/map/clan.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/instance.cpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/map.cpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8417 Preparatory cleanup of guilds
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/intif.cpp
  src/map/intif.hpp
  src/map/packets.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8418 Preparatory cleanup of parties
  src/common/mmo.hpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8415 Cannon Ball Skills (P.ATK and Res)
  src/map/battle.cpp
Labels: status:confirmed, component:skill, mode:renewal

#3753 Added configs for instance limitations
  conf/battle/instance.conf
  conf/battle_athena.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clan.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/party.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#6429 Always set all item data in npc_sellist_sub
  src/map/npc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#8429 Renewal Simple Defense Formula Flag
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/battle.cpp
  src/map/script_constants.hpp
  src/map/skill.hpp
Labels: component:database, status:confirmed, component:core, component:skill, mode:renewal

#8354 Updated npcspeed, npcwalkto and npcstop script commands
  doc/script_commands.txt
  src/common/mmo.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8439 Updated setunitdata UMOB_MODE
  src/map/mob.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8440 Added 4th jobs to ea_job_system.txt
  doc/ea_job_system.txt
Labels: component:database, mode:renewal, status:code-review, type:enhancement

#8442 Max RES/MRES and max RES/MRES ignored
  conf/battle/player.conf
  src/map/battle.cpp
  src/map/battle.hpp
Labels: component:core, mode:renewal, status:code-review

#8443 Guillotine Fist SP Recovery Prevention Cleanup
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  db/re/status.yml
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: status:confirmed, component:skill, mode:renewal, mode:prerenewal

#8449 Renewal Bowling Bash Knockback
  src/map/skill.cpp
Labels: status:confirmed, component:skill, mode:renewal

#8422 Packet cleanups - const and casts
  src/map/buyingstore.cpp
  src/map/cashshop.cpp
  src/map/cashshop.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/packets.hpp
  src/map/party.cpp
  src/map/party.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/searchstore.cpp
  src/map/skill.cpp
  src/map/storage.cpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8447 Implemented NPC_DEADLYCURSE2 and NPC_DEADLYCURSE
  db/re/mob_skill_db.txt
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:skill, mode:renewal, status:code-review

#8450 Added player permission script commands
  doc/permissions.txt
  doc/script_commands.txt
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8448 Configs for account and character names and passwords minimum length
  conf/char_athena.conf
  conf/login_athena.conf
  src/char/char.cpp
  src/char/char.hpp
  src/common/mmo.hpp
  src/login/login.cpp
  src/login/login.hpp
Labels: mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#8455 Frost Joke / Scream on Party Members
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#8458 Exported missing constants for setdialogalign script command
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8460 Star Gladiator Miracle Chance
  conf/battle/skill.conf
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#8456 Fixed searchstores and added a map parameter
  db/pre-re/item_db_usable.yml
  db/re/item_db_usable.yml
  doc/script_commands.txt
  src/map/buyingstore.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets_struct.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/searchstore.cpp
  src/map/searchstore.hpp
  src/map/unit.cpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8453 Initial implementation of Shopping Boards
  npc/re/merchants/shopping_boards.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, type:enhancement

#8464 Official conversion of lasagna warps
  npc/re/custom/lasagna/warps.txt
  npc/re/scripts_athena.conf
  npc/re/scripts_warps.conf
  npc/re/warps/cities/lasagna.txt
Labels: component:script, mode:renewal, status:code-review, type:enhancement

#8457 Updated instance_check_party script command
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#8463 Fixed rand(1) locked KO job quest
  npc/re/jobs/2e/kagerou_oboro.txt
Labels: component:script, mode:renewal, type:bug

#8459 Initial release of Illusion of Teddy bear (Walkthrough conversion)
  db/re/mob_db.yml
  db/re/mob_skill_db.txt
  db/re/quest_db.yml
  npc/re/merchants/barters/enchan_illusion_dungeons.yml
  npc/re/merchants/enchan_illusion_dungeons.txt
  npc/re/mobs/dungeons/ein_dun.txt
  npc/re/quests/illusion_investigation.txt
  npc/re/quests/quests_illusion_dungeons.txt
  src/common/mmo.hpp
  src/map/npc.cpp
Labels: component:database, component:script, mode:renewal, status:code-review

#8467 Added missing clear cutin in npc folder
  npc/kafras/kafras.txt
  npc/merchants/hair_style.txt
  npc/pre-re/merchants/hair_style.txt
  npc/quests/bard_quest.txt
  npc/quests/cooking_quest.txt
  npc/quests/quests_rachel.txt
  npc/quests/seals/mjolnir_seal.txt
  npc/quests/the_sign_quest.txt
  npc/re/cities/dicastes.txt
  npc/re/custom/lasagna/lasagna_npcs.txt
  npc/re/guild3/agit_main_te.txt
  npc/re/instances/CharlestonCrisis.txt
  npc/re/instances/SealedOs.txt
  npc/re/jobs/novice/academy.txt
  npc/re/other/clans.txt
  npc/re/quests/quests_16_1.txt
  npc/re/quests/quests_16_2.txt
  npc/re/quests/quests_17_1.txt
  npc/re/quests/quests_17_2.txt
  npc/re/quests/quests_malaya.txt
  npc/re/quests/quests_mora.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#8267 Add expanded 4ths to jobmaster
  npc/custom/jobmaster.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#8470 Enchant illusion item fix
  npc/re/merchants/barters/enchan_illusion_dungeons.yml
Labels: component:script, mode:renewal, type:bug

#8472 Corrected barter shop of illusion dungeon
  npc/re/merchants/barters/enchan_illusion_dungeons.yml
Labels: component:script, mode:renewal

#8477 Uncommented quest ID related to illusion investigation (teddy bear)
  db/re/quest_db.yml
Labels: component:database, mode:renewal, status:code-review
