Repository rathena/rathena, pull requests merged in 2025-06, with the labels that each got.

#9373 Status Change Start Delay Timer
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug, type:enhancement

#9382 Battle Getenemy Cleanup
  src/map/battle.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9365 Implemented CZ_MOVE_ITEM_TO_PERSONAL
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/storage.cpp
  src/map/storage.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9387 First Official Applications of Status Delay
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal, type:bug

#9390 Slow Poison Regen Calc Flag
  db/pre-re/status.yml
  db/re/status.yml
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9391 Monster Name Cut Off Fix
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9290 Converted viewdata to array
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/elemental.cpp
  src/map/homunculus.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/navi.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/status.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9394 Skid Trap Default Direction
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9397 Random Target Mode vs. Blind
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9402 Minor Fix manuk.txt
  npc/cities/manuk.txt
Labels: component:script, mode:renewal, type:bug

#9403 Fireball Damage and AoE
  db/pre-re/mob_skill_db.txt
  db/pre-re/skill_db.yml
  db/re/mob_skill_db.txt
  db/re/skill_db.yml
  doc/mob_skill_db_powerskill.txt
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9404 Set TK_JUMPKICK TargetType to Attack
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: component:database, component:skill, mode:renewal, mode:prerenewal, type:bug

#9372 Monsters group and title updated
  db/import-tmpl/mob_db.yml
  db/mob_db.yml
  db/pre-re/mob_db.yml
  db/re/mob_db.yml
  doc/mob_db.txt
  doc/yaml/db/mob_db.yml
  npc/re/instances/HiddenGarden.txt
  npc/re/mobs/dungeons/beach_dun.txt
  src/map/mob.cpp
  src/tool/yaml2sql.cpp
Labels: component:database, component:script, mode:renewal

#9411 Fix Research Report Status
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, status:code-review

#9419 Fixed typos EndlessTower.txt
  npc/instances/EndlessTower.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8986 Implemented New Spirit Handler Skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#9434 Fix a typo for Suhnbi
  npc/merchants/advanced_refiner.txt
Labels: component:script, mode:renewal, mode:prerenewal, type:bug

#9423 Compiler Errors on Old Client
  src/map/clif.cpp
  src/map/navi.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug, type:maintenance

#9410 Added the New Nightmare Biolab Enchant and Update Enchant Rates
  npc/re/merchants/nightmare_biolab.txt
Labels: component:script, mode:renewal, status:code-review

#9438 fix a typo renters.txt
  npc/merchants/renters.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review

#9441 Updated renewal skill delay data
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
Labels: component:database, component:skill, mode:renewal, status:code-review
