Repository rathena/rathena, pull requests merged in 2025-05, with the labels that each got.

#9286 Polymorph Cast Crash Fix
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9297 Added some state resets to warping
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9289 Update laphine item IDs 101455
  db/re/laphine_upgrade.yml
Labels: component:database, mode:renewal, status:code-review, type:bug

#9278 Base Attack Min/Max Limits
  src/map/pc.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:prerenewal, type:bug

#9301 Added dummy parsing for 0xc22
  src/map/clif_packetdb.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9295 Champion Combo Chaining
  src/map/skill.cpp
  src/map/unit.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9260 Added missing trade checks
  conf/battle/items.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/pc.hpp
  src/map/trade.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9275 Add reputation points check episode 18 Budan npc
  npc/re/quests/quests_18.txt
Labels: component:script, mode:renewal, status:code-review

#9317 Cloaking / Power Maximize on Monsters
  src/map/status.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9315 Status Changes on Equip Switch
  db/pre-re/status.yml
  db/re/status.yml
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9318 Loot Priority in Party Item Share Mode
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9329 Corrected Empire Controller NPC dialogue
  npc/re/quests/quests_16_2.txt
Labels: component:script, mode:renewal, status:code-review

#9333 Corrected script Booster Combat Manual
  db/re/item_db_usable.yml
Labels: component:database, mode:renewal

#9273 Fixed instance timer
  src/map/instance.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#9332 Skill Unit Missing Range Display Issue
  src/map/skill.cpp
  src/map/skill.hpp
Labels: component:core, component:skill, mode:renewal, type:bug

#9306 Update laphine item IDs 100722 and 100723
  db/re/item_randomopt_group.yml
  db/re/laphine_upgrade.yml
Labels: component:database, mode:renewal, status:code-review

#9291 Improved clif_npc_mayapurple
  src/map/clif.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9066 Improvement of the documentation for getiteminfo command
  doc/sample/getiteminfo.txt
  doc/script_commands.txt
Labels: component:documentation, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#9342 Fixed setunitdata definition
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9280 Update refine.txt
  npc/re/merchants/refine.txt
Labels: component:script, mode:renewal, status:code-review

#9341 Path Check for Unit Skills with Range (e.g. Earthquake)
  conf/battle/skill.conf
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  doc/skill_db.txt
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal, type:bug

#9302 Fixed addmonsterdrop
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9311 Poison React
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  doc/status_change.txt
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9346 Earthquake Packets / -30000 Damage Cleanup
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/skill.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal, type:maintenance

#9352 Defender on Devotee Equip Requirement
  src/map/pc.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal, type:bug

#9354 Earth Drive Animation
  src/map/skill.cpp
Labels: component:skill, mode:renewal, type:bug

#9353 Charge Attack Knockback Immunity and Distance Calculation
  src/map/path.cpp
  src/map/path.hpp
  src/map/skill.cpp
  src/map/unit.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9340 Added GroupID and Title YAML
  db/import-tmpl/mob_db.yml
  db/mob_db.yml
  db/pre-re/mob_db.yml
  db/re/mob_db.yml
  doc/mob_db.txt
  doc/yaml/db/mob_db.yml
  doc/yaml/sql/mob_db.sql
  doc/yaml/sql/mob_db2.sql
  doc/yaml/sql/mob_db2_re.sql
  doc/yaml/sql/mob_db_re.sql
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db2_re.sql
  sql-files/mob_db_re.sql
  sql-files/upgrades/upgrade_20250525.sql
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/status.cpp
  src/tool/yaml2sql.cpp
Labels: component:database, component:core, mode:renewal, mode:prerenewal, status:code-review

#9338 Add mapname2id script command
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review

#9350 Update the description in map_msg.conf
  conf/msg_conf/map_msg.conf
Labels: component:documentation, type:enhancement

#9298 Added achievements to inter_athena.conf
  conf/inter_athena.conf
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9366 Added a hasSCE function
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9359 Pre-Renewal Monster Class/AI Database Fix
  db/pre-re/mob_db.yml
Labels: component:database, mode:prerenewal, type:bug

#9312 'Ask DeepWiki' badge added
  README.md
Labels: component:documentation, type:enhancement
