Repository rathena/rathena, pull requests merged in 2025-09, with the labels that each got.

#8671 Implemented new Night Watch skills
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#9535 Poison DEF Reduction on player
  src/map/status.cpp
Labels: status:confirmed, component:core, mode:renewal, mode:prerenewal, type:bug

#9537 Cleaned up SM_SELFPROVOKE leftovers
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9540 Fix typoes in cash food
  db/pre-re/status.yml
  db/re/status.yml
Labels: component:database, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9541 Guild Storage Update
  src/char/int_guild.cpp
  src/map/storage.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8980 Implemented ABC_ABYSS_FLAME
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#9521 Split up Acolyte skills
  src/map/map-server-generator.vcxproj
  src/map/map-server-generator.vcxproj.filters
  src/map/map-server.vcxproj
  src/map/map-server.vcxproj.filters
  src/map/skill.cpp
  src/map/skills/acolyte/angelus.cpp
  src/map/skills/acolyte/angelus.hpp
  src/map/skills/acolyte/blessing.cpp
  src/map/skills/acolyte/blessing.hpp
  src/map/skills/acolyte/crucis.cpp
  src/map/skills/acolyte/crucis.hpp
  src/map/skills/acolyte/cure.cpp
  src/map/skills/acolyte/cure.hpp
  src/map/skills/acolyte/decagi.cpp
  src/map/skills/acolyte/decagi.hpp
  src/map/skills/acolyte/heal.cpp
  src/map/skills/acolyte/heal.hpp
  src/map/skills/acolyte/holylight.cpp
  src/map/skills/acolyte/holylight.hpp
  src/map/skills/acolyte/holywater.cpp
  src/map/skills/acolyte/holywater.hpp
  src/map/skills/acolyte/incagi.cpp
  src/map/skills/acolyte/incagi.hpp
  src/map/skills/acolyte/ruwach.cpp
  src/map/skills/acolyte/ruwach.hpp
  src/map/skills/acolyte/skill_factory_acolyte.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8666 Implemented TR_RHYTHMICAL_WAVE
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/common/mmo.hpp
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:core, component:skill, mode:renewal, status:code-review

#9567 Added const support to status_get_lv
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9565 Removed struct keyword from skill_unit
  src/map/battle.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#8983 Implemented CD_DIVINUS_FLOS
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#9561 Removed struct keyword from npc_data
  src/map/atcommand.cpp
  src/map/chat.cpp
  src/map/chat.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/guild.cpp
  src/map/guild.hpp
  src/map/instance.cpp
  src/map/log.cpp
  src/map/log.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/navi.cpp
  src/map/navi.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/npc_chat.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/status.cpp
  src/map/status.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9559 Removed struct keyword from flooritem_data
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9547 Split up thief skills
  src/map/battle.cpp
  src/map/map-server-generator.vcxproj
  src/map/map-server-generator.vcxproj.filters
  src/map/map-server.vcxproj
  src/map/map-server.vcxproj.filters
  src/map/skill.cpp
  src/map/skills/thief/backslide.cpp
  src/map/skills/thief/backslide.hpp
  src/map/skills/thief/detoxify.cpp
  src/map/skills/thief/detoxify.hpp
  src/map/skills/thief/envenom.cpp
  src/map/skills/thief/envenom.hpp
  src/map/skills/thief/findstone.cpp
  src/map/skills/thief/findstone.hpp
  src/map/skills/thief/hiding.cpp
  src/map/skills/thief/hiding.hpp
  src/map/skills/thief/sandattack.cpp
  src/map/skills/thief/sandattack.hpp
  src/map/skills/thief/skill_factory_thief.cpp
  src/map/skills/thief/steal.cpp
  src/map/skills/thief/steal.hpp
  src/map/skills/thief/stonefling.cpp
  src/map/skills/thief/stonefling.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9563 Removed struct keyword from s_elemental_data
  src/map/map.cpp
  src/map/map.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance
