Repository rathena/rathena, pull requests merged in 2025-07, with the labels that each got.

#8978 Implemented New Dragon Knight Skill
  db/re/skill_db.yml
  db/re/skill_tree.yml
  src/map/battle.cpp
  src/map/skill.cpp
Labels: component:database, component:skill, mode:renewal, status:code-review

#9454 Zero damage Skills Breaking SC
  db/pre-re/status.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/mob.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:bug

#9466 Mystical Amplification Pre-Re Damage
  src/map/status.cpp
Labels: status:confirmed, component:skill, mode:prerenewal, type:bug

#9470 Provoke by Non-PC / Demon Bane
  doc/mob_skill_db_powerskill.txt
  src/map/battle.cpp
  src/map/status.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:bug

#9335 Fix CMake compilation on macOS
  .github/workflows/build_servers_cmake_osx.yml
  3rdparty/cmake/FindMYSQL.cmake
  3rdparty/libconfig/CMakeLists.txt
  CMakeLists.txt
  configure
  configure.ac
  mac.rathena-start.scpt
  src/common/socket.cpp
Labels: component:core, component:tool, mode:renewal, mode:prerenewal, type:bug
