Repository rathena/rathena, pull requests merged in 2025-02, with the labels that each got.

#9033 Fixed homunculus destructor call
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#8890 Fixed cooldown saving
  sql-files/main.sql
  sql-files/upgrades/upgrade_20250201.sql
  src/char/int_homun.cpp
  src/char/int_mercenary.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9035 Fix duplicate msg key in spanish translation
  conf/msg_conf/map_msg_spn.conf
Labels: component:database, priority:low, status:code-review, type:bug

#9030 Update Mora Shop items
  npc/re/merchants/shops.txt
Labels: component:script, mode:renewal, status:code-review

#9026 Initial implementation of /macrochecker
  conf/atcommands.yml
  conf/battle/client.conf
  conf/msg_conf/map_msg.conf
  src/map/atcommand.cpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/map.hpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9036 Added itemname support to mestitemlink
  doc/script_commands.txt
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#7416 Implemented Kachua's Secret Box NPC
  db/re/item_db_usable.yml
  npc/re/other/kachua_key.txt
  npc/re/scripts_athena.conf
Labels: component:script, mode:renewal, status:code-review, type:bug

#9037 Added missing help to atcommands.yml
  conf/atcommands.yml
  src/map/atcommand.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9042 Small ASPD code cleanup
  src/map/pc.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9045 Lullaby, Throw Stone, Sprinkle Sand, Frost Nova Fixes
  db/pre-re/skill_db.yml
  db/re/skill_db.yml
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#9048 Super Novice Spirit and Two-Handed Axes
  src/map/pc.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#9050 Converted ZC_CONFIG_NOTIFY to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9051 Converted ZC_CONGRATULATION to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9052 Converted ZC_DIVORCE to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9053 Converted ZC_EMOTION to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/homunculus.cpp
  src/map/packets.hpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9054 Converted ZC_MSG to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/mercenary.cpp
  src/map/npc.cpp
  src/map/packets.hpp
  src/map/party.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/trade.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9055 Converted ZC_MSG_COLOR to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/pc.cpp
  src/map/pet.cpp
  src/map/skill.cpp
  src/map/vending.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9057 Converted ZC_MSG_SKILL to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
  src/map/skill.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9058 Converted ZC_MSG_VALUE to struct
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/packets.hpp
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9059 Converted ZC_NOTIFY_MANNER_POINT_GIVEN to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9061 Converted ZC_SETTING_WHISPER_PC to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9062 Converted ZC_SETTING_WHISPER_STATE to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9065 Alchemist Marine Spheres (NPC_RANDOMMOVE, NPC_SPEEDUP, etc.)
  conf/battle/monster.conf
  db/import-tmpl/mob_skill_db.txt
  db/pre-re/mob_skill_db.txt
  db/re/mob_skill_db.txt
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:database, component:core, component:skill, mode:renewal, mode:prerenewal

#9071 Alchemist Marine Sphere Code Cleanup
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9067 Endure Effect Quick Fix
  src/map/clif.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal

#8947 Initial implementation of Shinkiro/Shiranui
  db/re/skill_db.yml
  db/re/skill_tree.yml
  db/re/status.yml
  src/map/battle.cpp
  src/map/party.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#9077 Stone Curse Animation + Speedup Timing Fix
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal

#9083 Unit Attack Timer Fix
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#9069 Improved Alchemist Summon Setting
  conf/battle/skill.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/skill.cpp
Labels: component:skill, mode:renewal, mode:prerenewal, type:enhancement

#9046 Cleanup for pc_setreg2 and pc_readreg2
  src/map/pc.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9086 Removed SCB_BODY code
  src/map/status.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9082 Chase Skill Fixes and Code Optimization
  src/map/mob.cpp
  src/map/unit.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal

#9087 Refactored clif_refreshlook
  src/map/clif.cpp
  src/map/clif.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9085 Cleaned up changelook script command
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9079 Fix codeql issues
  src/common/core.cpp
  src/common/strlib.cpp
  src/map/clif.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9095 Endless Loop without Official Walkpath Fix
  src/config/core.hpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#9098 Endless Loop Emergency Quick Fix
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#9105 Map Server Crash Fix when Dropping Target on Occupied Cell
  src/map/mob.cpp
Labels: component:core, mode:renewal, mode:prerenewal

#9093 Massive Monster Delay/AI Refactor
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance
