Repository rathena/rathena, pull requests merged in 2025-08, with the labels that each got.

#9435 Fixed status_change memory leak
  src/map/elemental.cpp
  src/map/homunculus.cpp
  src/map/mercenary.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9473 Added default parameters for BindColumn
  src/char/char.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_achievement.cpp
  src/char/int_quest.cpp
  src/char/int_storage.cpp
  src/common/sql.hpp
  src/map/mapreg.cpp
  src/map/storage.cpp
  src/web/charconfig_controller.cpp
  src/web/emblem_controller.cpp
  src/web/merchantstore_controller.cpp
  src/web/partybooking_controller.cpp
  src/web/userconfig_controller.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9474 Added a destructor to StringBuf
  src/char/char.cpp
  src/char/char_mapif.cpp
  src/char/int_achievement.cpp
  src/char/int_auction.cpp
  src/char/int_guild.cpp
  src/char/int_mail.cpp
  src/char/int_storage.cpp
  src/common/showmsg.cpp
  src/common/sql.cpp
  src/common/strlib.cpp
  src/common/strlib.hpp
  src/map/atcommand.cpp
  src/map/buyingstore.cpp
  src/map/clif.cpp
  src/map/log.cpp
  src/map/script.cpp
  src/map/storage.cpp
  src/map/vending.cpp
  src/web/partybooking_controller.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9481 Ensemble skills now apply fatigue
  db/re/status.yml
  src/map/skill.cpp
  src/map/status.cpp
Labels: component:database, component:core, mode:renewal, status:code-review, type:bug

#8658 Converted CZ_REQ_EMOTION to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8626 Converted ZC_UPDATE_CHARSTAT to struct
  src/map/clif.cpp
  src/map/clif_packetdb.hpp
  src/map/packets.hpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#8598 Converted ZC_USESKILL_ACK to struct
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/skill.cpp
  src/map/unit.cpp
Labels: component:core, mode:renewal, mode:prerenewal, type:maintenance

#9497 Corrected "Blitz Beat" skillratio
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal

#9498 Devotion Cast Cancel Quick Fix
  src/map/battle.cpp
Labels: component:core, component:skill, mode:renewal, mode:prerenewal, type:bug

#9453 Add hat effects to all units
  doc/script_commands.txt
  src/common/utilities.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/unit.cpp
  src/map/unit.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:enhancement

#9507 Fixed the hateffect script command
  src/map/clif.cpp
  src/map/script.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9493 Fixed Drop Rate Bonus affecting mapdrop.
  conf/battle/drops.conf
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
  src/map/mob.hpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9504 Koshei The Immortal Quest Fix
  npc/quests/quests_moscovia.txt
Labels: component:script, mode:renewal, mode:prerenewal, status:code-review, type:bug

#9522 Frost Nova AoE Pre-Renewal
  db/pre-re/skill_db.yml
Labels: component:database, status:confirmed, component:skill, mode:prerenewal, type:bug

#9516 Split up swordman skills
  src/map/battle.cpp
  src/map/map-server-generator.vcxproj
  src/map/map-server-generator.vcxproj.filters
  src/map/map-server.vcxproj
  src/map/map-server.vcxproj.filters
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/skills/status_skill_impl.cpp
  src/map/skills/status_skill_impl.hpp
  src/map/skills/swordman/autoberserk.cpp
  src/map/skills/swordman/autoberserk.hpp
  src/map/skills/swordman/magnum.cpp
  src/map/skills/swordman/magnum.hpp
  src/map/skills/swordman/provoke.cpp
  src/map/skills/swordman/provoke.hpp
  src/map/skills/swordman/selfprovoke.cpp
  src/map/skills/swordman/selfprovoke.hpp
  src/map/skills/swordman/skill_factory_swordman.cpp
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9510 Use nested namespaces from c++17
  src/char/char.hpp
  src/common/core.hpp
  src/common/utilities.hpp
  src/login/login.hpp
  src/map/map.hpp
  src/tool/csv2yaml.hpp
  src/tool/mapcache.cpp
  src/tool/yaml2sql.cpp
  src/tool/yamlupgrade.hpp
  src/web/web.hpp
Labels: component:core, priority:medium, mode:renewal, mode:prerenewal, status:code-review, type:maintenance

#9519 Linux build fixes
  3rdparty/libconfig/grammar.c
  3rdparty/yaml-cpp/src/emitterutils.cpp
  CMakeLists.txt
  src/common/CMakeLists.txt
Labels: component:core, mode:renewal, mode:prerenewal, status:code-review, type:bug
